-- The sample book: a Hardcore dwarf hunter's first evenings, then the first
-- entries of an orc, a night elf and a Forsaken, each in their own voice,
-- played through the addon in the fake game (addon/test/game.lua) as the game
-- would send them, and written by the addon's own writer.
--   luajit addon/test/sample.lua > docs/sample.md
local lives = dofile("addon/test/lives.lua")

local function chapters(G, only)
  local book = G.ns.writeBook(HearthtaleChar)
  for i, ch in ipairs(book.chapters) do
    if only and i > only then break end
    io.write(
      ("## Entry %d (%s)\n\n%s\n\n"):format(
        ch.number,
        ch.from == ch.to and ("level " .. ch.from) or ("levels %d to %d"):format(ch.from, ch.to),
        ch.text or "(nothing to tell)"
      )
    )
  end
end

-- luajit addon/test/sample.lua landing > apps/web/src/lib/samples.json (part
-- of bun run addon:seed): the site's landing page, a page of each journal: the
-- longest finished entry of four lives, each in its own voice, and the
-- epitaph of one who fell. With --check (addon:check), fails when the site's
-- copy is no longer what the writer writes.
if arg and arg[1] == "landing" then
  local json = dofile("addon/test/json.lua")
  local samples = {}
  for _, name in ipairs({ "brannok", "grashnak", "aelyndra", "mortis", "pippa" }) do
    local G = lives[name]()
    local c = HearthtaleChar
    local book = G.ns.writeBook(c)
    local s = { name = c.name, race = c.race, class = c.class, hardcore = c.hardcore or false }
    if book.epitaph then
      s.part, s.text = "epitaph", book.epitaph
    else
      local best
      for _, ch in ipairs(book.chapters) do
        if not ch.open and (not best or #ch.text > #best.text) then best = ch end
      end
      s.part, s.number, s.title, s.place, s.from, s.to, s.text =
        "entry", best.number, best.title, best.place, best.from, best.to, best.text
    end
    table.insert(samples, s)
  end
  local out = json(samples) .. "\n"
  -- --check: the site's copy must be what the writer writes now
  if arg[2] == "--check" then
    local f = io.open("apps/web/src/lib/samples.json")
    local saved = f and f:read("*a")
    if f then f:close() end
    if saved ~= out then
      io.stderr:write("apps/web/src/lib/samples.json is stale: run bun run addon:seed\n")
      os.exit(1)
    end
    return
  end
  io.write(out)
  return
end

-- luajit addon/test/sample.lua deadmines > docs/sample-deadmines.md: an evening
if arg and arg[1] == "deadmines" then
  local G = lives.edric()
  local book = G.ns.writeBook(HearthtaleChar)
  io.write("# Sample: an evening in the Deadmines\n\n")
  io.write("Generated by `luajit addon/test/sample.lua deadmines`: a human warrior met at level 18 in Stormwind\n")
  io.write("takes the Deadmines' quests, finishes the Defias Brotherhood's trail, runs the dungeon with a group\n")
  io.write("and turns everything in (`lives.edric` in addon/test/lives.lua: quests, objectives, givers, mobs,\n")
  io.write("bosses and loot as in Classic), played through the addon in the test's fake game.\n\n")
  if book.prologue then io.write("## Prologue\n\n", book.prologue, "\n\n") end
  chapters(G)
  return
end
io.write("# Sample: four journals' first entries\n\n")
io.write("Generated by `luajit addon/test/sample.lua`: lives played through the addon in the test's fake game,\n")
io.write("the events as the game sends them, written by the addon's own writer. A chapter runs from rest to rest,\n")
io.write("read as the diary entry written at the rest that ends it, in the race's own voice.\n\n")
io.write("# Brannok, a Hardcore dwarf hunter\n\n(The third entry is still being written.)\n\n")
chapters(lives.brannok())
io.write("# Grashnak, an orc warrior\n\n")
chapters(lives.grashnak())
io.write("# Aelyndra, a Hardcore night elf druid\n\n")
chapters(lives.aelyndra())
io.write("# Mortis, a Forsaken priest\n\n")
chapters(lives.mortis())
