-- The sample book: a Hardcore dwarf hunter's first evenings, then the first
-- entries of an orc, a night elf and a Forsaken, each in their own voice,
-- played through the addon in the fake game (addon/test/game.lua) as the game
-- would send them, and written by the addon's own writer.
--   luajit addon/test/sample.lua > docs/sample.md
local lives = dofile("addon/test/lives.lua")

local function chapters(G, only)
  local book = G.ns.writeBook(HearthtaleChar)
  for i, ch in ipairs(book.chapters) do
    if only and i > only then break end
    io.write(
      ("## Chapter %d (%s)\n\n%s\n\n"):format(
        ch.number,
        ch.from == ch.to and ("level " .. ch.from) or ("levels %d to %d"):format(ch.from, ch.to),
        ch.text or "(nothing to tell)"
      )
    )
  end
end

-- luajit addon/test/sample.lua deadmines > docs/sample-deadmines.md: an evening
if arg and arg[1] == "deadmines" then
  local G = lives.edric()
  local book = G.ns.writeBook(HearthtaleChar)
  io.write("# Sample: an evening in the Deadmines\n\n")
  io.write("Generated by `luajit addon/test/sample.lua deadmines`: a human warrior met at level 18 in Stormwind\n")
  io.write("takes the Deadmines' quests, finishes the Defias Brotherhood's trail, runs the dungeon with a group\n")
  io.write("and turns everything in (`lives.edric` in addon/test/lives.lua: quests, objectives, givers, mobs,\n")
  io.write("bosses and loot as in Classic), played through the addon in the test's fake game.\n\n")
  if book.prologue then io.write("## Prologue\n\n", book.prologue, "\n\n") end
  chapters(G)
  return
end
io.write("# Sample: four journals' first entries\n\n")
io.write("Generated by `luajit addon/test/sample.lua`: lives played through the addon in the test's fake game,\n")
io.write("the events as the game sends them, written by the addon's own writer. A chapter runs from rest to rest,\n")
io.write("read as the diary entry written at the rest that ends it, in the race's own voice.\n\n")
io.write("# Brannok, a Hardcore dwarf hunter\n\n(The third chapter is still being written.)\n\n")
chapters(lives.brannok())
io.write("# Grashnak, an orc warrior\n\n")
chapters(lives.grashnak())
io.write("# Aelyndra, a Hardcore night elf druid\n\n")
chapters(lives.aelyndra())
io.write("# Mortis, a Forsaken priest\n\n")
chapters(lives.mortis())
