-- The sample book: a Hardcore dwarf hunter's first evenings, played through
-- the addon in the fake game (addon/test/game.lua) as the game would send
-- them, and written by the addon's own writer.
--   luajit addon/test/sample.lua > docs/sample.md
local G = dofile("addon/test/lives.lua").brannok()

-- ── the book ─────────────────────────────────────────────────────────────────
local book = G.ns.writeBook(HearthtaleChar)
io.write("# Sample: a Hardcore dwarf hunter, the first chapters\n\n")
io.write("Generated by `luajit addon/test/sample.lua`: a life played through the addon in the test's fake game,\n")
io.write("the events as the game sends them, written by the addon's own writer. A chapter runs from rest to rest\n")
io.write("(the third is still being written).\n\n")
for _, ch in ipairs(book.chapters) do
  io.write(("## Chapter %d (%s)\n\n%s\n\n"):format(ch.number,
    ch.from == ch.to and ("level " .. ch.from) or ("levels %d to %d"):format(ch.from, ch.to), ch.text or "(nothing to tell)"))
end
