-- One synthetic day's records, changing only the narrator. This isolates
-- expression from the different starter-zone stories in lives.lua. It is
-- an editorial comparison, not a claim about a canonical quest sequence.
local voices = {}
voices.races = { "Human", "Dwarf", "NightElf", "Gnome", "Orc", "Troll", "Tauren", "Scourge", "BloodElf", "Draenei" }
voices.labels = { NightElf = "Night elf", Scourge = "Forsaken", BloodElf = "Blood elf" }

function voices.day(race, faction)
  local log = {
    { k = "quest", giver = "Gazlowe", objectives = { { type = "item", name = "Linen Cloth", n = 8 } } },
    { k = "prof", name = "Tailoring", learned = true },
    { k = "gear", link = "item:1:[Brown Linen Robe]", made = true },
    { k = "group", name = "Kelsa" },
    { k = "place", sub = "The Merchant Coast" },
    { k = "kill", name = "Southsea Brigand", kind = "Humanoid" },
    { k = "quest", giver = "Wharfmaster Dizzywig", objectives = { { type = "monster", name = "Southsea Brigand", n = 6 } } },
    { k = "close", foe = "Southsea Brigand", hp = 3 },
    { k = "quest", giver = "Wharfmaster Dizzywig", objectives = { { text = "Recover the missing cargo" } } },
    { k = "inn", sub = "Ratchet", place = "Ratchet" },
  }
  for i, m in ipairs(log) do
    m.at, m.zone, m.level = 1000 + i * 300, "The Barrens", 20
    m.sub = m.sub or (i < 5 and "Ratchet" or "The Merchant Coast")
  end
  return {
    guid = "one-day-many-voices", race = race, faction = faction,
    class = race == "BloodElf" and "MAGE" or (race == "Skyborne" and (faction == "horde" and "SHAMAN" or "MAGE") or "WARRIOR"),
    began = { level = 20 }, chapters = { {
      start = { level = 20, at = 1000, zone = "The Barrens", sub = "Ratchet" },
      log = log, quests = 3, kills = { ["Southsea Brigand"] = 6 }, played = 5400, gold = 1900,
      ended = { level = 20, place = "Ratchet", how = "rest" },
    } },
  }
end

if ... == "compare" then
  local ns = {}
  local forever = os.getenv("FOREVER") == "1"
  assert(loadfile("addon/Hearthtale/" .. (forever and "Data_Forever.lua" or "Data_Classic.lua")))("Hearthtale", ns)
  assert(loadfile("addon/Hearthtale/Names.lua"))("Hearthtale", ns)
  assert(loadfile("addon/Hearthtale/Writer.lua"))("Hearthtale", ns)
  io.write("# One day, different voices\n\n")
  io.write("A synthetic record used to compare expression, not a canonical quest sequence.\n")
  io.write("The events, their order and the selection seed are identical. Classes use valid options\n")
  io.write("for each narrator; no class ability is part of this record. Generated by\n")
  io.write("`FOREVER=1 luajit addon/test/voices.lua compare`.\n\n")
  local function show(race, faction, label)
    io.write("## " .. (label or voices.labels[race] or race) .. "\n\n")
    io.write(ns.writeBook(voices.day(race, faction)).chapters[1].text .. "\n\n")
  end
  for _, race in ipairs(voices.races) do show(race) end
  if forever then
    show("Skyborne", "horde", "Skyborne: Windshaper")
    show("Skyborne", "alliance", "Skyborne: High Order")
  end
end
return voices
