-- One synthetic day's records, changing only the narrator. This isolates
-- expression from the different starter-zone stories in lives.lua. It is
-- an editorial comparison, not a claim about a canonical quest sequence.
local voices = {}
voices.races = { "Human", "Dwarf", "NightElf", "Gnome", "Orc", "Troll", "Tauren", "Scourge" }
voices.labels = { NightElf = "Night elf", Scourge = "Forsaken" }

function voices.day(race, faction)
  local log = {
    { k = "quest", giver = "Gazlowe", objectives = { { type = "item", name = "Linen Cloth", n = 8 } } },
    { k = "prof", name = "Tailoring", learned = true },
    { k = "gear", link = "item:1:[Brown Linen Robe]", made = true },
    { k = "group", name = "Kelsa" },
    { k = "place", sub = "The Merchant Coast" },
    { k = "kill", name = "Southsea Brigand", kind = "Humanoid" },
    {
      k = "quest",
      giver = "Wharfmaster Dizzywig",
      objectives = { { type = "monster", name = "Southsea Brigand", n = 6 } },
    },
    { k = "close", foe = "Southsea Brigand", hp = 3 },
    { k = "quest", giver = "Wharfmaster Dizzywig", objectives = { { text = "Recover the missing cargo" } } },
    { k = "inn", sub = "Ratchet", place = "Ratchet" },
  }
  for i, m in ipairs(log) do
    m.at, m.zone, m.level = 1000 + i * 300, "The Barrens", 20
    m.sub = m.sub or (i < 5 and "Ratchet" or "The Merchant Coast")
  end
  return {
    guid = "one-day-many-voices",
    race = race,
    faction = faction,
    class = race == "Skyborne" and (faction == "horde" and "SHAMAN" or "MAGE") or "WARRIOR",
    began = { level = 20 },
    chapters = {
      {
        start = { level = 20, at = 1000, zone = "The Barrens", sub = "Ratchet" },
        log = log,
        quests = 3,
        kills = { ["Southsea Brigand"] = 6 },
        played = 5400,
        gold = 1900,
        ended = { level = 20, place = "Ratchet", how = "rest" },
      },
    },
  }
end

-- A few larger moments beside the routine day. The records deliberately
-- stay identical across voices, including both Skyborne traditions.
function voices.moments(race, faction)
  local c = voices.day(race, faction)
  c.guid, c.began = "larger-moments-many-voices", { level = 1 }
  local function chapter(level, log, ended)
    for i, m in ipairs(log) do
      m.at, m.zone, m.sub, m.level = 1000 + i * 300, "The Barrens", "Ratchet", level
    end
    return {
      start = { level = level, at = 1000, zone = "The Barrens", sub = "Ratchet" },
      log = log,
      quests = 0,
      kills = {},
      played = 1800,
      gold = 0,
      ended = ended,
    }
  end
  local departure = chapter(1, {
    { k = "flight", from = "Gadgetzan", to = "Everlook" },
    { k = "campfire" },
    { k = "night" },
    { k = "wake", after = "night" },
  }, { level = 1, place = "Everlook", how = "rest" })
  departure.start.zone, departure.start.sub = "Tanaris", "Gadgetzan"
  for i, m in ipairs(departure.log) do
    m.zone, m.sub = i == 1 and "Tanaris" or "Winterspring", i == 1 and "Gadgetzan" or "Everlook"
  end
  departure.log[4].at = departure.log[3].at + 8 * 3600
  c.chapters = {
    departure,
    chapter(20, {
      { k = "close", foe = "Southsea Brigand", hp = 3 },
      {
        k = "died",
        death = { cause = "foe", foe = "Southsea Brigand", level = 20, zone = "The Barrens", sub = "Ratchet" },
      },
      { k = "revived", how = "ally", by = "Kelsa" },
    }, { level = 20, place = "Ratchet", how = "rest" }),
    chapter(59, {
      { k = "dungeon", name = "The Deadmines" },
      { k = "boss", name = "Edwin VanCleef", dungeon = "The Deadmines" },
    }, { level = 60, place = "The Deadmines", how = "summit" }),
  }
  return c
end

if ... == "compare" or ... == "moments" then
  local ns = {}
  local moments = ... == "moments"
  local forever = os.getenv("FOREVER") == "1"
  assert(loadfile("addon/Hearthtale/" .. (forever and "Data_Forever.lua" or "Data_Classic.lua")))("Hearthtale", ns)
  assert(loadfile("addon/Hearthtale/Names.lua"))("Hearthtale", ns)
  dofile("addon/test/writer-files.lua")(ns)
  io.write(moments and "# Larger moments, different voices\n\n" or "# One day, different voices\n\n")
  io.write("A synthetic record used to compare expression, not a canonical quest sequence.\n")
  io.write("The events, their order and the selection seed are identical. Classes use valid options\n")
  io.write("for each narrator; no class ability is part of this record. Generated by\n")
  io.write("`FOREVER=1 luajit addon/test/voices.lua " .. (moments and "moments" or "compare") .. "`.\n\n")
  local function show(race, faction, label)
    io.write("## " .. (label or voices.labels[race] or race) .. "\n\n")
    local book = ns.writeBook(moments and voices.moments(race, faction) or voices.day(race, faction))
    local labels = { "Setting out and a night outside", "Danger, death and help", "A dungeon's end and the final page" }
    for i, ch in ipairs(book.chapters) do
      if moments then io.write("### " .. labels[i] .. "\n\n") end
      io.write(ch.text .. "\n\n")
    end
  end
  local races = moments and { "Human", "Gnome", "Troll", "Tauren" } or voices.races
  for _, race in ipairs(races) do
    show(race)
  end
  if forever then
    show("Skyborne", "horde", "Skyborne: Windshaper")
    show("Skyborne", "alliance", "Skyborne: High Order")
  end
end
return voices
