-- generated by scripts/knowledge.ts from cmangos classic-db (GPL-3.0): do not edit
-- quests[id] = { class, spell, totem }: a class's own quest, the spell it gives, a shaman's element
-- chains[id] = the first quest of its chain; ends[id]: the last of one
local _, ns = ...
local K = { quests = {}, chains = {}, ends = {} }
ns.knowledge = K
local quests, chains, ends = K.quests, K.chains, K.ends
quests[26] = { class = "DRUID" }
quests[27] = { class = "DRUID" }
quests[28] = { class = "DRUID" }
quests[29] = { class = "DRUID" }
quests[30] = { class = "DRUID" }
quests[31] = { class = "DRUID", spell = "Aquatic Form" }
quests[63] = { class = "SHAMAN" }
quests[96] = { class = "SHAMAN", spell = "Healing Stream Totem", totem = "water" }
quests[100] = { class = "SHAMAN" }
quests[220] = { class = "SHAMAN" }
quests[272] = { class = "DRUID" }
quests[397] = { class = "WARLOCK" }
quests[972] = { class = "SHAMAN" }
quests[1103] = { class = "SHAMAN" }
quests[1442] = { class = "PALADIN" }
quests[1462] = { class = "SHAMAN" }
quests[1463] = { class = "SHAMAN" }
quests[1464] = { class = "SHAMAN" }
quests[1470] = { class = "WARLOCK", spell = "Summon Imp" }
quests[1471] = { class = "WARLOCK", spell = "Summon Voidwalker" }
quests[1472] = { class = "WARLOCK" }
quests[1473] = { class = "WARLOCK" }
quests[1474] = { class = "WARLOCK", spell = "Summon Succubus" }
quests[1476] = { class = "WARLOCK" }
quests[1478] = { class = "WARLOCK" }
quests[1485] = { class = "WARLOCK", spell = "Summon Imp" }
quests[1498] = { class = "WARRIOR", spell = "Taunt" }
quests[1499] = { class = "WARLOCK" }
quests[1501] = { class = "WARLOCK" }
quests[1502] = { class = "WARRIOR" }
quests[1503] = { class = "WARRIOR" }
quests[1504] = { class = "WARLOCK", spell = "Summon Voidwalker" }
quests[1505] = { class = "WARRIOR" }
quests[1506] = { class = "WARLOCK" }
quests[1507] = { class = "WARLOCK" }
quests[1508] = { class = "WARLOCK" }
quests[1509] = { class = "WARLOCK" }
quests[1510] = { class = "WARLOCK" }
quests[1511] = { class = "WARLOCK" }
quests[1512] = { class = "WARLOCK" }
quests[1513] = { class = "WARLOCK", spell = "Summon Succubus" }
quests[1515] = { class = "WARLOCK" }
quests[1516] = { class = "SHAMAN" }
quests[1517] = { class = "SHAMAN" }
quests[1518] = { class = "SHAMAN", spell = "Stoneskin Totem", totem = "earth" }
quests[1519] = { class = "SHAMAN" }
quests[1520] = { class = "SHAMAN" }
quests[1521] = { class = "SHAMAN", spell = "Stoneskin Totem", totem = "earth" }
quests[1522] = { class = "SHAMAN" }
quests[1523] = { class = "SHAMAN" }
quests[1524] = { class = "SHAMAN" }
quests[1525] = { class = "SHAMAN" }
quests[1526] = { class = "SHAMAN" }
quests[1527] = { class = "SHAMAN", spell = "Searing Totem", totem = "fire" }
quests[1528] = { class = "SHAMAN" }
quests[1529] = { class = "SHAMAN" }
quests[1530] = { class = "SHAMAN" }
quests[1531] = { class = "SHAMAN", totem = "air" }
quests[1532] = { class = "SHAMAN", totem = "air" }
quests[1534] = { class = "SHAMAN" }
quests[1535] = { class = "SHAMAN" }
quests[1536] = { class = "SHAMAN" }
quests[1598] = { class = "WARLOCK", spell = "Summon Imp" }
quests[1599] = { class = "WARLOCK", spell = "Summon Imp" }
quests[1638] = { class = "WARRIOR" }
quests[1639] = { class = "WARRIOR" }
quests[1640] = { class = "WARRIOR" }
quests[1641] = { class = "PALADIN" }
quests[1642] = { class = "PALADIN" }
quests[1643] = { class = "PALADIN" }
quests[1644] = { class = "PALADIN" }
quests[1645] = { class = "PALADIN" }
quests[1646] = { class = "PALADIN" }
quests[1647] = { class = "PALADIN" }
quests[1648] = { class = "PALADIN" }
quests[1649] = { class = "PALADIN" }
quests[1650] = { class = "PALADIN" }
quests[1651] = { class = "PALADIN" }
quests[1652] = { class = "PALADIN", spell = "Sense Undead" }
quests[1653] = { class = "PALADIN" }
quests[1654] = { class = "PALADIN" }
quests[1655] = { class = "PALADIN" }
quests[1661] = { class = "PALADIN" }
quests[1665] = { class = "WARRIOR", spell = "Taunt" }
quests[1666] = { class = "WARRIOR" }
quests[1667] = { class = "WARRIOR" }
quests[1678] = { class = "WARRIOR", spell = "Taunt" }
quests[1679] = { class = "WARRIOR" }
quests[1680] = { class = "WARRIOR" }
quests[1681] = { class = "WARRIOR" }
quests[1682] = { class = "WARRIOR" }
quests[1683] = { class = "WARRIOR", spell = "Taunt" }
quests[1684] = { class = "WARRIOR" }
quests[1685] = { class = "WARLOCK" }
quests[1686] = { class = "WARRIOR" }
quests[1688] = { class = "WARLOCK" }
quests[1689] = { class = "WARLOCK", spell = "Summon Voidwalker" }
quests[1692] = { class = "WARRIOR" }
quests[1693] = { class = "WARRIOR" }
quests[1698] = { class = "WARRIOR" }
quests[1699] = { class = "WARRIOR" }
quests[1700] = { class = "WARRIOR" }
quests[1701] = { class = "WARRIOR" }
quests[1702] = { class = "WARRIOR" }
quests[1703] = { class = "WARRIOR" }
quests[1704] = { class = "WARRIOR" }
quests[1705] = { class = "WARRIOR" }
quests[1706] = { class = "WARRIOR" }
quests[1708] = { class = "WARRIOR" }
quests[1709] = { class = "WARRIOR" }
quests[1710] = { class = "WARRIOR" }
quests[1711] = { class = "WARRIOR" }
quests[1712] = { class = "WARRIOR" }
quests[1713] = { class = "WARRIOR" }
quests[1714] = { class = "WARRIOR" }
quests[1715] = { class = "WARLOCK" }
quests[1716] = { class = "WARLOCK" }
quests[1717] = { class = "WARLOCK" }
quests[1718] = { class = "WARRIOR" }
quests[1719] = { class = "WARRIOR", spell = "Intercept" }
quests[1738] = { class = "WARLOCK" }
quests[1739] = { class = "WARLOCK", spell = "Summon Succubus" }
quests[1740] = { class = "WARLOCK" }
quests[1758] = { class = "WARLOCK" }
quests[1778] = { class = "PALADIN" }
quests[1779] = { class = "PALADIN" }
quests[1780] = { class = "PALADIN" }
quests[1781] = { class = "PALADIN" }
quests[1782] = { class = "WARRIOR" }
quests[1783] = { class = "PALADIN" }
quests[1784] = { class = "PALADIN" }
quests[1785] = { class = "PALADIN", spell = "Redemption" }
quests[1786] = { class = "PALADIN" }
quests[1787] = { class = "PALADIN" }
quests[1788] = { class = "PALADIN", spell = "Redemption" }
quests[1789] = { class = "PALADIN" }
quests[1790] = { class = "PALADIN" }
quests[1791] = { class = "WARRIOR" }
quests[1792] = { class = "WARRIOR" }
quests[1793] = { class = "PALADIN" }
quests[1794] = { class = "PALADIN" }
quests[1795] = { class = "WARLOCK", spell = "Summon Felhunter" }
quests[1796] = { class = "WARLOCK" }
quests[1798] = { class = "WARLOCK" }
quests[1799] = { class = "WARLOCK" }
quests[1801] = { class = "WARLOCK" }
quests[1802] = { class = "WARLOCK" }
quests[1803] = { class = "WARLOCK" }
quests[1804] = { class = "WARLOCK" }
quests[1805] = { class = "WARLOCK" }
quests[1806] = { class = "PALADIN" }
quests[1818] = { class = "WARRIOR" }
quests[1819] = { class = "WARRIOR", spell = "Taunt" }
quests[1820] = { class = "WARRIOR" }
quests[1821] = { class = "WARRIOR" }
quests[1822] = { class = "WARRIOR" }
quests[1823] = { class = "WARRIOR" }
quests[1824] = { class = "WARRIOR" }
quests[1825] = { class = "WARRIOR" }
quests[1838] = { class = "WARRIOR" }
quests[1839] = { class = "WARRIOR" }
quests[1840] = { class = "WARRIOR" }
quests[1841] = { class = "WARRIOR" }
quests[1842] = { class = "WARRIOR" }
quests[1843] = { class = "WARRIOR" }
quests[1844] = { class = "WARRIOR" }
quests[1845] = { class = "WARRIOR" }
quests[1846] = { class = "WARRIOR" }
quests[1847] = { class = "WARRIOR" }
quests[1848] = { class = "WARRIOR" }
quests[1858] = { class = "ROGUE" }
quests[1859] = { class = "ROGUE" }
quests[1860] = { class = "MAGE" }
quests[1861] = { class = "MAGE" }
quests[1879] = { class = "MAGE" }
quests[1880] = { class = "MAGE" }
quests[1881] = { class = "MAGE" }
quests[1882] = { class = "MAGE" }
quests[1883] = { class = "MAGE" }
quests[1884] = { class = "MAGE" }
quests[1885] = { class = "ROGUE" }
quests[1886] = { class = "ROGUE" }
quests[1898] = { class = "ROGUE" }
quests[1899] = { class = "ROGUE" }
quests[1919] = { class = "MAGE" }
quests[1920] = { class = "MAGE" }
quests[1921] = { class = "MAGE" }
quests[1938] = { class = "MAGE" }
quests[1939] = { class = "MAGE" }
quests[1940] = { class = "MAGE" }
quests[1941] = { class = "MAGE" }
quests[1942] = { class = "MAGE" }
quests[1943] = { class = "MAGE" }
quests[1944] = { class = "MAGE" }
quests[1945] = { class = "MAGE" }
quests[1946] = { class = "MAGE" }
quests[1947] = { class = "MAGE" }
quests[1948] = { class = "MAGE" }
quests[1949] = { class = "MAGE" }
quests[1950] = { class = "MAGE" }
quests[1951] = { class = "MAGE" }
quests[1952] = { class = "MAGE" }
quests[1953] = { class = "MAGE" }
quests[1954] = { class = "MAGE" }
quests[1955] = { class = "MAGE" }
quests[1956] = { class = "MAGE" }
quests[1957] = { class = "MAGE" }
quests[1958] = { class = "MAGE" }
quests[1959] = { class = "MAGE" }
quests[1960] = { class = "MAGE" }
quests[1961] = { class = "MAGE" }
quests[1962] = { class = "MAGE" }
quests[1963] = { class = "ROGUE" }
quests[1978] = { class = "ROGUE" }
quests[1998] = { class = "ROGUE" }
quests[1999] = { class = "ROGUE" }
quests[2205] = { class = "ROGUE" }
quests[2206] = { class = "ROGUE" }
quests[2218] = { class = "ROGUE" }
quests[2238] = { class = "ROGUE" }
quests[2239] = { class = "ROGUE" }
quests[2241] = { class = "ROGUE" }
quests[2242] = { class = "ROGUE" }
quests[2259] = { class = "ROGUE" }
quests[2260] = { class = "ROGUE" }
quests[2281] = { class = "ROGUE" }
quests[2282] = { class = "ROGUE" }
quests[2298] = { class = "ROGUE" }
quests[2299] = { class = "ROGUE" }
quests[2300] = { class = "ROGUE" }
quests[2358] = { class = "ROGUE" }
quests[2359] = { class = "ROGUE", spell = "Poisons" }
quests[2360] = { class = "ROGUE" }
quests[2378] = { class = "ROGUE" }
quests[2379] = { class = "ROGUE" }
quests[2380] = { class = "ROGUE" }
quests[2381] = { class = "ROGUE" }
quests[2382] = { class = "ROGUE" }
quests[2383] = { class = "WARRIOR" }
quests[2458] = { class = "ROGUE" }
quests[2460] = { class = "ROGUE" }
quests[2478] = { class = "ROGUE" }
quests[2479] = { class = "ROGUE" }
quests[2480] = { class = "ROGUE", spell = "Poisons" }
quests[2607] = { class = "ROGUE" }
quests[2608] = { class = "ROGUE" }
quests[2609] = { class = "ROGUE" }
quests[2983] = { class = "SHAMAN" }
quests[2984] = { class = "SHAMAN" }
quests[2985] = { class = "SHAMAN" }
quests[2986] = { class = "SHAMAN" }
quests[2996] = { class = "WARLOCK" }
quests[2997] = { class = "PALADIN" }
quests[2998] = { class = "PALADIN" }
quests[2999] = { class = "PALADIN" }
quests[3000] = { class = "PALADIN" }
quests[3001] = { class = "WARLOCK" }
quests[3065] = { class = "WARRIOR" }
quests[3082] = { class = "HUNTER" }
quests[3083] = { class = "ROGUE" }
quests[3084] = { class = "SHAMAN" }
quests[3085] = { class = "PRIEST" }
quests[3086] = { class = "MAGE" }
quests[3087] = { class = "HUNTER" }
quests[3088] = { class = "ROGUE" }
quests[3089] = { class = "SHAMAN" }
quests[3090] = { class = "WARLOCK" }
quests[3091] = { class = "WARRIOR" }
quests[3092] = { class = "HUNTER" }
quests[3093] = { class = "SHAMAN" }
quests[3094] = { class = "DRUID" }
quests[3095] = { class = "WARRIOR" }
quests[3096] = { class = "ROGUE" }
quests[3097] = { class = "PRIEST" }
quests[3098] = { class = "MAGE" }
quests[3099] = { class = "WARLOCK" }
quests[3100] = { class = "WARRIOR" }
quests[3101] = { class = "PALADIN" }
quests[3102] = { class = "ROGUE" }
quests[3103] = { class = "PRIEST" }
quests[3104] = { class = "MAGE" }
quests[3105] = { class = "WARLOCK" }
quests[3106] = { class = "WARRIOR" }
quests[3107] = { class = "PALADIN" }
quests[3108] = { class = "HUNTER" }
quests[3109] = { class = "ROGUE" }
quests[3110] = { class = "PRIEST" }
quests[3112] = { class = "WARRIOR" }
quests[3113] = { class = "ROGUE" }
quests[3114] = { class = "MAGE" }
quests[3115] = { class = "WARLOCK" }
quests[3116] = { class = "WARRIOR" }
quests[3117] = { class = "HUNTER" }
quests[3118] = { class = "ROGUE" }
quests[3119] = { class = "PRIEST" }
quests[3120] = { class = "DRUID" }
quests[3631] = { class = "WARLOCK" }
quests[3681] = { class = "PALADIN" }
quests[4485] = { class = "PALADIN" }
quests[4486] = { class = "PALADIN" }
quests[4487] = { class = "WARLOCK" }
quests[4488] = { class = "WARLOCK" }
quests[4489] = { class = "WARLOCK" }
quests[4490] = { class = "WARLOCK", spell = "Summon Felsteed" }
quests[4736] = { class = "WARLOCK" }
quests[4737] = { class = "WARLOCK" }
quests[4738] = { class = "WARLOCK" }
quests[4739] = { class = "WARLOCK" }
quests[4781] = { class = "WARLOCK" }
quests[4782] = { class = "WARLOCK" }
quests[4783] = { class = "WARLOCK" }
quests[4784] = { class = "WARLOCK" }
quests[4785] = { class = "WARLOCK" }
quests[4786] = { class = "WARLOCK" }
quests[4961] = { class = "WARLOCK" }
quests[4962] = { class = "WARLOCK" }
quests[4963] = { class = "WARLOCK" }
quests[4964] = { class = "WARLOCK" }
quests[4965] = { class = "WARLOCK" }
quests[4967] = { class = "WARLOCK" }
quests[4968] = { class = "WARLOCK" }
quests[4969] = { class = "WARLOCK" }
quests[4975] = { class = "WARLOCK" }
quests[4976] = { class = "WARLOCK" }
quests[5061] = { class = "DRUID", spell = "Aquatic Form" }
quests[5621] = { class = "PRIEST" }
quests[5622] = { class = "PRIEST" }
quests[5623] = { class = "PRIEST" }
quests[5624] = { class = "PRIEST" }
quests[5625] = { class = "PRIEST" }
quests[5626] = { class = "PRIEST" }
quests[5627] = { class = "PRIEST" }
quests[5628] = { class = "PRIEST", spell = "Starshards" }
quests[5629] = { class = "PRIEST", spell = "Starshards" }
quests[5630] = { class = "PRIEST", spell = "Starshards" }
quests[5631] = { class = "PRIEST", spell = "Starshards" }
quests[5632] = { class = "PRIEST", spell = "Starshards" }
quests[5633] = { class = "PRIEST", spell = "Starshards" }
quests[5634] = { class = "PRIEST", spell = "Desperate Prayer" }
quests[5635] = { class = "PRIEST", spell = "Desperate Prayer" }
quests[5636] = { class = "PRIEST", spell = "Desperate Prayer" }
quests[5637] = { class = "PRIEST", spell = "Desperate Prayer" }
quests[5638] = { class = "PRIEST", spell = "Desperate Prayer" }
quests[5639] = { class = "PRIEST", spell = "Desperate Prayer" }
quests[5641] = { class = "PRIEST", spell = "Fear Ward" }
quests[5642] = { class = "PRIEST", spell = "Shadowguard" }
quests[5643] = { class = "PRIEST", spell = "Shadowguard" }
quests[5644] = { class = "PRIEST", spell = "Devouring Plague" }
quests[5645] = { class = "PRIEST", spell = "Fear Ward" }
quests[5646] = { class = "PRIEST", spell = "Devouring Plague" }
quests[5647] = { class = "PRIEST", spell = "Fear Ward" }
quests[5648] = { class = "PRIEST" }
quests[5649] = { class = "PRIEST" }
quests[5650] = { class = "PRIEST" }
quests[5651] = { class = "PRIEST" }
quests[5652] = { class = "PRIEST", spell = "Hex of Weakness" }
quests[5654] = { class = "PRIEST", spell = "Hex of Weakness" }
quests[5655] = { class = "PRIEST", spell = "Hex of Weakness" }
quests[5656] = { class = "PRIEST", spell = "Hex of Weakness" }
quests[5657] = { class = "PRIEST", spell = "Hex of Weakness" }
quests[5658] = { class = "PRIEST", spell = "Touch of Weakness" }
quests[5660] = { class = "PRIEST", spell = "Touch of Weakness" }
quests[5661] = { class = "PRIEST", spell = "Touch of Weakness" }
quests[5662] = { class = "PRIEST", spell = "Touch of Weakness" }
quests[5663] = { class = "PRIEST", spell = "Touch of Weakness" }
quests[5672] = { class = "PRIEST", spell = "Elune's Grace" }
quests[5673] = { class = "PRIEST", spell = "Elune's Grace" }
quests[5674] = { class = "PRIEST", spell = "Elune's Grace" }
quests[5675] = { class = "PRIEST", spell = "Elune's Grace" }
quests[5676] = { class = "PRIEST", spell = "Feedback" }
quests[5677] = { class = "PRIEST", spell = "Desperate Prayer" }
quests[5679] = { class = "PRIEST", spell = "Devouring Plague" }
quests[5680] = { class = "PRIEST", spell = "Shadowguard" }
quests[5921] = { class = "DRUID" }
quests[5922] = { class = "DRUID" }
quests[5923] = { class = "DRUID" }
quests[5924] = { class = "DRUID" }
quests[5925] = { class = "DRUID" }
quests[5926] = { class = "DRUID" }
quests[5927] = { class = "DRUID" }
quests[5928] = { class = "DRUID" }
quests[5929] = { class = "DRUID" }
quests[5930] = { class = "DRUID" }
quests[5931] = { class = "DRUID" }
quests[5932] = { class = "DRUID" }
quests[6001] = { class = "DRUID", spell = "Maul" }
quests[6002] = { class = "DRUID", spell = "Maul" }
quests[6061] = { class = "HUNTER" }
quests[6062] = { class = "HUNTER" }
quests[6063] = { class = "HUNTER" }
quests[6064] = { class = "HUNTER" }
quests[6065] = { class = "HUNTER" }
quests[6066] = { class = "HUNTER" }
quests[6067] = { class = "HUNTER" }
quests[6068] = { class = "HUNTER" }
quests[6069] = { class = "HUNTER" }
quests[6070] = { class = "HUNTER" }
quests[6071] = { class = "HUNTER" }
quests[6072] = { class = "HUNTER" }
quests[6073] = { class = "HUNTER" }
quests[6074] = { class = "HUNTER" }
quests[6075] = { class = "HUNTER" }
quests[6076] = { class = "HUNTER" }
quests[6081] = { class = "HUNTER", spell = "Revive Pet" }
quests[6082] = { class = "HUNTER", spell = "Dismiss Pet" }
quests[6083] = { class = "HUNTER" }
quests[6084] = { class = "HUNTER" }
quests[6085] = { class = "HUNTER", spell = "Dismiss Pet" }
quests[6086] = { class = "HUNTER", spell = "Revive Pet" }
quests[6087] = { class = "HUNTER" }
quests[6088] = { class = "HUNTER", spell = "Dismiss Pet" }
quests[6089] = { class = "HUNTER", spell = "Revive Pet" }
quests[6101] = { class = "HUNTER" }
quests[6102] = { class = "HUNTER", spell = "Dismiss Pet" }
quests[6103] = { class = "HUNTER", spell = "Revive Pet" }
quests[6121] = { class = "DRUID" }
quests[6122] = { class = "DRUID" }
quests[6123] = { class = "DRUID" }
quests[6124] = { class = "DRUID" }
quests[6125] = { class = "DRUID", spell = "Cure Poison" }
quests[6126] = { class = "DRUID" }
quests[6127] = { class = "DRUID" }
quests[6128] = { class = "DRUID" }
quests[6129] = { class = "DRUID" }
quests[6130] = { class = "DRUID", spell = "Cure Poison" }
quests[6681] = { class = "ROGUE" }
quests[6701] = { class = "ROGUE" }
quests[6721] = { class = "HUNTER" }
quests[6722] = { class = "HUNTER" }
quests[7463] = { class = "MAGE", spell = "Conjure Water" }
quests[7498] = { class = "ROGUE" }
quests[7499] = { class = "WARRIOR" }
quests[7500] = { class = "MAGE" }
quests[7501] = { class = "PALADIN" }
quests[7502] = { class = "WARLOCK" }
quests[7503] = { class = "HUNTER" }
quests[7504] = { class = "PRIEST" }
quests[7505] = { class = "SHAMAN" }
quests[7506] = { class = "DRUID" }
quests[7562] = { class = "WARLOCK" }
quests[7563] = { class = "WARLOCK" }
quests[7564] = { class = "WARLOCK" }
quests[7581] = { class = "WARLOCK" }
quests[7582] = { class = "WARLOCK" }
quests[7583] = { class = "WARLOCK", spell = "Ritual of Doom" }
quests[7601] = { class = "WARLOCK" }
quests[7602] = { class = "WARLOCK" }
quests[7603] = { class = "WARLOCK", spell = "Inferno" }
quests[7621] = { class = "PRIEST" }
quests[7622] = { class = "PRIEST" }
quests[7623] = { class = "WARLOCK" }
quests[7624] = { class = "WARLOCK" }
quests[7625] = { class = "WARLOCK" }
quests[7626] = { class = "WARLOCK" }
quests[7627] = { class = "WARLOCK" }
quests[7628] = { class = "WARLOCK" }
quests[7629] = { class = "WARLOCK" }
quests[7630] = { class = "WARLOCK" }
quests[7631] = { class = "WARLOCK" }
quests[7632] = { class = "HUNTER" }
quests[7633] = { class = "HUNTER" }
quests[7634] = { class = "HUNTER" }
quests[7635] = { class = "HUNTER" }
quests[7636] = { class = "HUNTER" }
quests[7637] = { class = "PALADIN" }
quests[7638] = { class = "PALADIN" }
quests[7639] = { class = "PALADIN" }
quests[7640] = { class = "PALADIN" }
quests[7641] = { class = "PALADIN" }
quests[7642] = { class = "PALADIN" }
quests[7643] = { class = "PALADIN" }
quests[7644] = { class = "PALADIN" }
quests[7645] = { class = "PALADIN" }
quests[7646] = { class = "PALADIN" }
quests[7647] = { class = "PALADIN" }
quests[7648] = { class = "PALADIN" }
quests[7666] = { class = "PALADIN" }
quests[7667] = { class = "SHAMAN" }
quests[8041] = { class = "WARRIOR" }
quests[8042] = { class = "WARRIOR" }
quests[8043] = { class = "WARRIOR" }
quests[8044] = { class = "WARRIOR" }
quests[8045] = { class = "PALADIN" }
quests[8046] = { class = "PALADIN" }
quests[8047] = { class = "PALADIN" }
quests[8048] = { class = "PALADIN" }
quests[8049] = { class = "PRIEST" }
quests[8050] = { class = "PRIEST" }
quests[8051] = { class = "PRIEST" }
quests[8052] = { class = "PRIEST" }
quests[8053] = { class = "PALADIN" }
quests[8054] = { class = "PALADIN" }
quests[8055] = { class = "PALADIN" }
quests[8056] = { class = "SHAMAN" }
quests[8057] = { class = "DRUID" }
quests[8058] = { class = "WARRIOR" }
quests[8059] = { class = "WARLOCK" }
quests[8060] = { class = "MAGE" }
quests[8061] = { class = "PRIEST" }
quests[8062] = { class = "HUNTER" }
quests[8063] = { class = "ROGUE" }
quests[8064] = { class = "DRUID" }
quests[8065] = { class = "DRUID" }
quests[8066] = { class = "HUNTER" }
quests[8067] = { class = "HUNTER" }
quests[8068] = { class = "MAGE" }
quests[8069] = { class = "MAGE" }
quests[8070] = { class = "PRIEST" }
quests[8071] = { class = "PRIEST" }
quests[8072] = { class = "ROGUE" }
quests[8073] = { class = "ROGUE" }
quests[8074] = { class = "SHAMAN" }
quests[8075] = { class = "SHAMAN" }
quests[8076] = { class = "WARLOCK" }
quests[8077] = { class = "WARLOCK" }
quests[8078] = { class = "WARRIOR" }
quests[8079] = { class = "WARRIOR" }
quests[8101] = { class = "MAGE" }
quests[8102] = { class = "MAGE" }
quests[8103] = { class = "MAGE" }
quests[8104] = { class = "MAGE" }
quests[8106] = { class = "WARLOCK" }
quests[8107] = { class = "WARLOCK" }
quests[8108] = { class = "WARLOCK" }
quests[8109] = { class = "WARLOCK" }
quests[8110] = { class = "DRUID" }
quests[8111] = { class = "DRUID" }
quests[8112] = { class = "DRUID" }
quests[8113] = { class = "DRUID" }
quests[8116] = { class = "SHAMAN" }
quests[8117] = { class = "SHAMAN" }
quests[8118] = { class = "SHAMAN" }
quests[8119] = { class = "SHAMAN" }
quests[8141] = { class = "ROGUE" }
quests[8142] = { class = "ROGUE" }
quests[8143] = { class = "ROGUE" }
quests[8144] = { class = "ROGUE" }
quests[8145] = { class = "HUNTER" }
quests[8146] = { class = "HUNTER" }
quests[8147] = { class = "HUNTER" }
quests[8148] = { class = "HUNTER" }
quests[8151] = { class = "HUNTER" }
quests[8153] = { class = "HUNTER" }
quests[8231] = { class = "HUNTER" }
quests[8232] = { class = "HUNTER" }
quests[8233] = { class = "ROGUE" }
quests[8234] = { class = "ROGUE" }
quests[8235] = { class = "ROGUE" }
quests[8236] = { class = "ROGUE" }
quests[8249] = { class = "ROGUE" }
quests[8250] = { class = "MAGE" }
quests[8251] = { class = "MAGE" }
quests[8252] = { class = "MAGE" }
quests[8253] = { class = "MAGE" }
quests[8254] = { class = "PRIEST" }
quests[8255] = { class = "PRIEST" }
quests[8256] = { class = "PRIEST" }
quests[8257] = { class = "PRIEST" }
quests[8258] = { class = "SHAMAN" }
quests[8316] = { class = "WARRIOR" }
quests[8376] = { class = "PALADIN" }
quests[8377] = { class = "HUNTER" }
quests[8378] = { class = "ROGUE" }
quests[8379] = { class = "PRIEST" }
quests[8380] = { class = "SHAMAN" }
quests[8382] = { class = "DRUID" }
quests[8410] = { class = "SHAMAN" }
quests[8411] = { class = "SHAMAN" }
quests[8412] = { class = "SHAMAN" }
quests[8413] = { class = "SHAMAN" }
quests[8414] = { class = "PALADIN" }
quests[8415] = { class = "PALADIN" }
quests[8416] = { class = "PALADIN" }
quests[8417] = { class = "WARRIOR" }
quests[8418] = { class = "PALADIN" }
quests[8419] = { class = "WARLOCK" }
quests[8420] = { class = "WARLOCK" }
quests[8421] = { class = "WARLOCK" }
quests[8422] = { class = "WARLOCK" }
quests[8423] = { class = "WARRIOR" }
quests[8424] = { class = "WARRIOR" }
quests[8425] = { class = "WARRIOR" }
quests[8544] = { class = "WARRIOR" }
quests[8556] = { class = "WARRIOR" }
quests[8557] = { class = "WARRIOR" }
quests[8558] = { class = "WARRIOR" }
quests[8559] = { class = "WARRIOR" }
quests[8560] = { class = "WARRIOR" }
quests[8561] = { class = "WARRIOR" }
quests[8562] = { class = "WARRIOR" }
quests[8592] = { class = "PRIEST" }
quests[8593] = { class = "PRIEST" }
quests[8594] = { class = "PRIEST" }
quests[8596] = { class = "PRIEST" }
quests[8602] = { class = "SHAMAN" }
quests[8603] = { class = "PRIEST" }
quests[8621] = { class = "SHAMAN" }
quests[8622] = { class = "SHAMAN" }
quests[8623] = { class = "SHAMAN" }
quests[8624] = { class = "SHAMAN" }
quests[8625] = { class = "MAGE" }
quests[8626] = { class = "HUNTER" }
quests[8627] = { class = "PALADIN" }
quests[8628] = { class = "PALADIN" }
quests[8629] = { class = "PALADIN" }
quests[8630] = { class = "PALADIN" }
quests[8631] = { class = "MAGE" }
quests[8632] = { class = "MAGE" }
quests[8633] = { class = "MAGE" }
quests[8634] = { class = "MAGE" }
quests[8637] = { class = "ROGUE" }
quests[8638] = { class = "ROGUE" }
quests[8639] = { class = "ROGUE" }
quests[8640] = { class = "ROGUE" }
quests[8641] = { class = "ROGUE" }
quests[8655] = { class = "PALADIN" }
quests[8656] = { class = "HUNTER" }
quests[8657] = { class = "HUNTER" }
quests[8658] = { class = "HUNTER" }
quests[8659] = { class = "HUNTER" }
quests[8660] = { class = "WARLOCK" }
quests[8661] = { class = "WARLOCK" }
quests[8662] = { class = "WARLOCK" }
quests[8663] = { class = "WARLOCK" }
quests[8664] = { class = "WARLOCK" }
quests[8665] = { class = "DRUID" }
quests[8666] = { class = "DRUID" }
quests[8667] = { class = "DRUID" }
quests[8668] = { class = "DRUID" }
quests[8669] = { class = "DRUID" }
quests[8689] = { class = "PRIEST" }
quests[8690] = { class = "SHAMAN" }
quests[8691] = { class = "MAGE" }
quests[8692] = { class = "DRUID" }
quests[8693] = { class = "ROGUE" }
quests[8694] = { class = "WARLOCK" }
quests[8695] = { class = "PALADIN" }
quests[8696] = { class = "HUNTER" }
quests[8697] = { class = "PRIEST" }
quests[8698] = { class = "SHAMAN" }
quests[8699] = { class = "MAGE" }
quests[8700] = { class = "DRUID" }
quests[8701] = { class = "ROGUE" }
quests[8702] = { class = "WARLOCK" }
quests[8703] = { class = "PALADIN" }
quests[8704] = { class = "HUNTER" }
quests[8705] = { class = "PRIEST" }
quests[8706] = { class = "SHAMAN" }
quests[8707] = { class = "MAGE" }
quests[8708] = { class = "DRUID" }
quests[8709] = { class = "ROGUE" }
quests[8710] = { class = "WARLOCK" }
quests[8711] = { class = "PALADIN" }
quests[8712] = { class = "HUNTER" }
quests[8905] = { class = "DRUID" }
quests[8906] = { class = "HUNTER" }
quests[8907] = { class = "MAGE" }
quests[8908] = { class = "PALADIN" }
quests[8909] = { class = "PRIEST" }
quests[8910] = { class = "ROGUE" }
quests[8911] = { class = "WARLOCK" }
quests[8912] = { class = "WARRIOR" }
quests[8913] = { class = "DRUID" }
quests[8914] = { class = "HUNTER" }
quests[8915] = { class = "MAGE" }
quests[8916] = { class = "PRIEST" }
quests[8917] = { class = "ROGUE" }
quests[8918] = { class = "SHAMAN" }
quests[8919] = { class = "WARLOCK" }
quests[8920] = { class = "WARRIOR" }
quests[8926] = { class = "DRUID" }
quests[8927] = { class = "DRUID" }
quests[8931] = { class = "HUNTER" }
quests[8932] = { class = "MAGE" }
quests[8933] = { class = "PALADIN" }
quests[8934] = { class = "PRIEST" }
quests[8935] = { class = "ROGUE" }
quests[8936] = { class = "WARLOCK" }
quests[8937] = { class = "WARRIOR" }
quests[8938] = { class = "HUNTER" }
quests[8939] = { class = "MAGE" }
quests[8940] = { class = "PRIEST" }
quests[8941] = { class = "ROGUE" }
quests[8942] = { class = "SHAMAN" }
quests[8943] = { class = "WARLOCK" }
quests[8944] = { class = "WARRIOR" }
quests[8951] = { class = "DRUID" }
quests[8952] = { class = "HUNTER" }
quests[8953] = { class = "MAGE" }
quests[8954] = { class = "PALADIN" }
quests[8955] = { class = "PRIEST" }
quests[8956] = { class = "ROGUE" }
quests[8957] = { class = "SHAMAN" }
quests[8958] = { class = "WARLOCK" }
quests[8959] = { class = "WARRIOR" }
quests[8999] = { class = "DRUID" }
quests[9000] = { class = "HUNTER" }
quests[9001] = { class = "MAGE" }
quests[9002] = { class = "PALADIN" }
quests[9003] = { class = "PRIEST" }
quests[9004] = { class = "ROGUE" }
quests[9005] = { class = "WARLOCK" }
quests[9006] = { class = "WARRIOR" }
quests[9007] = { class = "DRUID" }
quests[9008] = { class = "HUNTER" }
quests[9009] = { class = "PRIEST" }
quests[9010] = { class = "ROGUE" }
quests[9011] = { class = "SHAMAN" }
quests[9012] = { class = "WARLOCK" }
quests[9013] = { class = "WARRIOR" }
quests[9014] = { class = "MAGE" }
quests[9016] = { class = "DRUID" }
quests[9017] = { class = "HUNTER" }
quests[9018] = { class = "MAGE" }
quests[9019] = { class = "PRIEST" }
quests[9020] = { class = "ROGUE" }
quests[9021] = { class = "WARLOCK" }
quests[9022] = { class = "WARRIOR" }
quests[9034] = { class = "WARRIOR" }
quests[9036] = { class = "WARRIOR" }
quests[9037] = { class = "WARRIOR" }
quests[9038] = { class = "WARRIOR" }
quests[9039] = { class = "WARRIOR" }
quests[9040] = { class = "WARRIOR" }
quests[9041] = { class = "WARRIOR" }
quests[9042] = { class = "WARRIOR" }
quests[9043] = { class = "PALADIN" }
quests[9044] = { class = "PALADIN" }
quests[9045] = { class = "PALADIN" }
quests[9046] = { class = "PALADIN" }
quests[9047] = { class = "PALADIN" }
quests[9048] = { class = "PALADIN" }
quests[9049] = { class = "PALADIN" }
quests[9050] = { class = "PALADIN" }
quests[9051] = { class = "DRUID" }
quests[9052] = { class = "DRUID" }
quests[9053] = { class = "DRUID" }
quests[9054] = { class = "HUNTER" }
quests[9055] = { class = "HUNTER" }
quests[9056] = { class = "HUNTER" }
quests[9057] = { class = "HUNTER" }
quests[9058] = { class = "HUNTER" }
quests[9059] = { class = "HUNTER" }
quests[9060] = { class = "HUNTER" }
quests[9061] = { class = "HUNTER" }
quests[9063] = { class = "DRUID" }
quests[9068] = { class = "SHAMAN" }
quests[9069] = { class = "SHAMAN" }
quests[9070] = { class = "SHAMAN" }
quests[9071] = { class = "SHAMAN" }
quests[9072] = { class = "SHAMAN" }
quests[9073] = { class = "SHAMAN" }
quests[9074] = { class = "SHAMAN" }
quests[9075] = { class = "SHAMAN" }
quests[9077] = { class = "ROGUE" }
quests[9078] = { class = "ROGUE" }
quests[9079] = { class = "ROGUE" }
quests[9080] = { class = "ROGUE" }
quests[9081] = { class = "ROGUE" }
quests[9082] = { class = "ROGUE" }
quests[9083] = { class = "ROGUE" }
quests[9084] = { class = "ROGUE" }
quests[9086] = { class = "DRUID" }
quests[9087] = { class = "DRUID" }
quests[9088] = { class = "DRUID" }
quests[9089] = { class = "DRUID" }
quests[9090] = { class = "DRUID" }
quests[9091] = { class = "DRUID" }
quests[9092] = { class = "DRUID" }
quests[9093] = { class = "DRUID" }
quests[9095] = { class = "MAGE" }
quests[9096] = { class = "MAGE" }
quests[9097] = { class = "MAGE" }
quests[9098] = { class = "MAGE" }
quests[9099] = { class = "MAGE" }
quests[9100] = { class = "MAGE" }
quests[9101] = { class = "MAGE" }
quests[9102] = { class = "MAGE" }
quests[9103] = { class = "WARLOCK" }
quests[9104] = { class = "WARLOCK" }
quests[9105] = { class = "WARLOCK" }
quests[9106] = { class = "WARLOCK" }
quests[9107] = { class = "WARLOCK" }
quests[9108] = { class = "WARLOCK" }
quests[9109] = { class = "WARLOCK" }
quests[9110] = { class = "WARLOCK" }
quests[9111] = { class = "PRIEST" }
quests[9112] = { class = "PRIEST" }
quests[9113] = { class = "PRIEST" }
quests[9114] = { class = "PRIEST" }
quests[9115] = { class = "PRIEST" }
quests[9116] = { class = "PRIEST" }
quests[9117] = { class = "PRIEST" }
quests[9118] = { class = "PRIEST" }
quests[9257] = { class = "PRIEST" }
quests[9269] = { class = "DRUID" }
quests[9270] = { class = "MAGE" }
quests[9271] = { class = "WARLOCK" }
quests[9362] = { class = "MAGE" }
quests[9364] = { class = "MAGE", spell = "Polymorph: Pig" }
chains[5] = 5
chains[6] = 18
ends[6] = true
chains[8] = 8
chains[10] = 992
ends[10] = true
chains[11] = 62
ends[11] = true
chains[12] = 12
chains[13] = 12
chains[14] = 12
ends[14] = true
chains[15] = 15
chains[18] = 18
chains[21] = 15
ends[21] = true
chains[26] = 26
chains[27] = 27
chains[28] = 26
chains[29] = 27
chains[30] = 26
ends[30] = true
chains[31] = 26
ends[31] = true
chains[33] = 5261
chains[35] = 40
chains[36] = 36
chains[37] = 40
chains[38] = 36
ends[38] = true
chains[39] = 40
chains[40] = 40
chains[45] = 40
chains[48] = 48
chains[49] = 48
chains[50] = 48
chains[51] = 48
chains[53] = 48
ends[53] = true
chains[54] = 15
ends[54] = true
chains[55] = 322
ends[55] = true
chains[56] = 56
chains[57] = 56
chains[58] = 56
ends[58] = true
chains[59] = 40
ends[59] = true
chains[60] = 60
ends[60] = true
chains[61] = 60
ends[61] = true
chains[62] = 62
chains[63] = 1530
ends[63] = true
chains[65] = 65
chains[66] = 66
chains[67] = 66
chains[68] = 66
chains[69] = 66
chains[70] = 66
chains[71] = 40
chains[72] = 66
chains[74] = 66
chains[75] = 66
chains[76] = 62
chains[77] = 649
ends[77] = true
chains[78] = 66
chains[79] = 66
chains[80] = 66
chains[81] = 649
ends[81] = true
chains[82] = 992
chains[84] = 85
chains[85] = 85
chains[86] = 85
chains[87] = 85
ends[87] = true
chains[89] = 125
ends[89] = true
chains[93] = 5
ends[93] = true
chains[94] = 94
chains[95] = 95
chains[97] = 66
chains[98] = 66
ends[98] = true
chains[99] = 421
ends[99] = true
chains[100] = 1530
ends[100] = true
chains[106] = 106
chains[107] = 106
chains[110] = 992
chains[111] = 106
chains[112] = 106
ends[112] = true
chains[113] = 992
ends[113] = true
chains[114] = 106
ends[114] = true
chains[118] = 118
chains[119] = 118
ends[119] = true
chains[120] = 120
chains[121] = 120
chains[123] = 123
chains[124] = 124
chains[125] = 125
chains[126] = 124
ends[126] = true
chains[129] = 129
chains[130] = 129
chains[131] = 129
ends[131] = true
chains[132] = 65
chains[133] = 148
chains[134] = 148
chains[135] = 65
chains[136] = 136
chains[138] = 136
chains[139] = 136
chains[140] = 136
ends[140] = true
chains[141] = 65
chains[142] = 65
chains[143] = 120
chains[144] = 120
chains[145] = 120
chains[146] = 120
ends[146] = true
chains[147] = 123
ends[147] = true
chains[148] = 148
chains[149] = 148
chains[154] = 148
chains[155] = 65
ends[155] = true
chains[156] = 148
chains[157] = 148
chains[158] = 148
chains[159] = 148
chains[160] = 148
chains[161] = 250
chains[173] = 173
chains[174] = 174
chains[175] = 174
chains[177] = 174
chains[181] = 174
ends[181] = true
chains[182] = 182
chains[185] = 185
chains[186] = 185
chains[187] = 185
chains[188] = 185
ends[188] = true
chains[189] = 189
chains[190] = 190
chains[191] = 190
chains[192] = 190
chains[193] = 190
ends[193] = true
chains[194] = 194
chains[195] = 194
chains[196] = 194
chains[197] = 194
ends[197] = true
chains[199] = 250
chains[200] = 215
chains[202] = 574
ends[202] = true
chains[205] = 207
ends[205] = true
chains[207] = 207
chains[209] = 189
ends[209] = true
chains[210] = 210
chains[215] = 215
chains[216] = 216
chains[217] = 224
ends[217] = true
chains[218] = 182
chains[220] = 1530
chains[221] = 173
chains[222] = 173
ends[222] = true
chains[223] = 173
ends[223] = true
chains[224] = 224
chains[225] = 225
chains[227] = 225
chains[228] = 225
ends[228] = true
chains[229] = 225
chains[230] = 95
chains[231] = 225
ends[231] = true
chains[232] = 232
chains[233] = 233
chains[234] = 233
ends[234] = true
chains[237] = 224
chains[238] = 232
chains[239] = 62
chains[240] = 5
ends[240] = true
chains[243] = 232
chains[244] = 244
chains[246] = 244
ends[246] = true
chains[248] = 94
chains[249] = 94
ends[249] = true
chains[250] = 250
chains[251] = 148
chains[252] = 148
chains[253] = 148
ends[253] = true
chains[254] = 148
ends[254] = true
chains[257] = 257
chains[258] = 257
chains[261] = 6141
chains[262] = 95
chains[263] = 224
chains[265] = 95
chains[266] = 95
chains[268] = 95
chains[269] = 95
chains[270] = 95
chains[271] = 257
ends[271] = true
chains[272] = 27
ends[272] = true
chains[273] = 298
chains[274] = 250
chains[275] = 463
ends[275] = true
chains[276] = 463
chains[277] = 463
chains[278] = 250
ends[278] = true
chains[279] = 279
ends[279] = true
chains[280] = 250
chains[281] = 279
chains[282] = 182
chains[283] = 250
ends[283] = true
chains[284] = 279
chains[285] = 279
chains[286] = 279
ends[286] = true
chains[287] = 182
ends[287] = true
chains[288] = 288
chains[289] = 288
chains[290] = 288
ends[290] = true
chains[291] = 182
ends[291] = true
chains[292] = 288
chains[293] = 288
ends[293] = true
chains[294] = 294
chains[295] = 294
chains[296] = 294
ends[296] = true
chains[297] = 436
ends[297] = true
chains[298] = 298
chains[301] = 298
chains[302] = 298
chains[303] = 303
chains[305] = 305
chains[306] = 305
ends[306] = true
chains[309] = 298
ends[309] = true
chains[317] = 317
chains[318] = 317
chains[319] = 317
ends[319] = true
chains[320] = 317
ends[320] = true
chains[321] = 95
chains[322] = 322
chains[323] = 95
chains[324] = 95
ends[324] = true
chains[325] = 322
chains[328] = 215
chains[329] = 215
chains[330] = 215
chains[331] = 215
ends[331] = true
chains[335] = 335
ends[335] = true
chains[336] = 335
chains[337] = 337
chains[343] = 343
chains[344] = 343
chains[345] = 343
chains[346] = 343
ends[346] = true
chains[347] = 343
ends[347] = true
chains[348] = 348
chains[349] = 348
ends[349] = true
chains[350] = 373
chains[351] = 351
chains[353] = 1097
ends[353] = true
chains[354] = 354
chains[355] = 354
chains[357] = 405
chains[359] = 359
chains[360] = 359
ends[360] = true
chains[363] = 363
chains[364] = 363
ends[364] = true
chains[365] = 365
ends[365] = true
chains[366] = 405
chains[367] = 367
chains[368] = 367
chains[369] = 367
ends[369] = true
chains[370] = 370
chains[371] = 370
chains[372] = 370
ends[372] = true
chains[373] = 373
chains[378] = 303
ends[378] = true
chains[379] = 232
ends[379] = true
chains[380] = 380
chains[381] = 380
chains[382] = 380
chains[383] = 380
chains[389] = 373
chains[391] = 373
chains[392] = 373
chains[393] = 373
chains[394] = 373
chains[395] = 373
chains[396] = 373
ends[396] = true
chains[397] = 335
ends[397] = true
chains[401] = 148
chains[404] = 404
chains[405] = 405
chains[407] = 365
ends[407] = true
chains[408] = 354
ends[408] = true
chains[409] = 405
ends[409] = true
chains[413] = 413
chains[414] = 413
ends[414] = true
chains[417] = 419
ends[417] = true
chains[419] = 419
chains[420] = 182
chains[421] = 421
chains[422] = 421
chains[423] = 421
chains[424] = 421
chains[425] = 428
ends[425] = true
chains[426] = 404
ends[426] = true
chains[427] = 380
ends[427] = true
chains[428] = 428
chains[429] = 428
chains[430] = 428
chains[434] = 373
ends[434] = true
chains[435] = 435
ends[435] = true
chains[436] = 436
chains[437] = 437
ends[437] = true
chains[438] = 437
ends[438] = true
chains[440] = 440
chains[441] = 440
chains[442] = 443
ends[442] = true
chains[443] = 443
chains[444] = 443
chains[446] = 443
chains[447] = 447
chains[448] = 443
chains[449] = 435
chains[450] = 447
chains[451] = 447
ends[451] = true
chains[453] = 95
chains[454] = 298
chains[455] = 468
ends[455] = true
chains[458] = 458
chains[459] = 458
ends[459] = true
chains[460] = 460
chains[461] = 460
chains[463] = 463
chains[464] = 473
chains[465] = 473
chains[466] = 467
ends[466] = true
chains[467] = 467
chains[468] = 468
chains[471] = 484
ends[471] = true
chains[473] = 473
chains[474] = 473
ends[474] = true
chains[475] = 475
chains[476] = 475
chains[477] = 477
chains[478] = 477
chains[479] = 477
chains[480] = 477
ends[480] = true
chains[481] = 477
chains[482] = 477
chains[483] = 475
chains[484] = 484
chains[485] = 485
chains[486] = 475
ends[486] = true
chains[488] = 488
chains[489] = 488
ends[489] = true
chains[491] = 460
ends[491] = true
chains[492] = 367
ends[492] = true
chains[495] = 495
chains[496] = 496
ends[496] = true
chains[498] = 498
chains[499] = 496
ends[499] = true
chains[500] = 500
chains[501] = 501
ends[501] = true
chains[502] = 501
ends[502] = true
chains[503] = 498
chains[504] = 500
ends[504] = true
chains[506] = 498
chains[507] = 498
ends[507] = true
chains[508] = 498
ends[508] = true
chains[509] = 509
chains[510] = 510
chains[511] = 511
chains[512] = 510
ends[512] = true
chains[513] = 509
chains[514] = 511
chains[515] = 509
chains[517] = 509
ends[517] = true
chains[518] = 495
chains[519] = 495
chains[520] = 495
ends[520] = true
chains[521] = 495
ends[521] = true
chains[522] = 522
chains[523] = 522
ends[523] = true
chains[524] = 509
ends[524] = true
chains[525] = 511
chains[528] = 528
chains[529] = 528
chains[530] = 440
ends[530] = true
chains[531] = 257
ends[531] = true
chains[532] = 528
chains[533] = 498
chains[536] = 536
chains[537] = 511
ends[537] = true
chains[538] = 337
chains[539] = 528
chains[540] = 337
ends[540] = true
chains[541] = 528
ends[541] = true
chains[542] = 337
ends[542] = true
chains[544] = 544
chains[545] = 544
ends[545] = true
chains[550] = 528
ends[550] = true
chains[551] = 551
chains[552] = 552
chains[553] = 552
ends[553] = true
chains[554] = 551
ends[554] = true
chains[556] = 556
chains[557] = 556
ends[557] = true
chains[559] = 536
chains[560] = 536
chains[561] = 536
chains[562] = 536
ends[562] = true
chains[563] = 536
ends[563] = true
chains[568] = 568
chains[569] = 568
ends[569] = true
chains[570] = 570
chains[571] = 570
chains[572] = 570
chains[573] = 570
ends[573] = true
chains[574] = 574
chains[575] = 575
chains[577] = 575
chains[578] = 616
chains[581] = 581
chains[582] = 581
chains[584] = 581
ends[584] = true
chains[588] = 588
chains[589] = 588
chains[590] = 8
ends[590] = true
chains[591] = 588
chains[592] = 588
chains[593] = 588
ends[593] = true
chains[594] = 594
chains[596] = 596
chains[597] = 597
chains[598] = 596
ends[598] = true
chains[599] = 597
chains[600] = 605
ends[600] = true
chains[601] = 616
chains[602] = 616
chains[603] = 616
chains[604] = 597
chains[605] = 605
chains[606] = 606
chains[607] = 606
chains[608] = 597
ends[608] = true
chains[609] = 606
chains[610] = 616
chains[611] = 616
ends[611] = true
chains[613] = 606
ends[613] = true
chains[616] = 616
chains[617] = 617
ends[617] = true
chains[622] = 210
ends[622] = true
chains[623] = 617
ends[623] = true
chains[624] = 624
chains[625] = 624
chains[626] = 624
ends[626] = true
chains[627] = 210
ends[627] = true
chains[628] = 575
ends[628] = true
chains[630] = 594
ends[630] = true
chains[631] = 631
chains[632] = 631
chains[633] = 631
ends[633] = true
chains[634] = 631
ends[634] = true
chains[637] = 637
chains[638] = 638
chains[639] = 638
chains[640] = 638
chains[641] = 638
chains[642] = 642
chains[643] = 638
chains[644] = 638
ends[644] = true
chains[645] = 638
chains[646] = 638
ends[646] = true
chains[648] = 351
ends[648] = true
chains[649] = 649
chains[650] = 649
chains[651] = 642
chains[652] = 642
ends[652] = true
chains[654] = 654
ends[654] = true
chains[655] = 655
chains[656] = 687
ends[656] = true
chains[657] = 659
chains[658] = 659
chains[659] = 659
chains[660] = 659
ends[660] = true
chains[661] = 659
ends[661] = true
chains[662] = 663
ends[662] = true
chains[663] = 663
chains[665] = 665
chains[666] = 665
chains[667] = 665
ends[667] = true
chains[668] = 665
chains[669] = 665
chains[670] = 665
chains[671] = 671
chains[672] = 655
chains[673] = 671
ends[673] = true
chains[674] = 655
chains[675] = 655
chains[676] = 676
chains[677] = 676
chains[678] = 676
ends[678] = true
chains[681] = 681
chains[682] = 681
ends[682] = true
chains[683] = 637
chains[686] = 637
chains[687] = 687
chains[689] = 637
ends[689] = true
chains[691] = 691
chains[692] = 687
chains[693] = 691
chains[694] = 691
chains[695] = 691
chains[696] = 691
ends[696] = true
chains[697] = 691
ends[697] = true
chains[698] = 698
chains[699] = 698
chains[700] = 637
ends[700] = true
chains[701] = 655
ends[701] = true
chains[702] = 655
chains[704] = 707
ends[704] = true
chains[705] = 705
ends[705] = true
chains[707] = 707
chains[710] = 710
chains[711] = 710
chains[712] = 710
chains[713] = 713
chains[714] = 713
chains[715] = 713
ends[715] = true
chains[716] = 710
ends[716] = true
chains[717] = 732
chains[720] = 720
chains[721] = 720
chains[722] = 720
chains[723] = 720
chains[724] = 720
chains[725] = 720
chains[726] = 720
chains[727] = 727
chains[728] = 728
chains[729] = 730
chains[730] = 730
chains[731] = 730
chains[732] = 732
chains[734] = 734
chains[735] = 727
ends[735] = true
chains[736] = 728
ends[736] = true
chains[738] = 707
chains[739] = 707
chains[741] = 730
chains[748] = 748
chains[749] = 749
chains[750] = 750
chains[751] = 749
ends[751] = true
chains[752] = 752
chains[753] = 752
chains[754] = 748
chains[755] = 752
chains[756] = 748
chains[757] = 752
chains[758] = 748
chains[759] = 748
chains[760] = 748
ends[760] = true
chains[762] = 720
chains[763] = 752
chains[767] = 752
chains[768] = 768
chains[769] = 768
ends[769] = true
chains[771] = 752
chains[772] = 752
chains[773] = 752
chains[775] = 752
chains[776] = 752
ends[776] = true
chains[777] = 734
chains[778] = 734
ends[778] = true
chains[779] = 732
ends[779] = true
chains[780] = 750
ends[780] = true
chains[782] = 782
chains[784] = 784
chains[790] = 790
ends[790] = true
chains[793] = 782
chains[794] = 794
ends[794] = true
chains[795] = 782
ends[795] = true
chains[804] = 790
ends[804] = true
chains[805] = 794
ends[805] = true
chains[806] = 823
chains[809] = 823
chains[812] = 812
chains[813] = 812
ends[813] = true
chains[819] = 819
chains[821] = 819
chains[822] = 819
ends[822] = true
chains[823] = 823
chains[824] = 1918
ends[824] = true
chains[825] = 784
ends[825] = true
chains[827] = 823
chains[828] = 823
chains[829] = 823
chains[830] = 830
chains[831] = 830
ends[831] = true
chains[834] = 834
chains[835] = 834
ends[835] = true
chains[836] = 485
ends[836] = true
chains[838] = 838
chains[840] = 840
chains[842] = 840
ends[842] = true
chains[843] = 843
chains[844] = 861
chains[845] = 861
chains[846] = 843
chains[847] = 655
ends[847] = true
chains[848] = 848
ends[848] = true
chains[849] = 843
ends[849] = true
chains[850] = 850
chains[851] = 850
chains[852] = 850
chains[853] = 848
ends[853] = true
chains[858] = 858
chains[860] = 861
chains[861] = 861
chains[863] = 858
ends[863] = true
chains[864] = 654
ends[864] = true
chains[865] = 865
chains[867] = 867
chains[869] = 869
chains[870] = 886
chains[873] = 861
ends[873] = true
chains[874] = 861
chains[875] = 867
chains[876] = 867
ends[876] = true
chains[877] = 886
chains[878] = 878
chains[879] = 879
ends[879] = true
chains[880] = 886
ends[880] = true
chains[881] = 861
chains[882] = 861
chains[886] = 886
chains[887] = 887
chains[888] = 887
ends[888] = true
chains[890] = 887
chains[892] = 887
chains[893] = 893
chains[894] = 894
chains[900] = 894
chains[901] = 894
chains[902] = 894
chains[903] = 861
chains[905] = 861
chains[906] = 879
ends[906] = true
chains[907] = 861
chains[913] = 861
chains[914] = 1489
ends[914] = true
chains[916] = 916
chains[917] = 916
chains[918] = 997
chains[920] = 916
chains[921] = 916
chains[922] = 997
chains[923] = 997
chains[924] = 823
ends[924] = true
chains[926] = 823
ends[926] = true
chains[927] = 927
chains[928] = 916
chains[929] = 916
chains[931] = 931
chains[933] = 916
ends[933] = true
chains[937] = 937
ends[937] = true
chains[939] = 939
chains[940] = 937
chains[941] = 927
ends[941] = true
chains[942] = 730
chains[943] = 730
ends[943] = true
chains[944] = 947
ends[944] = true
chains[947] = 947
chains[948] = 947
chains[950] = 950
chains[951] = 950
ends[951] = true
chains[952] = 937
ends[952] = true
chains[954] = 954
chains[955] = 954
chains[956] = 954
chains[957] = 954
ends[957] = true
chains[964] = 838
chains[965] = 965
chains[966] = 965
chains[967] = 965
chains[969] = 6606
chains[970] = 965
chains[972] = 1103
ends[972] = true
chains[973] = 965
ends[973] = true
chains[974] = 974
chains[975] = 6606
ends[975] = true
chains[977] = 3783
chains[978] = 3661
chains[979] = 3661
chains[980] = 974
chains[981] = 1140
ends[981] = true
chains[983] = 983
chains[985] = 985
chains[986] = 985
ends[986] = true
chains[991] = 991
chains[992] = 992
chains[993] = 985
ends[993] = true
chains[997] = 997
chains[1001] = 983
chains[1002] = 983
chains[1003] = 983
ends[1003] = true
chains[1007] = 1007
chains[1008] = 1008
chains[1009] = 1007
ends[1009] = true
chains[1010] = 1010
chains[1011] = 1011
chains[1012] = 1011
ends[1012] = true
chains[1016] = 1016
chains[1017] = 1016
ends[1017] = true
chains[1020] = 1010
chains[1021] = 1021
chains[1022] = 1022
chains[1023] = 991
ends[1023] = true
chains[1024] = 1024
chains[1026] = 1024
chains[1027] = 1024
chains[1028] = 1024
chains[1029] = 1024
chains[1030] = 1024
chains[1031] = 1021
chains[1032] = 1021
ends[1032] = true
chains[1033] = 1010
chains[1034] = 1010
chains[1035] = 1010
ends[1035] = true
chains[1036] = 1036
chains[1037] = 1022
chains[1038] = 1022
chains[1039] = 1022
chains[1040] = 1022
chains[1041] = 1022
chains[1042] = 1022
chains[1043] = 1022
ends[1043] = true
chains[1044] = 1022
ends[1044] = true
chains[1045] = 1024
chains[1046] = 1024
ends[1046] = true
chains[1052] = 6141
chains[1053] = 6141
ends[1053] = true
chains[1055] = 1024
chains[1056] = 1056
chains[1057] = 1056
ends[1057] = true
chains[1059] = 1056
ends[1059] = true
chains[1060] = 867
ends[1060] = true
chains[1063] = 1063
chains[1064] = 1063
chains[1065] = 1063
chains[1066] = 1063
chains[1067] = 1063
chains[1070] = 1070
chains[1071] = 1070
ends[1071] = true
chains[1072] = 1072
chains[1073] = 1072
chains[1074] = 1072
chains[1075] = 1075
chains[1076] = 1075
chains[1077] = 1075
chains[1079] = 1072
ends[1079] = true
chains[1080] = 1075
ends[1080] = true
chains[1081] = 1082
ends[1081] = true
chains[1082] = 1082
chains[1085] = 1070
chains[1086] = 1063
ends[1086] = true
chains[1087] = 1087
chains[1088] = 1087
chains[1089] = 1087
ends[1089] = true
chains[1090] = 1090
ends[1090] = true
chains[1092] = 1090
ends[1092] = true
chains[1093] = 1483
chains[1094] = 1483
chains[1095] = 1483
chains[1096] = 1483
ends[1096] = true
chains[1097] = 1097
chains[1100] = 1100
chains[1101] = 1100
ends[1101] = true
chains[1103] = 1103
ends[1103] = true
chains[1105] = 1105
chains[1106] = 1106
chains[1107] = 1105
ends[1107] = true
chains[1108] = 1106
chains[1109] = 1109
chains[1111] = 1111
chains[1112] = 1111
chains[1113] = 1109
ends[1113] = true
chains[1114] = 1111
chains[1115] = 1111
chains[1116] = 1111
ends[1116] = true
chains[1117] = 1111
chains[1118] = 1111
ends[1118] = true
chains[1122] = 1122
chains[1124] = 1124
chains[1125] = 1124
chains[1126] = 1124
ends[1126] = true
chains[1127] = 1122
ends[1127] = true
chains[1130] = 1130
chains[1131] = 1130
chains[1132] = 1132
chains[1133] = 1132
ends[1133] = true
chains[1134] = 1008
ends[1134] = true
chains[1136] = 1130
ends[1136] = true
chains[1137] = 1106
chains[1139] = 720
ends[1139] = true
chains[1140] = 1140
chains[1143] = 1140
ends[1143] = true
chains[1145] = 1145
chains[1146] = 1145
chains[1147] = 1145
ends[1147] = true
chains[1148] = 1148
ends[1148] = true
chains[1149] = 1149
chains[1150] = 1149
chains[1151] = 1149
chains[1152] = 1149
chains[1153] = 893
ends[1153] = true
chains[1154] = 1149
chains[1159] = 1149
chains[1160] = 1149
chains[1167] = 1140
chains[1169] = 1169
chains[1170] = 1169
chains[1171] = 1169
chains[1172] = 1169
chains[1173] = 1169
ends[1173] = true
chains[1176] = 1176
chains[1178] = 1176
chains[1180] = 1176
chains[1181] = 1176
chains[1182] = 1176
chains[1183] = 1176
chains[1184] = 1148
ends[1184] = true
chains[1185] = 1124
ends[1185] = true
chains[1186] = 1176
chains[1187] = 1176
ends[1187] = true
chains[1188] = 1176
chains[1189] = 1176
ends[1189] = true
chains[1190] = 1106
chains[1192] = 1106
ends[1192] = true
chains[1194] = 1106
chains[1195] = 1195
chains[1196] = 1195
chains[1197] = 1195
ends[1197] = true
chains[1198] = 1198
chains[1200] = 1198
ends[1200] = true
chains[1201] = 1201
chains[1202] = 1201
ends[1202] = true
chains[1203] = 1218
ends[1203] = true
chains[1204] = 1260
chains[1206] = 1218
chains[1218] = 1218
chains[1219] = 1219
chains[1220] = 1219
ends[1220] = true
chains[1238] = 1238
chains[1239] = 1238
chains[1240] = 1238
chains[1241] = 1274
chains[1242] = 1274
chains[1243] = 1274
chains[1244] = 1274
chains[1245] = 1274
chains[1246] = 1274
chains[1247] = 1274
chains[1248] = 1274
chains[1249] = 1274
chains[1250] = 1274
chains[1251] = 1251
chains[1252] = 1252
chains[1253] = 1253
chains[1258] = 1260
ends[1258] = true
chains[1259] = 1252
chains[1260] = 1260
chains[1261] = 1238
ends[1261] = true
chains[1262] = 1238
chains[1264] = 1274
chains[1265] = 1274
chains[1266] = 1274
chains[1267] = 1274
ends[1267] = true
chains[1269] = 1269
chains[1273] = 1269
ends[1273] = true
chains[1274] = 1274
chains[1275] = 3765
ends[1275] = true
chains[1276] = 1251
ends[1276] = true
chains[1285] = 1252
chains[1286] = 1252
chains[1287] = 1252
ends[1287] = true
chains[1301] = 1301
chains[1302] = 1301
ends[1302] = true
chains[1319] = 1253
chains[1320] = 1253
ends[1320] = true
chains[1321] = 1251
chains[1322] = 1251
ends[1322] = true
chains[1323] = 1251
chains[1324] = 1274
ends[1324] = true
chains[1338] = 1339
ends[1338] = true
chains[1339] = 1339
chains[1358] = 435
ends[1358] = true
chains[1359] = 435
chains[1361] = 1361
chains[1362] = 1361
ends[1362] = true
chains[1363] = 1363
chains[1364] = 1363
ends[1364] = true
chains[1365] = 1365
chains[1366] = 1365
ends[1366] = true
chains[1369] = 1369
chains[1370] = 1370
chains[1371] = 1369
chains[1372] = 1372
chains[1373] = 1370
chains[1374] = 1370
chains[1375] = 1369
chains[1380] = 1370
ends[1380] = true
chains[1381] = 1369
ends[1381] = true
chains[1382] = 1382
chains[1383] = 1372
ends[1383] = true
chains[1384] = 1382
ends[1384] = true
chains[1385] = 1385
chains[1386] = 1385
ends[1386] = true
chains[1388] = 1372
chains[1391] = 1372
ends[1391] = true
chains[1394] = 1149
ends[1394] = true
chains[1395] = 1477
ends[1395] = true
chains[1396] = 1396
chains[1398] = 1396
ends[1398] = true
chains[1418] = 1418
chains[1420] = 1418
ends[1420] = true
chains[1421] = 1396
chains[1422] = 698
chains[1424] = 1424
chains[1425] = 1396
ends[1425] = true
chains[1426] = 698
chains[1427] = 698
chains[1428] = 698
ends[1428] = true
chains[1429] = 1424
chains[1431] = 1431
chains[1432] = 1431
chains[1433] = 1431
chains[1435] = 1431
ends[1435] = true
chains[1436] = 1431
ends[1436] = true
chains[1437] = 1437
chains[1438] = 1437
chains[1439] = 1437
chains[1440] = 1437
ends[1440] = true
chains[1444] = 1424
chains[1445] = 1424
ends[1445] = true
chains[1447] = 1274
chains[1448] = 1448
chains[1449] = 1448
chains[1450] = 1448
chains[1451] = 1448
chains[1452] = 1448
chains[1454] = 1454
chains[1455] = 1454
chains[1456] = 1454
ends[1456] = true
chains[1457] = 1454
ends[1457] = true
chains[1458] = 1458
chains[1459] = 1458
chains[1465] = 1437
chains[1466] = 1458
ends[1466] = true
chains[1467] = 1458
ends[1467] = true
chains[1469] = 1448
chains[1471] = 1478
ends[1471] = true
chains[1472] = 1472
chains[1473] = 1478
chains[1474] = 1472
ends[1474] = true
chains[1475] = 1448
ends[1475] = true
chains[1476] = 1472
chains[1477] = 1477
chains[1478] = 1478
chains[1480] = 1480
chains[1481] = 1480
chains[1482] = 1480
chains[1483] = 1483
chains[1484] = 1480
chains[1485] = 1485
ends[1485] = true
chains[1488] = 1480
ends[1488] = true
chains[1489] = 1489
chains[1490] = 1489
chains[1491] = 865
ends[1491] = true
chains[1498] = 1505
chains[1499] = 1485
ends[1499] = true
chains[1501] = 1506
chains[1502] = 1505
chains[1503] = 1505
ends[1503] = true
chains[1504] = 1506
ends[1504] = true
chains[1505] = 1505
chains[1506] = 1506
chains[1507] = 1507
chains[1508] = 1507
chains[1509] = 1507
chains[1510] = 1507
chains[1511] = 1507
chains[1512] = 1507
chains[1513] = 1507
ends[1513] = true
chains[1515] = 1507
chains[1516] = 1516
ends[1516] = true
chains[1517] = 1516
ends[1517] = true
chains[1519] = 1519
ends[1519] = true
chains[1520] = 1519
ends[1520] = true
chains[1524] = 1524
chains[1525] = 1524
chains[1526] = 1524
ends[1526] = true
chains[1530] = 1530
chains[1534] = 1530
chains[1535] = 1530
chains[1536] = 1530
chains[1559] = 705
ends[1559] = true
chains[1579] = 1579
chains[1580] = 1579
ends[1580] = true
chains[1638] = 1638
chains[1639] = 1638
chains[1640] = 1638
chains[1642] = 1642
chains[1643] = 1642
chains[1644] = 1642
chains[1646] = 1646
chains[1647] = 1646
chains[1648] = 1646
chains[1649] = 1649
chains[1650] = 1649
chains[1651] = 1649
ends[1651] = true
chains[1652] = 1649
chains[1653] = 1649
ends[1653] = true
chains[1654] = 1654
ends[1654] = true
chains[1665] = 1638
chains[1666] = 1638
chains[1667] = 1638
ends[1667] = true
chains[1678] = 1679
chains[1679] = 1679
chains[1680] = 1679
chains[1681] = 1679
ends[1681] = true
chains[1682] = 1679
ends[1682] = true
chains[1683] = 1684
chains[1684] = 1684
chains[1685] = 1685
chains[1686] = 1684
ends[1686] = true
chains[1688] = 1685
chains[1689] = 1685
ends[1689] = true
chains[1690] = 1690
chains[1691] = 1690
ends[1691] = true
chains[1692] = 1684
chains[1693] = 1684
ends[1693] = true
chains[1698] = 1698
chains[1699] = 1698
chains[1700] = 1700
chains[1701] = 1698
ends[1701] = true
chains[1702] = 1698
chains[1703] = 1703
chains[1704] = 1704
chains[1705] = 1700
ends[1705] = true
chains[1706] = 1700
ends[1706] = true
chains[1707] = 1707
chains[1708] = 1704
ends[1708] = true
chains[1709] = 1704
ends[1709] = true
chains[1710] = 1703
ends[1710] = true
chains[1711] = 1703
ends[1711] = true
chains[1712] = 1718
ends[1712] = true
chains[1713] = 1713
ends[1713] = true
chains[1716] = 1717
chains[1717] = 1717
chains[1718] = 1718
chains[1719] = 1718
chains[1738] = 1717
chains[1739] = 1717
ends[1739] = true
chains[1758] = 1798
chains[1778] = 1646
chains[1779] = 1646
chains[1780] = 1642
chains[1781] = 1642
chains[1783] = 1646
chains[1784] = 1646
ends[1784] = true
chains[1785] = 1646
ends[1785] = true
chains[1786] = 1642
chains[1787] = 1642
ends[1787] = true
chains[1788] = 1642
ends[1788] = true
chains[1791] = 1718
chains[1792] = 1713
ends[1792] = true
chains[1796] = 1796
chains[1798] = 1798
chains[1801] = 1801
chains[1802] = 1798
chains[1803] = 1801
chains[1804] = 1798
ends[1804] = true
chains[1805] = 1801
ends[1805] = true
chains[1806] = 1654
ends[1806] = true
chains[1818] = 1818
chains[1819] = 1818
chains[1820] = 1818
chains[1821] = 1818
ends[1821] = true
chains[1822] = 1818
ends[1822] = true
chains[1823] = 1823
chains[1824] = 1823
chains[1825] = 1823
chains[1838] = 1823
ends[1838] = true
chains[1839] = 1839
chains[1840] = 1840
chains[1841] = 1841
chains[1842] = 1839
ends[1842] = true
chains[1843] = 1839
ends[1843] = true
chains[1844] = 1840
ends[1844] = true
chains[1845] = 1840
ends[1845] = true
chains[1846] = 1841
ends[1846] = true
chains[1847] = 1841
ends[1847] = true
chains[1858] = 1859
ends[1858] = true
chains[1859] = 1859
chains[1860] = 1860
chains[1861] = 1860
ends[1861] = true
chains[1878] = 1707
ends[1878] = true
chains[1879] = 1879
chains[1880] = 1879
ends[1880] = true
chains[1881] = 1881
chains[1882] = 1881
ends[1882] = true
chains[1883] = 1883
chains[1884] = 1883
ends[1884] = true
chains[1885] = 1885
chains[1886] = 1885
chains[1898] = 1885
chains[1899] = 1885
ends[1899] = true
chains[1918] = 1918
chains[1919] = 1919
chains[1920] = 1919
chains[1921] = 1919
ends[1921] = true
chains[1938] = 1939
chains[1939] = 1939
chains[1940] = 1939
ends[1940] = true
chains[1941] = 1919
ends[1941] = true
chains[1942] = 1939
ends[1942] = true
chains[1943] = 1943
chains[1944] = 1943
chains[1945] = 1943
ends[1945] = true
chains[1946] = 1943
ends[1946] = true
chains[1947] = 1947
chains[1949] = 1947
chains[1950] = 1947
chains[1951] = 1947
ends[1951] = true
chains[1952] = 1947
ends[1952] = true
chains[1953] = 1953
chains[1954] = 1953
chains[1955] = 1953
chains[1956] = 1953
chains[1957] = 1953
ends[1957] = true
chains[1958] = 1953
ends[1958] = true
chains[1959] = 1959
chains[1960] = 1959
chains[1961] = 1959
ends[1961] = true
chains[1962] = 1959
ends[1962] = true
chains[1963] = 1859
chains[1978] = 1885
ends[1978] = true
chains[1998] = 1998
chains[1999] = 1998
ends[1999] = true
chains[2038] = 2039
ends[2038] = true
chains[2039] = 2039
chains[2040] = 2041
ends[2040] = true
chains[2041] = 2041
chains[2078] = 2098
ends[2078] = true
chains[2098] = 2098
chains[2118] = 2118
chains[2138] = 2118
chains[2139] = 2118
ends[2139] = true
chains[2198] = 2198
chains[2199] = 2198
chains[2200] = 2198
chains[2201] = 2198
chains[2202] = 2258
chains[2203] = 2258
ends[2203] = true
chains[2204] = 2198
ends[2204] = true
chains[2218] = 2218
chains[2238] = 2218
chains[2239] = 2218
ends[2239] = true
chains[2240] = 2398
ends[2240] = true
chains[2258] = 2258
chains[2259] = 2259
chains[2260] = 2259
ends[2260] = true
chains[2279] = 2279
chains[2280] = 2280
chains[2281] = 2300
chains[2282] = 2300
ends[2282] = true
chains[2283] = 2283
chains[2284] = 2283
chains[2298] = 2299
ends[2298] = true
chains[2299] = 2299
chains[2300] = 2300
chains[2318] = 2283
chains[2338] = 2283
chains[2339] = 2283
ends[2339] = true
chains[2340] = 2283
chains[2341] = 2283
ends[2341] = true
chains[2359] = 2360
chains[2360] = 2360
chains[2361] = 2198
ends[2361] = true
chains[2379] = 2379
chains[2381] = 2379
ends[2381] = true
chains[2382] = 2379
chains[2398] = 2398
chains[2399] = 931
ends[2399] = true
chains[2438] = 2438
chains[2439] = 2279
chains[2440] = 2280
chains[2458] = 2460
chains[2459] = 2438
ends[2459] = true
chains[2460] = 2460
chains[2478] = 2460
chains[2479] = 2460
chains[2480] = 2460
ends[2480] = true
chains[2498] = 997
chains[2499] = 997
ends[2499] = true
chains[2518] = 2519
chains[2519] = 2519
chains[2520] = 2519
ends[2520] = true
chains[2521] = 2521
chains[2522] = 2521
ends[2522] = true
chains[2541] = 2541
chains[2561] = 2541
ends[2561] = true
chains[2581] = 2581
chains[2582] = 2581
ends[2582] = true
chains[2583] = 2583
chains[2584] = 2583
ends[2584] = true
chains[2585] = 2585
chains[2586] = 2585
ends[2586] = true
chains[2601] = 2601
chains[2602] = 2601
ends[2602] = true
chains[2603] = 2603
chains[2604] = 2603
ends[2604] = true
chains[2605] = 2605
chains[2606] = 2605
chains[2607] = 2360
chains[2608] = 2360
chains[2609] = 2360
ends[2609] = true
chains[2621] = 2784
chains[2622] = 2784
chains[2623] = 2784
ends[2623] = true
chains[2641] = 2605
ends[2641] = true
chains[2661] = 2605
chains[2662] = 2605
ends[2662] = true
chains[2681] = 2783
chains[2701] = 2783
chains[2702] = 2783
chains[2721] = 2783
chains[2742] = 2742
ends[2742] = true
chains[2743] = 2783
chains[2744] = 2783
chains[2745] = 373
chains[2746] = 373
chains[2751] = 2751
chains[2752] = 2751
chains[2753] = 2751
chains[2754] = 2751
chains[2755] = 2751
ends[2755] = true
chains[2756] = 2756
ends[2756] = true
chains[2757] = 2756
ends[2757] = true
chains[2758] = 2758
ends[2758] = true
chains[2759] = 2758
ends[2759] = true
chains[2765] = 3321
ends[2765] = true
chains[2766] = 2766
chains[2767] = 2766
ends[2767] = true
chains[2769] = 2769
chains[2770] = 2769
ends[2770] = true
chains[2782] = 2742
chains[2783] = 2783
chains[2784] = 2784
chains[2801] = 2783
chains[2821] = 2821
chains[2822] = 2822
chains[2841] = 2841
chains[2842] = 2841
chains[2843] = 2841
ends[2843] = true
chains[2844] = 2844
chains[2845] = 2844
ends[2845] = true
chains[2846] = 2861
ends[2846] = true
chains[2861] = 2861
chains[2862] = 2862
chains[2863] = 2862
ends[2863] = true
chains[2864] = 2864
chains[2865] = 2864
ends[2865] = true
chains[2866] = 2866
chains[2867] = 2866
chains[2869] = 2866
chains[2870] = 2866
ends[2870] = true
chains[2871] = 2866
ends[2871] = true
chains[2872] = 2872
chains[2873] = 2872
ends[2873] = true
chains[2874] = 2872
ends[2874] = true
chains[2879] = 2939
chains[2880] = 2880
chains[2881] = 2880
ends[2881] = true
chains[2902] = 2862
chains[2903] = 2862
ends[2903] = true
chains[2922] = 2923
ends[2922] = true
chains[2923] = 2923
chains[2924] = 2925
ends[2924] = true
chains[2925] = 2925
chains[2926] = 2927
chains[2927] = 2927
chains[2930] = 2931
ends[2930] = true
chains[2931] = 2931
chains[2933] = 2933
chains[2934] = 2933
chains[2935] = 2933
chains[2936] = 2933
chains[2937] = 2933
ends[2937] = true
chains[2938] = 2933
ends[2938] = true
chains[2939] = 2939
chains[2940] = 2939
chains[2941] = 2939
chains[2942] = 2939
ends[2942] = true
chains[2943] = 2939
chains[2944] = 2939
chains[2946] = 2279
ends[2946] = true
chains[2947] = 2947
chains[2948] = 2947
ends[2948] = true
chains[2949] = 2949
chains[2950] = 2949
ends[2950] = true
chains[2951] = 2951
chains[2952] = 2951
chains[2953] = 2951
ends[2953] = true
chains[2962] = 2927
ends[2962] = true
chains[2963] = 2279
chains[2964] = 2977
ends[2964] = true
chains[2965] = 2280
chains[2966] = 2280
ends[2966] = true
chains[2967] = 2967
chains[2968] = 2967
ends[2968] = true
chains[2969] = 2969
chains[2970] = 2969
chains[2972] = 2969
chains[2973] = 2973
chains[2974] = 2973
ends[2974] = true
chains[2975] = 2981
chains[2976] = 2973
ends[2976] = true
chains[2977] = 2977
chains[2978] = 2978
chains[2979] = 2978
ends[2979] = true
chains[2980] = 2981
ends[2980] = true
chains[2981] = 2981
chains[2988] = 2988
chains[2989] = 2988
chains[2990] = 2988
chains[2991] = 2988
chains[2992] = 2988
chains[2993] = 2988
chains[2994] = 2988
ends[2994] = true
chains[3002] = 2978
ends[3002] = true
chains[3121] = 3121
chains[3122] = 3121
chains[3123] = 3121
chains[3124] = 3121
chains[3125] = 3121
chains[3126] = 3121
chains[3127] = 3121
ends[3127] = true
chains[3130] = 2866
chains[3141] = 2783
chains[3181] = 3181
chains[3182] = 3181
chains[3201] = 3181
ends[3201] = true
chains[3221] = 435
chains[3261] = 861
chains[3281] = 869
ends[3281] = true
chains[3321] = 3321
chains[3364] = 3364
chains[3365] = 3364
ends[3365] = true
chains[3367] = 3367
chains[3368] = 3367
chains[3371] = 3367
chains[3372] = 3367
chains[3373] = 3373
chains[3374] = 3373
ends[3374] = true
chains[3377] = 3377
chains[3378] = 3377
ends[3378] = true
chains[3379] = 3379
chains[3385] = 3379
ends[3385] = true
chains[3402] = 3379
ends[3402] = true
chains[3441] = 3441
chains[3442] = 3441
chains[3443] = 3441
chains[3449] = 3449
ends[3449] = true
chains[3450] = 3450
chains[3451] = 3450
chains[3452] = 3441
chains[3453] = 3441
chains[3454] = 3441
chains[3461] = 3449
ends[3461] = true
chains[3462] = 3441
chains[3463] = 3441
chains[3481] = 3441
chains[3483] = 3450
ends[3483] = true
chains[3501] = 3501
chains[3502] = 3501
ends[3502] = true
chains[3504] = 3504
chains[3505] = 3504
chains[3506] = 3504
ends[3506] = true
chains[3507] = 3504
ends[3507] = true
chains[3508] = 2783
chains[3509] = 2783
chains[3510] = 2783
chains[3511] = 2783
chains[3512] = 3373
ends[3512] = true
chains[3513] = 3513
chains[3514] = 3513
ends[3514] = true
chains[3518] = 3518
chains[3519] = 4495
chains[3520] = 3520
chains[3521] = 4495
ends[3521] = true
chains[3522] = 4495
ends[3522] = true
chains[3523] = 3523
chains[3524] = 3524
chains[3525] = 3523
ends[3525] = true
chains[3527] = 3520
chains[3528] = 3520
chains[3541] = 3541
chains[3542] = 3542
chains[3561] = 3561
chains[3562] = 3518
ends[3562] = true
chains[3563] = 3541
ends[3563] = true
chains[3564] = 3542
ends[3564] = true
chains[3565] = 3561
ends[3565] = true
chains[3566] = 3367
ends[3566] = true
chains[3568] = 3568
ends[3568] = true
chains[3569] = 3568
chains[3570] = 3568
ends[3570] = true
chains[3601] = 3601
chains[3602] = 2783
chains[3621] = 2783
chains[3625] = 2783
chains[3626] = 2783
chains[3627] = 2783
chains[3628] = 2783
ends[3628] = true
chains[3638] = 3638
chains[3639] = 3638
ends[3639] = true
chains[3640] = 3640
chains[3641] = 3640
ends[3641] = true
chains[3642] = 3642
chains[3643] = 3642
ends[3643] = true
chains[3645] = 3640
ends[3645] = true
chains[3647] = 3642
ends[3647] = true
chains[3661] = 3661
chains[3701] = 3702
ends[3701] = true
chains[3702] = 3702
chains[3761] = 3761
chains[3764] = 3764
chains[3765] = 3765
chains[3781] = 3764
chains[3782] = 3761
chains[3783] = 3783
chains[3785] = 3764
ends[3785] = true
chains[3786] = 3761
chains[3791] = 3791
chains[3792] = 3791
ends[3792] = true
chains[3801] = 3801
chains[3802] = 3801
ends[3802] = true
chains[3804] = 3761
ends[3804] = true
chains[3821] = 3821
chains[3822] = 3821
ends[3822] = true
chains[3823] = 3823
chains[3824] = 3823
chains[3825] = 3823
ends[3825] = true
chains[3841] = 2969
chains[3842] = 2969
chains[3843] = 2969
chains[3844] = 3844
chains[3845] = 3844
chains[3903] = 5261
chains[3904] = 5261
ends[3904] = true
chains[3905] = 5261
ends[3905] = true
chains[3908] = 3844
chains[3909] = 3844
ends[3909] = true
chains[3912] = 3912
chains[3913] = 3912
chains[3914] = 3912
chains[3921] = 894
chains[3922] = 894
chains[3923] = 894
chains[3924] = 894
ends[3924] = true
chains[3941] = 3912
chains[3942] = 3912
chains[3961] = 3912
chains[3962] = 3912
ends[3962] = true
chains[3981] = 3981
chains[3982] = 3981
chains[4001] = 3981
chains[4002] = 3981
chains[4003] = 3981
ends[4003] = true
chains[4004] = 3981
ends[4004] = true
chains[4005] = 3912
chains[4021] = 850
ends[4021] = true
chains[4022] = 3441
ends[4022] = true
chains[4061] = 4061
chains[4062] = 4061
chains[4063] = 4061
ends[4063] = true
chains[4081] = 4081
chains[4082] = 4081
ends[4082] = true
chains[4084] = 3912
chains[4103] = 5882
ends[4103] = true
chains[4104] = 5883
ends[4104] = true
chains[4105] = 5884
ends[4105] = true
chains[4106] = 5885
ends[4106] = true
chains[4107] = 5886
ends[4107] = true
chains[4108] = 5887
ends[4108] = true
chains[4109] = 5888
ends[4109] = true
chains[4110] = 5889
ends[4110] = true
chains[4111] = 5890
ends[4111] = true
chains[4112] = 5891
ends[4112] = true
chains[4121] = 4122
chains[4122] = 4122
chains[4124] = 4124
chains[4125] = 4124
chains[4126] = 4128
ends[4126] = true
chains[4127] = 4124
chains[4128] = 4128
chains[4129] = 4124
chains[4130] = 4124
chains[4131] = 4124
chains[4132] = 4122
ends[4132] = true
chains[4133] = 4133
chains[4134] = 4133
ends[4134] = true
chains[4135] = 4124
chains[4136] = 4324
ends[4136] = true
chains[4141] = 4141
chains[4142] = 4141
chains[4143] = 4141
chains[4144] = 4141
ends[4144] = true
chains[4145] = 4145
chains[4146] = 4145
chains[4147] = 4145
chains[4148] = 4145
ends[4148] = true
chains[4182] = 4182
chains[4183] = 4182
chains[4184] = 4182
chains[4185] = 4182
chains[4186] = 4182
chains[4223] = 4182
chains[4224] = 4182
chains[4241] = 4182
chains[4242] = 4182
chains[4243] = 4243
chains[4244] = 4243
chains[4245] = 4243
ends[4245] = true
chains[4261] = 939
ends[4261] = true
chains[4262] = 4262
chains[4263] = 4262
ends[4263] = true
chains[4264] = 4182
chains[4265] = 4124
ends[4265] = true
chains[4266] = 4124
chains[4267] = 4124
ends[4267] = true
chains[4282] = 4182
chains[4289] = 4289
chains[4290] = 4290
chains[4291] = 4290
chains[4292] = 4290
ends[4292] = true
chains[4293] = 4293
chains[4294] = 4294
chains[4297] = 2969
ends[4297] = true
chains[4298] = 2969
ends[4298] = true
chains[4301] = 4289
ends[4301] = true
chains[4322] = 4182
chains[4324] = 4324
chains[4341] = 3702
ends[4341] = true
chains[4361] = 4361
chains[4362] = 4361
ends[4362] = true
chains[4363] = 4361
ends[4363] = true
chains[4421] = 4421
chains[4441] = 939
chains[4442] = 939
chains[4449] = 4449
chains[4450] = 4449
ends[4450] = true
chains[4491] = 4492
ends[4491] = true
chains[4492] = 4492
chains[4495] = 4495
chains[4496] = 4496
chains[4505] = 6605
chains[4506] = 6605
ends[4506] = true
chains[4507] = 4496
ends[4507] = true
chains[4508] = 4508
chains[4509] = 4509
chains[4510] = 4508
ends[4510] = true
chains[4511] = 4509
ends[4511] = true
chains[4512] = 4512
chains[4513] = 4512
ends[4513] = true
chains[4521] = 4521
chains[4542] = 4542
chains[4561] = 4294
ends[4561] = true
chains[4601] = 4601
chains[4602] = 4602
chains[4603] = 4601
ends[4603] = true
chains[4604] = 4602
ends[4604] = true
chains[4605] = 4601
chains[4606] = 4602
chains[4621] = 1036
ends[4621] = true
chains[4661] = 4293
ends[4661] = true
chains[4681] = 3524
ends[4681] = true
chains[4721] = 4521
ends[4721] = true
chains[4726] = 4726
chains[4734] = 4726
chains[4735] = 4726
chains[4741] = 4521
chains[4742] = 4742
chains[4743] = 4742
ends[4743] = true
chains[4761] = 4761
chains[4762] = 4761
chains[4763] = 4761
ends[4763] = true
chains[4764] = 4766
ends[4764] = true
chains[4765] = 4766
ends[4765] = true
chains[4766] = 4766
chains[4768] = 4769
ends[4768] = true
chains[4769] = 4769
chains[4771] = 4726
ends[4771] = true
chains[4781] = 1796
chains[4782] = 1796
chains[4783] = 1796
ends[4783] = true
chains[4784] = 4784
ends[4784] = true
chains[4786] = 4784
ends[4786] = true
chains[4787] = 3520
chains[4788] = 3520
ends[4788] = true
chains[4808] = 4726
chains[4809] = 4726
chains[4810] = 4726
chains[4811] = 4811
chains[4812] = 4811
ends[4812] = true
chains[4813] = 4811
ends[4813] = true
chains[4821] = 4821
chains[4841] = 4542
chains[4842] = 974
ends[4842] = true
chains[4861] = 6604
chains[4863] = 6604
chains[4864] = 6604
ends[4864] = true
chains[4865] = 4821
chains[4881] = 4881
chains[4882] = 4882
chains[4883] = 4882
ends[4883] = true
chains[4901] = 3661
ends[4901] = true
chains[4902] = 3661
ends[4902] = true
chains[4903] = 4903
chains[4906] = 4421
ends[4906] = true
chains[4907] = 4726
chains[4941] = 4903
chains[4961] = 4961
ends[4961] = true
chains[4966] = 4881
ends[4966] = true
chains[4971] = 4971
chains[4972] = 4971
chains[4973] = 4971
ends[4973] = true
chains[4974] = 4903
chains[4976] = 4961
ends[4976] = true
chains[4981] = 4981
chains[4982] = 4981
ends[4982] = true
chains[4983] = 4981
ends[4983] = true
chains[4984] = 4984
chains[4985] = 4984
ends[4985] = true
chains[5001] = 5001
chains[5002] = 5001
chains[5022] = 5022
chains[5023] = 5023
chains[5048] = 5022
ends[5048] = true
chains[5049] = 5023
ends[5049] = true
chains[5050] = 5050
chains[5051] = 5050
ends[5051] = true
chains[5052] = 878
ends[5052] = true
chains[5054] = 5054
chains[5055] = 5054
chains[5056] = 5054
ends[5056] = true
chains[5057] = 5054
ends[5057] = true
chains[5061] = 27
ends[5061] = true
chains[5062] = 4821
chains[5064] = 4542
ends[5064] = true
chains[5065] = 3520
chains[5081] = 5001
ends[5081] = true
chains[5082] = 6603
ends[5082] = true
chains[5083] = 5083
chains[5084] = 5083
chains[5085] = 5083
chains[5086] = 5083
chains[5087] = 5083
ends[5087] = true
chains[5088] = 4821
ends[5088] = true
chains[5089] = 5089
chains[5102] = 5089
ends[5102] = true
chains[5103] = 5103
chains[5122] = 5122
ends[5122] = true
chains[5123] = 5123
chains[5124] = 5103
ends[5124] = true
chains[5125] = 5122
ends[5125] = true
chains[5126] = 5126
chains[5127] = 5126
ends[5127] = true
chains[5128] = 5123
ends[5128] = true
chains[5152] = 5152
chains[5153] = 5152
chains[5154] = 5152
ends[5154] = true
chains[5155] = 5155
chains[5157] = 5155
chains[5158] = 5155
chains[5159] = 5155
chains[5160] = 5160
chains[5161] = 5160
chains[5162] = 5160
chains[5163] = 3783
ends[5163] = true
chains[5164] = 5160
ends[5164] = true
chains[5165] = 5155
chains[5202] = 5202
chains[5203] = 5202
chains[5204] = 5202
ends[5204] = true
chains[5206] = 5206
chains[5210] = 5152
ends[5210] = true
chains[5211] = 5241
ends[5211] = true
chains[5212] = 5212
chains[5213] = 5212
ends[5213] = true
chains[5215] = 5215
chains[5216] = 5215
chains[5217] = 5215
chains[5219] = 5215
chains[5220] = 5215
chains[5222] = 5215
chains[5223] = 5215
chains[5225] = 5215
ends[5225] = true
chains[5226] = 5215
chains[5228] = 5228
chains[5229] = 5228
chains[5230] = 5228
chains[5231] = 5228
chains[5232] = 5228
chains[5233] = 5228
chains[5234] = 5228
chains[5235] = 5228
ends[5235] = true
chains[5236] = 5228
chains[5237] = 5215
ends[5237] = true
chains[5238] = 5228
ends[5238] = true
chains[5241] = 5241
chains[5242] = 5155
ends[5242] = true
chains[5244] = 5244
chains[5245] = 5244
chains[5246] = 5244
chains[5247] = 5244
ends[5247] = true
chains[5248] = 5244
chains[5251] = 5251
chains[5252] = 5244
chains[5253] = 5244
ends[5253] = true
chains[5261] = 5261
chains[5262] = 5251
chains[5263] = 5251
ends[5263] = true
chains[5264] = 5251
chains[5265] = 5251
ends[5265] = true
chains[5281] = 5281
chains[5282] = 5281
ends[5282] = true
chains[5341] = 5341
chains[5342] = 5341
ends[5342] = true
chains[5343] = 5343
chains[5344] = 5343
ends[5344] = true
chains[5381] = 5381
chains[5382] = 5382
chains[5384] = 5382
chains[5385] = 5202
ends[5385] = true
chains[5386] = 5386
chains[5421] = 5386
ends[5421] = true
chains[5441] = 5441
chains[5461] = 5382
chains[5462] = 5382
chains[5463] = 5382
chains[5464] = 5382
chains[5465] = 5382
chains[5466] = 5382
ends[5466] = true
chains[5481] = 5481
chains[5482] = 5481
ends[5482] = true
chains[5505] = 5533
ends[5505] = true
chains[5511] = 838
ends[5511] = true
chains[5514] = 838
chains[5515] = 5382
chains[5518] = 5518
chains[5519] = 5518
ends[5519] = true
chains[5522] = 4726
chains[5525] = 5525
chains[5526] = 5527
ends[5526] = true
chains[5527] = 5527
chains[5529] = 5529
ends[5529] = true
chains[5531] = 4726
chains[5533] = 5533
chains[5534] = 3601
ends[5534] = true
chains[5537] = 5533
chains[5538] = 5533
chains[5581] = 5381
ends[5581] = true
chains[5582] = 5529
ends[5582] = true
chains[5621] = 5622
ends[5621] = true
chains[5622] = 5622
chains[5623] = 5623
chains[5624] = 5623
ends[5624] = true
chains[5625] = 5626
ends[5625] = true
chains[5626] = 5626
chains[5648] = 5649
ends[5648] = true
chains[5649] = 5649
chains[5650] = 5651
ends[5650] = true
chains[5651] = 5651
chains[5721] = 5206
ends[5721] = true
chains[5722] = 5722
chains[5724] = 5722
ends[5724] = true
chains[5726] = 5726
chains[5727] = 5726
chains[5728] = 5726
ends[5728] = true
chains[5729] = 5726
chains[5730] = 5726
ends[5730] = true
chains[5741] = 5741
chains[5742] = 5742
chains[5781] = 5742
chains[5801] = 5533
chains[5802] = 838
chains[5803] = 5533
ends[5803] = true
chains[5804] = 838
ends[5804] = true
chains[5845] = 5742
chains[5846] = 5742
chains[5848] = 5742
chains[5861] = 5742
chains[5862] = 5742
chains[5882] = 5882
chains[5883] = 5883
chains[5884] = 5884
chains[5885] = 5885
chains[5886] = 5886
chains[5887] = 5887
chains[5888] = 5888
chains[5889] = 5889
chains[5890] = 5890
chains[5891] = 5891
chains[5901] = 5901
ends[5901] = true
chains[5902] = 5901
chains[5903] = 5903
ends[5903] = true
chains[5904] = 5903
chains[5921] = 5921
chains[5922] = 5922
chains[5929] = 5921
chains[5930] = 5922
chains[5931] = 5921
chains[5932] = 5922
chains[5941] = 5206
chains[5942] = 5206
ends[5942] = true
chains[5944] = 5742
ends[5944] = true
chains[6001] = 5921
ends[6001] = true
chains[6002] = 5922
ends[6002] = true
chains[6004] = 6004
chains[6023] = 6004
chains[6025] = 6004
ends[6025] = true
chains[6026] = 6026
chains[6027] = 5741
ends[6027] = true
chains[6041] = 6026
ends[6041] = true
chains[6061] = 6061
chains[6062] = 6062
chains[6063] = 6063
chains[6064] = 6064
chains[6081] = 6062
ends[6081] = true
chains[6082] = 6062
ends[6082] = true
chains[6083] = 6062
chains[6084] = 6064
chains[6085] = 6064
ends[6085] = true
chains[6086] = 6064
ends[6086] = true
chains[6087] = 6061
chains[6088] = 6061
ends[6088] = true
chains[6089] = 6061
ends[6089] = true
chains[6101] = 6063
chains[6102] = 6063
ends[6102] = true
chains[6103] = 6063
ends[6103] = true
chains[6121] = 6121
chains[6122] = 6121
chains[6123] = 6121
chains[6124] = 6121
ends[6124] = true
chains[6125] = 6121
ends[6125] = true
chains[6126] = 6126
chains[6127] = 6126
chains[6128] = 6126
chains[6129] = 6126
ends[6129] = true
chains[6130] = 6126
ends[6130] = true
chains[6133] = 6133
chains[6135] = 6133
chains[6141] = 6141
chains[6144] = 6144
chains[6145] = 6144
chains[6146] = 6144
chains[6147] = 6144
chains[6148] = 6144
ends[6148] = true
chains[6163] = 6133
ends[6163] = true
chains[6181] = 6181
chains[6182] = 6182
chains[6183] = 6182
chains[6184] = 6182
chains[6185] = 6182
chains[6186] = 6182
chains[6187] = 6182
ends[6187] = true
chains[6261] = 6181
chains[6281] = 6181
chains[6282] = 6282
chains[6283] = 6282
ends[6283] = true
chains[6285] = 6181
ends[6285] = true
chains[6301] = 6301
chains[6321] = 6321
chains[6322] = 6321
chains[6323] = 6321
chains[6324] = 6321
ends[6324] = true
chains[6341] = 6344
chains[6342] = 6344
chains[6343] = 6344
ends[6343] = true
chains[6344] = 6344
chains[6361] = 6361
chains[6362] = 6361
chains[6363] = 6361
chains[6364] = 6361
ends[6364] = true
chains[6365] = 6365
chains[6381] = 6301
ends[6381] = true
chains[6384] = 6365
chains[6385] = 6365
chains[6386] = 6365
ends[6386] = true
chains[6387] = 6387
chains[6388] = 6387
chains[6389] = 5903
ends[6389] = true
chains[6390] = 5901
ends[6390] = true
chains[6391] = 6387
chains[6392] = 6387
ends[6392] = true
chains[6394] = 5441
ends[6394] = true
chains[6401] = 6523
ends[6401] = true
chains[6402] = 4182
chains[6403] = 4182
chains[6421] = 6421
chains[6481] = 6421
ends[6481] = true
chains[6501] = 4182
chains[6502] = 4182
ends[6502] = true
chains[6521] = 6522
ends[6521] = true
chains[6522] = 6522
chains[6523] = 6523
ends[6523] = true
chains[6548] = 6548
chains[6562] = 6562
chains[6563] = 6562
ends[6563] = true
chains[6564] = 6564
chains[6565] = 6564
ends[6565] = true
chains[6566] = 4903
chains[6567] = 4903
chains[6568] = 4903
chains[6569] = 4903
ends[6569] = true
chains[6570] = 4903
ends[6570] = true
chains[6571] = 6571
chains[6581] = 6571
ends[6581] = true
chains[6585] = 6585
chains[6601] = 6585
chains[6602] = 6585
ends[6602] = true
chains[6603] = 6603
chains[6604] = 6604
chains[6605] = 6605
chains[6606] = 6606
chains[6621] = 216
ends[6621] = true
chains[6622] = 6623
ends[6622] = true
chains[6623] = 6623
chains[6624] = 6625
ends[6624] = true
chains[6625] = 6625
chains[6627] = 1149
chains[6628] = 1149
ends[6628] = true
chains[6629] = 6548
ends[6629] = true
chains[6661] = 6661
ends[6661] = true
chains[6662] = 6661
ends[6662] = true
chains[6681] = 6681
chains[6701] = 6681
ends[6701] = true
chains[6741] = 7224
ends[6741] = true
chains[6761] = 6761
chains[6762] = 6761
ends[6762] = true
chains[6781] = 7223
ends[6781] = true
chains[6821] = 6821
chains[6822] = 6821
chains[6823] = 6821
chains[6824] = 6821
ends[6824] = true
chains[6844] = 1124
chains[6845] = 1124
chains[6963] = 6963
chains[6964] = 6964
chains[6983] = 6963
ends[6983] = true
chains[6984] = 6963
ends[6984] = true
chains[7003] = 7003
chains[7042] = 7042
chains[7043] = 7042
ends[7043] = true
chains[7044] = 7044
chains[7045] = 7042
ends[7045] = true
chains[7046] = 7044
ends[7046] = true
chains[7061] = 6964
ends[7061] = true
chains[7062] = 7062
chains[7063] = 7062
ends[7063] = true
chains[7141] = 7221
ends[7141] = true
chains[7142] = 7222
ends[7142] = true
chains[7161] = 7161
chains[7162] = 7162
chains[7163] = 7161
chains[7164] = 7161
chains[7165] = 7161
chains[7166] = 7161
chains[7167] = 7161
ends[7167] = true
chains[7168] = 7162
chains[7169] = 7162
chains[7170] = 7162
chains[7171] = 7162
chains[7172] = 7162
ends[7172] = true
chains[7221] = 7221
chains[7222] = 7222
chains[7223] = 7223
chains[7224] = 7224
chains[7401] = 7401
chains[7402] = 7402
chains[7427] = 7401
ends[7427] = true
chains[7428] = 7402
ends[7428] = true
chains[7429] = 5525
ends[7429] = true
chains[7486] = 6821
ends[7486] = true
chains[7488] = 7494
ends[7488] = true
chains[7489] = 7492
ends[7489] = true
chains[7490] = 7490
chains[7491] = 7490
chains[7492] = 7492
chains[7493] = 7490
ends[7493] = true
chains[7494] = 7494
chains[7495] = 7495
chains[7496] = 7495
chains[7497] = 7495
ends[7497] = true
chains[7507] = 7507
chains[7508] = 7507
chains[7509] = 7507
ends[7509] = true
chains[7541] = 1238
ends[7541] = true
chains[7562] = 7562
chains[7563] = 7562
ends[7563] = true
chains[7564] = 7562
ends[7564] = true
chains[7601] = 7601
chains[7602] = 7601
chains[7603] = 7601
ends[7603] = true
chains[7623] = 7623
chains[7624] = 7623
chains[7625] = 7623
ends[7625] = true
chains[7637] = 7637
chains[7639] = 7637
chains[7640] = 7637
chains[7641] = 7637
chains[7642] = 7637
ends[7642] = true
chains[7644] = 7644
chains[7646] = 7644
chains[7647] = 7644
ends[7647] = true
chains[7666] = 7644
ends[7666] = true
chains[7667] = 7667
chains[7721] = 7721
chains[7725] = 7003
ends[7725] = true
chains[7726] = 7721
ends[7726] = true
chains[7733] = 2821
ends[7733] = true
chains[7734] = 2822
ends[7734] = true
chains[7781] = 7781
chains[7782] = 7781
ends[7782] = true
chains[7783] = 7783
chains[7784] = 7783
ends[7784] = true
chains[7785] = 7785
chains[7786] = 7785
ends[7786] = true
chains[7787] = 7785
ends[7787] = true
chains[7788] = 7788
chains[7789] = 7789
chains[7795] = 7795
chains[7796] = 7795
ends[7796] = true
chains[7800] = 7800
chains[7801] = 7800
ends[7801] = true
chains[7805] = 7805
chains[7806] = 7805
ends[7806] = true
chains[7810] = 7810
chains[7811] = 7811
chains[7812] = 7811
ends[7812] = true
chains[7815] = 7815
chains[7816] = 7815
ends[7816] = true
chains[7818] = 7818
chains[7819] = 7818
ends[7819] = true
chains[7823] = 7823
chains[7824] = 7824
chains[7825] = 7823
ends[7825] = true
chains[7832] = 7824
ends[7832] = true
chains[7836] = 7836
chains[7837] = 7836
ends[7837] = true
chains[7838] = 7810
ends[7838] = true
chains[7841] = 7841
chains[7842] = 7841
chains[7843] = 7841
ends[7843] = true
chains[7845] = 7845
chains[7846] = 7845
ends[7846] = true
chains[7847] = 7845
ends[7847] = true
chains[7871] = 7871
chains[7872] = 7872
chains[7873] = 7873
chains[7874] = 7874
chains[7875] = 7875
chains[7876] = 7876
chains[7886] = 7873
ends[7886] = true
chains[7887] = 7871
ends[7887] = true
chains[7888] = 7872
ends[7888] = true
chains[7921] = 7788
ends[7921] = true
chains[7922] = 7876
ends[7922] = true
chains[7923] = 7875
ends[7923] = true
chains[7924] = 7874
ends[7924] = true
chains[7925] = 7789
ends[7925] = true
chains[8041] = 8041
chains[8042] = 8041
chains[8043] = 8041
chains[8044] = 8041
ends[8044] = true
chains[8045] = 8045
chains[8046] = 8045
chains[8047] = 8045
chains[8048] = 8045
ends[8048] = true
chains[8049] = 8049
chains[8050] = 8049
chains[8051] = 8049
chains[8052] = 8049
ends[8052] = true
chains[8080] = 8080
chains[8081] = 8080
ends[8081] = true
chains[8101] = 8101
chains[8102] = 8101
chains[8103] = 8101
chains[8104] = 8101
ends[8104] = true
chains[8106] = 8106
chains[8107] = 8106
chains[8108] = 8106
chains[8109] = 8106
ends[8109] = true
chains[8110] = 8110
chains[8111] = 8110
chains[8112] = 8110
chains[8113] = 8110
ends[8113] = true
chains[8116] = 8116
chains[8117] = 8116
chains[8118] = 8116
chains[8119] = 8116
ends[8119] = true
chains[8123] = 8123
chains[8124] = 8123
ends[8124] = true
chains[8141] = 8141
chains[8142] = 8141
chains[8143] = 8141
chains[8144] = 8141
ends[8144] = true
chains[8145] = 8145
chains[8146] = 8145
chains[8147] = 8145
chains[8148] = 8145
ends[8148] = true
chains[8151] = 8151
chains[8153] = 8151
chains[8154] = 8154
chains[8155] = 8155
chains[8156] = 8156
chains[8157] = 8154
ends[8157] = true
chains[8158] = 8155
ends[8158] = true
chains[8159] = 8156
ends[8159] = true
chains[8160] = 8160
chains[8161] = 8161
chains[8162] = 8162
chains[8163] = 8160
ends[8163] = true
chains[8164] = 8161
ends[8164] = true
chains[8165] = 8162
ends[8165] = true
chains[8181] = 3520
chains[8182] = 3520
ends[8182] = true
chains[8231] = 8151
chains[8232] = 8151
ends[8232] = true
chains[8233] = 8233
chains[8234] = 8233
chains[8235] = 8233
chains[8236] = 8233
ends[8236] = true
chains[8250] = 8250
chains[8251] = 8250
chains[8252] = 8250
chains[8253] = 8250
ends[8253] = true
chains[8254] = 8254
chains[8255] = 8254
chains[8256] = 8254
chains[8257] = 8254
ends[8257] = true
chains[8258] = 7667
ends[8258] = true
chains[8271] = 7221
ends[8271] = true
chains[8272] = 7222
ends[8272] = true
chains[8273] = 2742
ends[8273] = true
chains[8277] = 8277
chains[8278] = 8277
chains[8279] = 8284
ends[8279] = true
chains[8280] = 8280
chains[8281] = 8280
ends[8281] = true
chains[8282] = 8277
ends[8282] = true
chains[8284] = 8284
chains[8285] = 8284
chains[8286] = 8286
chains[8288] = 8286
chains[8291] = 8291
chains[8292] = 8291
ends[8292] = true
chains[8293] = 8294
ends[8293] = true
chains[8294] = 8294
chains[8297] = 8297
chains[8298] = 8297
ends[8298] = true
chains[8299] = 8299
chains[8300] = 8299
ends[8300] = true
chains[8301] = 8286
ends[8301] = true
chains[8303] = 8303
chains[8305] = 8303
chains[8307] = 8307
chains[8313] = 8307
chains[8314] = 8314
chains[8315] = 8314
ends[8315] = true
chains[8317] = 8307
ends[8317] = true
chains[8318] = 8318
chains[8319] = 8318
ends[8319] = true
chains[8320] = 8320
chains[8321] = 8320
ends[8321] = true
chains[8322] = 8322
chains[8323] = 8323
chains[8324] = 8323
ends[8324] = true
chains[8331] = 8331
chains[8332] = 8331
ends[8332] = true
chains[8341] = 8343
ends[8341] = true
chains[8343] = 8343
chains[8348] = 8349
chains[8349] = 8349
chains[8351] = 8351
chains[8352] = 8351
chains[8361] = 8361
chains[8362] = 8361
ends[8362] = true
chains[8363] = 8349
ends[8363] = true
chains[8364] = 8351
ends[8364] = true
chains[8367] = 8367
chains[8368] = 8368
chains[8369] = 8369
chains[8370] = 8370
chains[8371] = 8371
chains[8372] = 8372
chains[8374] = 8374
chains[8375] = 8375
chains[8383] = 8375
ends[8383] = true
chains[8384] = 8374
ends[8384] = true
chains[8385] = 8371
ends[8385] = true
chains[8386] = 8372
ends[8386] = true
chains[8387] = 8369
ends[8387] = true
chains[8388] = 8367
ends[8388] = true
chains[8389] = 8368
ends[8389] = true
chains[8390] = 8370
ends[8390] = true
chains[8391] = 8393
ends[8391] = true
chains[8392] = 8394
ends[8392] = true
chains[8393] = 8393
chains[8394] = 8394
chains[8395] = 8395
chains[8396] = 8396
chains[8397] = 8395
ends[8397] = true
chains[8398] = 8396
ends[8398] = true
chains[8399] = 8399
chains[8400] = 8400
chains[8401] = 8401
chains[8402] = 8402
chains[8403] = 8403
chains[8404] = 8399
ends[8404] = true
chains[8405] = 8400
ends[8405] = true
chains[8406] = 8401
ends[8406] = true
chains[8407] = 8402
ends[8407] = true
chains[8408] = 8403
ends[8408] = true
chains[8409] = 8322
ends[8409] = true
chains[8412] = 8412
chains[8413] = 8412
ends[8413] = true
chains[8414] = 8415
chains[8415] = 8415
chains[8416] = 8415
chains[8417] = 8417
chains[8418] = 8415
ends[8418] = true
chains[8421] = 8421
chains[8422] = 8421
ends[8422] = true
chains[8423] = 8417
chains[8424] = 8417
chains[8425] = 8417
ends[8425] = true
chains[8426] = 8426
chains[8427] = 8427
chains[8428] = 8428
chains[8429] = 8429
chains[8430] = 8430
chains[8431] = 8426
ends[8431] = true
chains[8432] = 8427
ends[8432] = true
chains[8433] = 8428
ends[8433] = true
chains[8434] = 8429
ends[8434] = true
chains[8435] = 8430
ends[8435] = true
chains[8436] = 8436
chains[8437] = 8437
chains[8438] = 8438
chains[8439] = 8439
chains[8440] = 8436
ends[8440] = true
chains[8441] = 8437
ends[8441] = true
chains[8442] = 8438
ends[8442] = true
chains[8443] = 8439
ends[8443] = true
chains[8446] = 8446
chains[8447] = 8446
ends[8447] = true
chains[8464] = 8464
chains[8469] = 8464
ends[8469] = true
chains[8492] = 8492
chains[8493] = 8492
ends[8493] = true
chains[8494] = 8494
chains[8495] = 8494
ends[8495] = true
chains[8499] = 8499
chains[8500] = 8499
ends[8500] = true
chains[8503] = 8503
chains[8504] = 8503
ends[8504] = true
chains[8505] = 8505
chains[8506] = 8505
ends[8506] = true
chains[8507] = 8507
chains[8508] = 8507
ends[8508] = true
chains[8509] = 8509
chains[8510] = 8509
ends[8510] = true
chains[8511] = 8511
chains[8512] = 8511
ends[8512] = true
chains[8513] = 8513
chains[8514] = 8513
ends[8514] = true
chains[8515] = 8515
chains[8516] = 8515
ends[8516] = true
chains[8517] = 8517
chains[8518] = 8517
ends[8518] = true
chains[8519] = 8303
chains[8520] = 8520
chains[8521] = 8520
ends[8521] = true
chains[8522] = 8522
chains[8523] = 8522
ends[8523] = true
chains[8524] = 8524
chains[8525] = 8524
ends[8525] = true
chains[8526] = 8526
chains[8527] = 8526
ends[8527] = true
chains[8528] = 8528
chains[8529] = 8528
ends[8529] = true
chains[8532] = 8532
chains[8533] = 8532
ends[8533] = true
chains[8542] = 8542
chains[8543] = 8542
ends[8543] = true
chains[8545] = 8545
chains[8546] = 8545
ends[8546] = true
chains[8549] = 8549
chains[8550] = 8549
ends[8550] = true
chains[8555] = 8303
chains[8574] = 8800
ends[8574] = true
chains[8575] = 8575
chains[8576] = 8575
ends[8576] = true
chains[8577] = 8577
chains[8578] = 8577
ends[8578] = true
chains[8580] = 8580
chains[8581] = 8580
ends[8581] = true
chains[8582] = 8582
chains[8583] = 8582
ends[8583] = true
chains[8584] = 8584
chains[8585] = 8584
chains[8586] = 8584
ends[8586] = true
chains[8587] = 8584
ends[8587] = true
chains[8588] = 8588
chains[8589] = 8588
ends[8589] = true
chains[8590] = 8590
chains[8591] = 8590
ends[8591] = true
chains[8598] = 8598
chains[8600] = 8600
chains[8601] = 8600
ends[8601] = true
chains[8604] = 8604
chains[8605] = 8604
ends[8605] = true
chains[8606] = 8598
chains[8607] = 8607
chains[8608] = 8607
ends[8608] = true
chains[8609] = 8609
chains[8610] = 8609
ends[8610] = true
chains[8611] = 8611
chains[8612] = 8611
ends[8612] = true
chains[8613] = 8613
chains[8614] = 8613
ends[8614] = true
chains[8615] = 8615
chains[8616] = 8615
ends[8616] = true
chains[8620] = 8598
chains[8728] = 8598
chains[8729] = 8598
ends[8729] = true
chains[8730] = 8303
ends[8730] = true
chains[8731] = 8731
chains[8732] = 8731
ends[8732] = true
chains[8733] = 8733
chains[8734] = 8733
chains[8735] = 8733
chains[8736] = 8733
ends[8736] = true
chains[8741] = 8733
ends[8741] = true
chains[8746] = 8746
chains[8747] = 8747
chains[8748] = 8747
chains[8749] = 8747
chains[8750] = 8747
chains[8751] = 8747
ends[8751] = true
chains[8752] = 8752
chains[8753] = 8752
chains[8754] = 8752
chains[8755] = 8752
chains[8756] = 8752
ends[8756] = true
chains[8757] = 8757
chains[8758] = 8757
chains[8759] = 8757
chains[8760] = 8757
chains[8761] = 8757
ends[8761] = true
chains[8762] = 8762
chains[8763] = 8762
ends[8763] = true
chains[8798] = 3783
ends[8798] = true
chains[8799] = 8746
ends[8799] = true
chains[8800] = 8800
chains[8801] = 8801
chains[8802] = 8801
ends[8802] = true
chains[8811] = 8811
chains[8812] = 8812
chains[8813] = 8813
chains[8814] = 8814
chains[8815] = 8815
chains[8816] = 8816
chains[8817] = 8817
chains[8818] = 8818
chains[8819] = 8819
chains[8820] = 8820
chains[8821] = 8821
chains[8822] = 8822
chains[8823] = 8823
chains[8824] = 8824
chains[8825] = 8825
chains[8826] = 8826
chains[8830] = 8811
ends[8830] = true
chains[8831] = 8819
ends[8831] = true
chains[8832] = 8815
ends[8832] = true
chains[8833] = 8823
ends[8833] = true
chains[8834] = 8812
ends[8834] = true
chains[8835] = 8820
ends[8835] = true
chains[8836] = 8813
ends[8836] = true
chains[8837] = 8821
ends[8837] = true
chains[8838] = 8814
ends[8838] = true
chains[8839] = 8822
ends[8839] = true
chains[8840] = 8816
ends[8840] = true
chains[8841] = 8824
ends[8841] = true
chains[8842] = 8817
ends[8842] = true
chains[8843] = 8825
ends[8843] = true
chains[8844] = 8818
ends[8844] = true
chains[8845] = 8826
ends[8845] = true
chains[8867] = 8867
ends[8867] = true
chains[8883] = 8867
ends[8883] = true
chains[8903] = 8903
chains[8904] = 8904
chains[8921] = 8921
chains[8924] = 8921
chains[8925] = 8921
chains[8928] = 8921
ends[8928] = true
chains[8945] = 8945
chains[8946] = 8945
chains[8947] = 8945
chains[8948] = 8945
chains[8949] = 8945
chains[8950] = 8945
chains[8962] = 8962
chains[8963] = 8963
chains[8964] = 8964
chains[8965] = 8965
chains[8966] = 8962
ends[8966] = true
chains[8967] = 8963
ends[8967] = true
chains[8968] = 8964
ends[8968] = true
chains[8969] = 8965
ends[8969] = true
chains[8979] = 8904
ends[8979] = true
chains[8980] = 8904
chains[8982] = 8904
chains[8983] = 8904
chains[8984] = 8904
ends[8984] = true
chains[8985] = 8985
chains[8986] = 8986
chains[8987] = 8987
chains[8988] = 8988
chains[8989] = 8986
ends[8989] = true
chains[8990] = 8985
ends[8990] = true
chains[8991] = 8987
ends[8991] = true
chains[8992] = 8988
ends[8992] = true
chains[8994] = 8994
chains[8995] = 8994
chains[8996] = 8994
ends[8996] = true
chains[9015] = 8945
ends[9015] = true
chains[9024] = 8903
ends[9024] = true
chains[9025] = 8903
chains[9026] = 8903
chains[9027] = 8903
chains[9028] = 8903
ends[9028] = true
chains[9051] = 9063
chains[9052] = 9063
chains[9053] = 9063
ends[9053] = true
chains[9063] = 9063
chains[9124] = 9124
chains[9125] = 9124
ends[9125] = true
chains[9126] = 9126
chains[9127] = 9126
ends[9127] = true
chains[9128] = 9128
chains[9129] = 9128
ends[9129] = true
chains[9131] = 9131
chains[9132] = 9131
ends[9132] = true
chains[9136] = 9136
chains[9137] = 9136
ends[9137] = true
chains[9141] = 9141
chains[9142] = 9141
ends[9142] = true
chains[9229] = 9229
chains[9230] = 9229
ends[9230] = true
chains[9250] = 9250
chains[9251] = 9250
ends[9251] = true
chains[9362] = 9362
chains[9364] = 9362
ends[9364] = true
chains[9415] = 9415
chains[9416] = 9416
chains[9419] = 9415
ends[9419] = true
chains[9422] = 9416
ends[9422] = true
