-- generated by scripts/knowledge.ts from cmangos classic-db (GPL-3.0): do not edit
-- quests[id] = { class, spell }: a class's own quest and the spell it gives
-- npcs[name] = { people, role }: a quest giver's people and calling
local _, ns = ...
local K = { quests = {}, npcs = {} }
ns.knowledge = K
local quests, npcs = K.quests, K.npcs
quests[26] = { class = "DRUID" }
quests[27] = { class = "DRUID" }
quests[28] = { class = "DRUID" }
quests[29] = { class = "DRUID" }
quests[30] = { class = "DRUID" }
quests[31] = { class = "DRUID", spell = "Aquatic Form" }
quests[63] = { class = "SHAMAN" }
quests[96] = { class = "SHAMAN", spell = "Healing Stream Totem" }
quests[100] = { class = "SHAMAN" }
quests[220] = { class = "SHAMAN" }
quests[272] = { class = "DRUID" }
quests[397] = { class = "WARLOCK" }
quests[972] = { class = "SHAMAN" }
quests[1103] = { class = "SHAMAN" }
quests[1442] = { class = "PALADIN" }
quests[1462] = { class = "SHAMAN" }
quests[1463] = { class = "SHAMAN" }
quests[1464] = { class = "SHAMAN" }
quests[1470] = { class = "WARLOCK", spell = "Summon Imp" }
quests[1471] = { class = "WARLOCK", spell = "Summon Voidwalker" }
quests[1472] = { class = "WARLOCK" }
quests[1473] = { class = "WARLOCK" }
quests[1474] = { class = "WARLOCK", spell = "Summon Succubus" }
quests[1476] = { class = "WARLOCK" }
quests[1478] = { class = "WARLOCK" }
quests[1485] = { class = "WARLOCK", spell = "Summon Imp" }
quests[1498] = { class = "WARRIOR", spell = "Taunt" }
quests[1499] = { class = "WARLOCK" }
quests[1501] = { class = "WARLOCK" }
quests[1502] = { class = "WARRIOR" }
quests[1503] = { class = "WARRIOR" }
quests[1504] = { class = "WARLOCK", spell = "Summon Voidwalker" }
quests[1505] = { class = "WARRIOR" }
quests[1506] = { class = "WARLOCK" }
quests[1507] = { class = "WARLOCK" }
quests[1508] = { class = "WARLOCK" }
quests[1509] = { class = "WARLOCK" }
quests[1510] = { class = "WARLOCK" }
quests[1511] = { class = "WARLOCK" }
quests[1512] = { class = "WARLOCK" }
quests[1513] = { class = "WARLOCK", spell = "Summon Succubus" }
quests[1515] = { class = "WARLOCK" }
quests[1516] = { class = "SHAMAN" }
quests[1517] = { class = "SHAMAN" }
quests[1518] = { class = "SHAMAN", spell = "Stoneskin Totem" }
quests[1519] = { class = "SHAMAN" }
quests[1520] = { class = "SHAMAN" }
quests[1521] = { class = "SHAMAN", spell = "Stoneskin Totem" }
quests[1522] = { class = "SHAMAN" }
quests[1523] = { class = "SHAMAN" }
quests[1524] = { class = "SHAMAN" }
quests[1525] = { class = "SHAMAN" }
quests[1526] = { class = "SHAMAN" }
quests[1527] = { class = "SHAMAN", spell = "Searing Totem" }
quests[1528] = { class = "SHAMAN" }
quests[1529] = { class = "SHAMAN" }
quests[1530] = { class = "SHAMAN" }
quests[1531] = { class = "SHAMAN" }
quests[1532] = { class = "SHAMAN" }
quests[1534] = { class = "SHAMAN" }
quests[1535] = { class = "SHAMAN" }
quests[1536] = { class = "SHAMAN" }
quests[1598] = { class = "WARLOCK", spell = "Summon Imp" }
quests[1599] = { class = "WARLOCK", spell = "Summon Imp" }
quests[1638] = { class = "WARRIOR" }
quests[1639] = { class = "WARRIOR" }
quests[1640] = { class = "WARRIOR" }
quests[1641] = { class = "PALADIN" }
quests[1642] = { class = "PALADIN" }
quests[1643] = { class = "PALADIN" }
quests[1644] = { class = "PALADIN" }
quests[1645] = { class = "PALADIN" }
quests[1646] = { class = "PALADIN" }
quests[1647] = { class = "PALADIN" }
quests[1648] = { class = "PALADIN" }
quests[1649] = { class = "PALADIN" }
quests[1650] = { class = "PALADIN" }
quests[1651] = { class = "PALADIN" }
quests[1652] = { class = "PALADIN", spell = "Sense Undead" }
quests[1653] = { class = "PALADIN" }
quests[1654] = { class = "PALADIN" }
quests[1655] = { class = "PALADIN" }
quests[1661] = { class = "PALADIN" }
quests[1665] = { class = "WARRIOR", spell = "Taunt" }
quests[1666] = { class = "WARRIOR" }
quests[1667] = { class = "WARRIOR" }
quests[1678] = { class = "WARRIOR", spell = "Taunt" }
quests[1679] = { class = "WARRIOR" }
quests[1680] = { class = "WARRIOR" }
quests[1681] = { class = "WARRIOR" }
quests[1682] = { class = "WARRIOR" }
quests[1683] = { class = "WARRIOR", spell = "Taunt" }
quests[1684] = { class = "WARRIOR" }
quests[1685] = { class = "WARLOCK" }
quests[1686] = { class = "WARRIOR" }
quests[1688] = { class = "WARLOCK" }
quests[1689] = { class = "WARLOCK", spell = "Summon Voidwalker" }
quests[1692] = { class = "WARRIOR" }
quests[1693] = { class = "WARRIOR" }
quests[1698] = { class = "WARRIOR" }
quests[1699] = { class = "WARRIOR" }
quests[1700] = { class = "WARRIOR" }
quests[1701] = { class = "WARRIOR" }
quests[1702] = { class = "WARRIOR" }
quests[1703] = { class = "WARRIOR" }
quests[1704] = { class = "WARRIOR" }
quests[1705] = { class = "WARRIOR" }
quests[1706] = { class = "WARRIOR" }
quests[1708] = { class = "WARRIOR" }
quests[1709] = { class = "WARRIOR" }
quests[1710] = { class = "WARRIOR" }
quests[1711] = { class = "WARRIOR" }
quests[1712] = { class = "WARRIOR" }
quests[1713] = { class = "WARRIOR" }
quests[1714] = { class = "WARRIOR" }
quests[1715] = { class = "WARLOCK" }
quests[1716] = { class = "WARLOCK" }
quests[1717] = { class = "WARLOCK" }
quests[1718] = { class = "WARRIOR" }
quests[1719] = { class = "WARRIOR", spell = "Intercept" }
quests[1738] = { class = "WARLOCK" }
quests[1739] = { class = "WARLOCK", spell = "Summon Succubus" }
quests[1740] = { class = "WARLOCK" }
quests[1758] = { class = "WARLOCK" }
quests[1778] = { class = "PALADIN" }
quests[1779] = { class = "PALADIN" }
quests[1780] = { class = "PALADIN" }
quests[1781] = { class = "PALADIN" }
quests[1782] = { class = "WARRIOR" }
quests[1783] = { class = "PALADIN" }
quests[1784] = { class = "PALADIN" }
quests[1785] = { class = "PALADIN", spell = "Redemption" }
quests[1786] = { class = "PALADIN" }
quests[1787] = { class = "PALADIN" }
quests[1788] = { class = "PALADIN", spell = "Redemption" }
quests[1789] = { class = "PALADIN" }
quests[1790] = { class = "PALADIN" }
quests[1791] = { class = "WARRIOR" }
quests[1792] = { class = "WARRIOR" }
quests[1793] = { class = "PALADIN" }
quests[1794] = { class = "PALADIN" }
quests[1795] = { class = "WARLOCK", spell = "Summon Felhunter" }
quests[1796] = { class = "WARLOCK" }
quests[1798] = { class = "WARLOCK" }
quests[1799] = { class = "WARLOCK" }
quests[1801] = { class = "WARLOCK" }
quests[1802] = { class = "WARLOCK" }
quests[1803] = { class = "WARLOCK" }
quests[1804] = { class = "WARLOCK" }
quests[1805] = { class = "WARLOCK" }
quests[1806] = { class = "PALADIN" }
quests[1818] = { class = "WARRIOR" }
quests[1819] = { class = "WARRIOR", spell = "Taunt" }
quests[1820] = { class = "WARRIOR" }
quests[1821] = { class = "WARRIOR" }
quests[1822] = { class = "WARRIOR" }
quests[1823] = { class = "WARRIOR" }
quests[1824] = { class = "WARRIOR" }
quests[1825] = { class = "WARRIOR" }
quests[1838] = { class = "WARRIOR" }
quests[1839] = { class = "WARRIOR" }
quests[1840] = { class = "WARRIOR" }
quests[1841] = { class = "WARRIOR" }
quests[1842] = { class = "WARRIOR" }
quests[1843] = { class = "WARRIOR" }
quests[1844] = { class = "WARRIOR" }
quests[1845] = { class = "WARRIOR" }
quests[1846] = { class = "WARRIOR" }
quests[1847] = { class = "WARRIOR" }
quests[1848] = { class = "WARRIOR" }
quests[1858] = { class = "ROGUE" }
quests[1859] = { class = "ROGUE" }
quests[1860] = { class = "MAGE" }
quests[1861] = { class = "MAGE" }
quests[1879] = { class = "MAGE" }
quests[1880] = { class = "MAGE" }
quests[1881] = { class = "MAGE" }
quests[1882] = { class = "MAGE" }
quests[1883] = { class = "MAGE" }
quests[1884] = { class = "MAGE" }
quests[1885] = { class = "ROGUE" }
quests[1886] = { class = "ROGUE" }
quests[1898] = { class = "ROGUE" }
quests[1899] = { class = "ROGUE" }
quests[1919] = { class = "MAGE" }
quests[1920] = { class = "MAGE" }
quests[1921] = { class = "MAGE" }
quests[1938] = { class = "MAGE" }
quests[1939] = { class = "MAGE" }
quests[1940] = { class = "MAGE" }
quests[1941] = { class = "MAGE" }
quests[1942] = { class = "MAGE" }
quests[1943] = { class = "MAGE" }
quests[1944] = { class = "MAGE" }
quests[1945] = { class = "MAGE" }
quests[1946] = { class = "MAGE" }
quests[1947] = { class = "MAGE" }
quests[1948] = { class = "MAGE" }
quests[1949] = { class = "MAGE" }
quests[1950] = { class = "MAGE" }
quests[1951] = { class = "MAGE" }
quests[1952] = { class = "MAGE" }
quests[1953] = { class = "MAGE" }
quests[1954] = { class = "MAGE" }
quests[1955] = { class = "MAGE" }
quests[1956] = { class = "MAGE" }
quests[1957] = { class = "MAGE" }
quests[1958] = { class = "MAGE" }
quests[1959] = { class = "MAGE" }
quests[1960] = { class = "MAGE" }
quests[1961] = { class = "MAGE" }
quests[1962] = { class = "MAGE" }
quests[1963] = { class = "ROGUE" }
quests[1978] = { class = "ROGUE" }
quests[1998] = { class = "ROGUE" }
quests[1999] = { class = "ROGUE" }
quests[2205] = { class = "ROGUE" }
quests[2206] = { class = "ROGUE" }
quests[2218] = { class = "ROGUE" }
quests[2238] = { class = "ROGUE" }
quests[2239] = { class = "ROGUE" }
quests[2241] = { class = "ROGUE" }
quests[2242] = { class = "ROGUE" }
quests[2259] = { class = "ROGUE" }
quests[2260] = { class = "ROGUE" }
quests[2281] = { class = "ROGUE" }
quests[2282] = { class = "ROGUE" }
quests[2298] = { class = "ROGUE" }
quests[2299] = { class = "ROGUE" }
quests[2300] = { class = "ROGUE" }
quests[2358] = { class = "ROGUE" }
quests[2359] = { class = "ROGUE", spell = "Poisons" }
quests[2360] = { class = "ROGUE" }
quests[2378] = { class = "ROGUE" }
quests[2379] = { class = "ROGUE" }
quests[2380] = { class = "ROGUE" }
quests[2381] = { class = "ROGUE" }
quests[2382] = { class = "ROGUE" }
quests[2383] = { class = "WARRIOR" }
quests[2458] = { class = "ROGUE" }
quests[2460] = { class = "ROGUE" }
quests[2478] = { class = "ROGUE" }
quests[2479] = { class = "ROGUE" }
quests[2480] = { class = "ROGUE", spell = "Poisons" }
quests[2607] = { class = "ROGUE" }
quests[2608] = { class = "ROGUE" }
quests[2609] = { class = "ROGUE" }
quests[2983] = { class = "SHAMAN" }
quests[2984] = { class = "SHAMAN" }
quests[2985] = { class = "SHAMAN" }
quests[2986] = { class = "SHAMAN" }
quests[2996] = { class = "WARLOCK" }
quests[2997] = { class = "PALADIN" }
quests[2998] = { class = "PALADIN" }
quests[2999] = { class = "PALADIN" }
quests[3000] = { class = "PALADIN" }
quests[3001] = { class = "WARLOCK" }
quests[3065] = { class = "WARRIOR" }
quests[3082] = { class = "HUNTER" }
quests[3083] = { class = "ROGUE" }
quests[3084] = { class = "SHAMAN" }
quests[3085] = { class = "PRIEST" }
quests[3086] = { class = "MAGE" }
quests[3087] = { class = "HUNTER" }
quests[3088] = { class = "ROGUE" }
quests[3089] = { class = "SHAMAN" }
quests[3090] = { class = "WARLOCK" }
quests[3091] = { class = "WARRIOR" }
quests[3092] = { class = "HUNTER" }
quests[3093] = { class = "SHAMAN" }
quests[3094] = { class = "DRUID" }
quests[3095] = { class = "WARRIOR" }
quests[3096] = { class = "ROGUE" }
quests[3097] = { class = "PRIEST" }
quests[3098] = { class = "MAGE" }
quests[3099] = { class = "WARLOCK" }
quests[3100] = { class = "WARRIOR" }
quests[3101] = { class = "PALADIN" }
quests[3102] = { class = "ROGUE" }
quests[3103] = { class = "PRIEST" }
quests[3104] = { class = "MAGE" }
quests[3105] = { class = "WARLOCK" }
quests[3106] = { class = "WARRIOR" }
quests[3107] = { class = "PALADIN" }
quests[3108] = { class = "HUNTER" }
quests[3109] = { class = "ROGUE" }
quests[3110] = { class = "PRIEST" }
quests[3112] = { class = "WARRIOR" }
quests[3113] = { class = "ROGUE" }
quests[3114] = { class = "MAGE" }
quests[3115] = { class = "WARLOCK" }
quests[3116] = { class = "WARRIOR" }
quests[3117] = { class = "HUNTER" }
quests[3118] = { class = "ROGUE" }
quests[3119] = { class = "PRIEST" }
quests[3120] = { class = "DRUID" }
quests[3631] = { class = "WARLOCK" }
quests[3681] = { class = "PALADIN" }
quests[4485] = { class = "PALADIN" }
quests[4486] = { class = "PALADIN" }
quests[4487] = { class = "WARLOCK" }
quests[4488] = { class = "WARLOCK" }
quests[4489] = { class = "WARLOCK" }
quests[4490] = { class = "WARLOCK", spell = "Summon Felsteed" }
quests[4736] = { class = "WARLOCK" }
quests[4737] = { class = "WARLOCK" }
quests[4738] = { class = "WARLOCK" }
quests[4739] = { class = "WARLOCK" }
quests[4781] = { class = "WARLOCK" }
quests[4782] = { class = "WARLOCK" }
quests[4783] = { class = "WARLOCK" }
quests[4784] = { class = "WARLOCK" }
quests[4785] = { class = "WARLOCK" }
quests[4786] = { class = "WARLOCK" }
quests[4961] = { class = "WARLOCK" }
quests[4962] = { class = "WARLOCK" }
quests[4963] = { class = "WARLOCK" }
quests[4964] = { class = "WARLOCK" }
quests[4965] = { class = "WARLOCK" }
quests[4967] = { class = "WARLOCK" }
quests[4968] = { class = "WARLOCK" }
quests[4969] = { class = "WARLOCK" }
quests[4975] = { class = "WARLOCK" }
quests[4976] = { class = "WARLOCK" }
quests[5061] = { class = "DRUID", spell = "Aquatic Form" }
quests[5621] = { class = "PRIEST" }
quests[5622] = { class = "PRIEST" }
quests[5623] = { class = "PRIEST" }
quests[5624] = { class = "PRIEST" }
quests[5625] = { class = "PRIEST" }
quests[5626] = { class = "PRIEST" }
quests[5627] = { class = "PRIEST" }
quests[5628] = { class = "PRIEST", spell = "Starshards" }
quests[5629] = { class = "PRIEST", spell = "Starshards" }
quests[5630] = { class = "PRIEST", spell = "Starshards" }
quests[5631] = { class = "PRIEST", spell = "Starshards" }
quests[5632] = { class = "PRIEST", spell = "Starshards" }
quests[5633] = { class = "PRIEST", spell = "Starshards" }
quests[5634] = { class = "PRIEST", spell = "Desperate Prayer" }
quests[5635] = { class = "PRIEST", spell = "Desperate Prayer" }
quests[5636] = { class = "PRIEST", spell = "Desperate Prayer" }
quests[5637] = { class = "PRIEST", spell = "Desperate Prayer" }
quests[5638] = { class = "PRIEST", spell = "Desperate Prayer" }
quests[5639] = { class = "PRIEST", spell = "Desperate Prayer" }
quests[5641] = { class = "PRIEST", spell = "Fear Ward" }
quests[5642] = { class = "PRIEST", spell = "Shadowguard" }
quests[5643] = { class = "PRIEST", spell = "Shadowguard" }
quests[5644] = { class = "PRIEST", spell = "Devouring Plague" }
quests[5645] = { class = "PRIEST", spell = "Fear Ward" }
quests[5646] = { class = "PRIEST", spell = "Devouring Plague" }
quests[5647] = { class = "PRIEST", spell = "Fear Ward" }
quests[5648] = { class = "PRIEST" }
quests[5649] = { class = "PRIEST" }
quests[5650] = { class = "PRIEST" }
quests[5651] = { class = "PRIEST" }
quests[5652] = { class = "PRIEST", spell = "Hex of Weakness" }
quests[5654] = { class = "PRIEST", spell = "Hex of Weakness" }
quests[5655] = { class = "PRIEST", spell = "Hex of Weakness" }
quests[5656] = { class = "PRIEST", spell = "Hex of Weakness" }
quests[5657] = { class = "PRIEST", spell = "Hex of Weakness" }
quests[5658] = { class = "PRIEST", spell = "Touch of Weakness" }
quests[5660] = { class = "PRIEST", spell = "Touch of Weakness" }
quests[5661] = { class = "PRIEST", spell = "Touch of Weakness" }
quests[5662] = { class = "PRIEST", spell = "Touch of Weakness" }
quests[5663] = { class = "PRIEST", spell = "Touch of Weakness" }
quests[5672] = { class = "PRIEST", spell = "Elune's Grace" }
quests[5673] = { class = "PRIEST", spell = "Elune's Grace" }
quests[5674] = { class = "PRIEST", spell = "Elune's Grace" }
quests[5675] = { class = "PRIEST", spell = "Elune's Grace" }
quests[5676] = { class = "PRIEST", spell = "Feedback" }
quests[5677] = { class = "PRIEST", spell = "Desperate Prayer" }
quests[5679] = { class = "PRIEST", spell = "Devouring Plague" }
quests[5680] = { class = "PRIEST", spell = "Shadowguard" }
quests[5921] = { class = "DRUID" }
quests[5922] = { class = "DRUID" }
quests[5923] = { class = "DRUID" }
quests[5924] = { class = "DRUID" }
quests[5925] = { class = "DRUID" }
quests[5926] = { class = "DRUID" }
quests[5927] = { class = "DRUID" }
quests[5928] = { class = "DRUID" }
quests[5929] = { class = "DRUID" }
quests[5930] = { class = "DRUID" }
quests[5931] = { class = "DRUID" }
quests[5932] = { class = "DRUID" }
quests[6001] = { class = "DRUID", spell = "Maul" }
quests[6002] = { class = "DRUID", spell = "Maul" }
quests[6061] = { class = "HUNTER" }
quests[6062] = { class = "HUNTER" }
quests[6063] = { class = "HUNTER" }
quests[6064] = { class = "HUNTER" }
quests[6065] = { class = "HUNTER" }
quests[6066] = { class = "HUNTER" }
quests[6067] = { class = "HUNTER" }
quests[6068] = { class = "HUNTER" }
quests[6069] = { class = "HUNTER" }
quests[6070] = { class = "HUNTER" }
quests[6071] = { class = "HUNTER" }
quests[6072] = { class = "HUNTER" }
quests[6073] = { class = "HUNTER" }
quests[6074] = { class = "HUNTER" }
quests[6075] = { class = "HUNTER" }
quests[6076] = { class = "HUNTER" }
quests[6081] = { class = "HUNTER", spell = "Revive Pet" }
quests[6082] = { class = "HUNTER", spell = "Dismiss Pet" }
quests[6083] = { class = "HUNTER" }
quests[6084] = { class = "HUNTER" }
quests[6085] = { class = "HUNTER", spell = "Dismiss Pet" }
quests[6086] = { class = "HUNTER", spell = "Revive Pet" }
quests[6087] = { class = "HUNTER" }
quests[6088] = { class = "HUNTER", spell = "Dismiss Pet" }
quests[6089] = { class = "HUNTER", spell = "Revive Pet" }
quests[6101] = { class = "HUNTER" }
quests[6102] = { class = "HUNTER", spell = "Dismiss Pet" }
quests[6103] = { class = "HUNTER", spell = "Revive Pet" }
quests[6121] = { class = "DRUID" }
quests[6122] = { class = "DRUID" }
quests[6123] = { class = "DRUID" }
quests[6124] = { class = "DRUID" }
quests[6125] = { class = "DRUID", spell = "Cure Poison" }
quests[6126] = { class = "DRUID" }
quests[6127] = { class = "DRUID" }
quests[6128] = { class = "DRUID" }
quests[6129] = { class = "DRUID" }
quests[6130] = { class = "DRUID", spell = "Cure Poison" }
quests[6681] = { class = "ROGUE" }
quests[6701] = { class = "ROGUE" }
quests[6721] = { class = "HUNTER" }
quests[6722] = { class = "HUNTER" }
quests[7463] = { class = "MAGE", spell = "Conjure Water" }
quests[7498] = { class = "ROGUE" }
quests[7499] = { class = "WARRIOR" }
quests[7500] = { class = "MAGE" }
quests[7501] = { class = "PALADIN" }
quests[7502] = { class = "WARLOCK" }
quests[7503] = { class = "HUNTER" }
quests[7504] = { class = "PRIEST" }
quests[7505] = { class = "SHAMAN" }
quests[7506] = { class = "DRUID" }
quests[7562] = { class = "WARLOCK" }
quests[7563] = { class = "WARLOCK" }
quests[7564] = { class = "WARLOCK" }
quests[7581] = { class = "WARLOCK" }
quests[7582] = { class = "WARLOCK" }
quests[7583] = { class = "WARLOCK", spell = "Ritual of Doom" }
quests[7601] = { class = "WARLOCK" }
quests[7602] = { class = "WARLOCK" }
quests[7603] = { class = "WARLOCK", spell = "Inferno" }
quests[7621] = { class = "PRIEST" }
quests[7622] = { class = "PRIEST" }
quests[7623] = { class = "WARLOCK" }
quests[7624] = { class = "WARLOCK" }
quests[7625] = { class = "WARLOCK" }
quests[7626] = { class = "WARLOCK" }
quests[7627] = { class = "WARLOCK" }
quests[7628] = { class = "WARLOCK" }
quests[7629] = { class = "WARLOCK" }
quests[7630] = { class = "WARLOCK" }
quests[7631] = { class = "WARLOCK" }
quests[7632] = { class = "HUNTER" }
quests[7633] = { class = "HUNTER" }
quests[7634] = { class = "HUNTER" }
quests[7635] = { class = "HUNTER" }
quests[7636] = { class = "HUNTER" }
quests[7637] = { class = "PALADIN" }
quests[7638] = { class = "PALADIN" }
quests[7639] = { class = "PALADIN" }
quests[7640] = { class = "PALADIN" }
quests[7641] = { class = "PALADIN" }
quests[7642] = { class = "PALADIN" }
quests[7643] = { class = "PALADIN" }
quests[7644] = { class = "PALADIN" }
quests[7645] = { class = "PALADIN" }
quests[7646] = { class = "PALADIN" }
quests[7647] = { class = "PALADIN" }
quests[7648] = { class = "PALADIN" }
quests[7666] = { class = "PALADIN" }
quests[7667] = { class = "SHAMAN" }
quests[8041] = { class = "WARRIOR" }
quests[8042] = { class = "WARRIOR" }
quests[8043] = { class = "WARRIOR" }
quests[8044] = { class = "WARRIOR" }
quests[8045] = { class = "PALADIN" }
quests[8046] = { class = "PALADIN" }
quests[8047] = { class = "PALADIN" }
quests[8048] = { class = "PALADIN" }
quests[8049] = { class = "PRIEST" }
quests[8050] = { class = "PRIEST" }
quests[8051] = { class = "PRIEST" }
quests[8052] = { class = "PRIEST" }
quests[8053] = { class = "PALADIN" }
quests[8054] = { class = "PALADIN" }
quests[8055] = { class = "PALADIN" }
quests[8056] = { class = "SHAMAN" }
quests[8057] = { class = "DRUID" }
quests[8058] = { class = "WARRIOR" }
quests[8059] = { class = "WARLOCK" }
quests[8060] = { class = "MAGE" }
quests[8061] = { class = "PRIEST" }
quests[8062] = { class = "HUNTER" }
quests[8063] = { class = "ROGUE" }
quests[8064] = { class = "DRUID" }
quests[8065] = { class = "DRUID" }
quests[8066] = { class = "HUNTER" }
quests[8067] = { class = "HUNTER" }
quests[8068] = { class = "MAGE" }
quests[8069] = { class = "MAGE" }
quests[8070] = { class = "PRIEST" }
quests[8071] = { class = "PRIEST" }
quests[8072] = { class = "ROGUE" }
quests[8073] = { class = "ROGUE" }
quests[8074] = { class = "SHAMAN" }
quests[8075] = { class = "SHAMAN" }
quests[8076] = { class = "WARLOCK" }
quests[8077] = { class = "WARLOCK" }
quests[8078] = { class = "WARRIOR" }
quests[8079] = { class = "WARRIOR" }
quests[8101] = { class = "MAGE" }
quests[8102] = { class = "MAGE" }
quests[8103] = { class = "MAGE" }
quests[8104] = { class = "MAGE" }
quests[8106] = { class = "WARLOCK" }
quests[8107] = { class = "WARLOCK" }
quests[8108] = { class = "WARLOCK" }
quests[8109] = { class = "WARLOCK" }
quests[8110] = { class = "DRUID" }
quests[8111] = { class = "DRUID" }
quests[8112] = { class = "DRUID" }
quests[8113] = { class = "DRUID" }
quests[8116] = { class = "SHAMAN" }
quests[8117] = { class = "SHAMAN" }
quests[8118] = { class = "SHAMAN" }
quests[8119] = { class = "SHAMAN" }
quests[8141] = { class = "ROGUE" }
quests[8142] = { class = "ROGUE" }
quests[8143] = { class = "ROGUE" }
quests[8144] = { class = "ROGUE" }
quests[8145] = { class = "HUNTER" }
quests[8146] = { class = "HUNTER" }
quests[8147] = { class = "HUNTER" }
quests[8148] = { class = "HUNTER" }
quests[8151] = { class = "HUNTER" }
quests[8153] = { class = "HUNTER" }
quests[8231] = { class = "HUNTER" }
quests[8232] = { class = "HUNTER" }
quests[8233] = { class = "ROGUE" }
quests[8234] = { class = "ROGUE" }
quests[8235] = { class = "ROGUE" }
quests[8236] = { class = "ROGUE" }
quests[8249] = { class = "ROGUE" }
quests[8250] = { class = "MAGE" }
quests[8251] = { class = "MAGE" }
quests[8252] = { class = "MAGE" }
quests[8253] = { class = "MAGE" }
quests[8254] = { class = "PRIEST" }
quests[8255] = { class = "PRIEST" }
quests[8256] = { class = "PRIEST" }
quests[8257] = { class = "PRIEST" }
quests[8258] = { class = "SHAMAN" }
quests[8316] = { class = "WARRIOR" }
quests[8376] = { class = "PALADIN" }
quests[8377] = { class = "HUNTER" }
quests[8378] = { class = "ROGUE" }
quests[8379] = { class = "PRIEST" }
quests[8380] = { class = "SHAMAN" }
quests[8382] = { class = "DRUID" }
quests[8410] = { class = "SHAMAN" }
quests[8411] = { class = "SHAMAN" }
quests[8412] = { class = "SHAMAN" }
quests[8413] = { class = "SHAMAN" }
quests[8414] = { class = "PALADIN" }
quests[8415] = { class = "PALADIN" }
quests[8416] = { class = "PALADIN" }
quests[8417] = { class = "WARRIOR" }
quests[8418] = { class = "PALADIN" }
quests[8419] = { class = "WARLOCK" }
quests[8420] = { class = "WARLOCK" }
quests[8421] = { class = "WARLOCK" }
quests[8422] = { class = "WARLOCK" }
quests[8423] = { class = "WARRIOR" }
quests[8424] = { class = "WARRIOR" }
quests[8425] = { class = "WARRIOR" }
quests[8544] = { class = "WARRIOR" }
quests[8556] = { class = "WARRIOR" }
quests[8557] = { class = "WARRIOR" }
quests[8558] = { class = "WARRIOR" }
quests[8559] = { class = "WARRIOR" }
quests[8560] = { class = "WARRIOR" }
quests[8561] = { class = "WARRIOR" }
quests[8562] = { class = "WARRIOR" }
quests[8592] = { class = "PRIEST" }
quests[8593] = { class = "PRIEST" }
quests[8594] = { class = "PRIEST" }
quests[8596] = { class = "PRIEST" }
quests[8602] = { class = "SHAMAN" }
quests[8603] = { class = "PRIEST" }
quests[8621] = { class = "SHAMAN" }
quests[8622] = { class = "SHAMAN" }
quests[8623] = { class = "SHAMAN" }
quests[8624] = { class = "SHAMAN" }
quests[8625] = { class = "MAGE" }
quests[8626] = { class = "HUNTER" }
quests[8627] = { class = "PALADIN" }
quests[8628] = { class = "PALADIN" }
quests[8629] = { class = "PALADIN" }
quests[8630] = { class = "PALADIN" }
quests[8631] = { class = "MAGE" }
quests[8632] = { class = "MAGE" }
quests[8633] = { class = "MAGE" }
quests[8634] = { class = "MAGE" }
quests[8637] = { class = "ROGUE" }
quests[8638] = { class = "ROGUE" }
quests[8639] = { class = "ROGUE" }
quests[8640] = { class = "ROGUE" }
quests[8641] = { class = "ROGUE" }
quests[8655] = { class = "PALADIN" }
quests[8656] = { class = "HUNTER" }
quests[8657] = { class = "HUNTER" }
quests[8658] = { class = "HUNTER" }
quests[8659] = { class = "HUNTER" }
quests[8660] = { class = "WARLOCK" }
quests[8661] = { class = "WARLOCK" }
quests[8662] = { class = "WARLOCK" }
quests[8663] = { class = "WARLOCK" }
quests[8664] = { class = "WARLOCK" }
quests[8665] = { class = "DRUID" }
quests[8666] = { class = "DRUID" }
quests[8667] = { class = "DRUID" }
quests[8668] = { class = "DRUID" }
quests[8669] = { class = "DRUID" }
quests[8689] = { class = "PRIEST" }
quests[8690] = { class = "SHAMAN" }
quests[8691] = { class = "MAGE" }
quests[8692] = { class = "DRUID" }
quests[8693] = { class = "ROGUE" }
quests[8694] = { class = "WARLOCK" }
quests[8695] = { class = "PALADIN" }
quests[8696] = { class = "HUNTER" }
quests[8697] = { class = "PRIEST" }
quests[8698] = { class = "SHAMAN" }
quests[8699] = { class = "MAGE" }
quests[8700] = { class = "DRUID" }
quests[8701] = { class = "ROGUE" }
quests[8702] = { class = "WARLOCK" }
quests[8703] = { class = "PALADIN" }
quests[8704] = { class = "HUNTER" }
quests[8705] = { class = "PRIEST" }
quests[8706] = { class = "SHAMAN" }
quests[8707] = { class = "MAGE" }
quests[8708] = { class = "DRUID" }
quests[8709] = { class = "ROGUE" }
quests[8710] = { class = "WARLOCK" }
quests[8711] = { class = "PALADIN" }
quests[8712] = { class = "HUNTER" }
quests[8905] = { class = "DRUID" }
quests[8906] = { class = "HUNTER" }
quests[8907] = { class = "MAGE" }
quests[8908] = { class = "PALADIN" }
quests[8909] = { class = "PRIEST" }
quests[8910] = { class = "ROGUE" }
quests[8911] = { class = "WARLOCK" }
quests[8912] = { class = "WARRIOR" }
quests[8913] = { class = "DRUID" }
quests[8914] = { class = "HUNTER" }
quests[8915] = { class = "MAGE" }
quests[8916] = { class = "PRIEST" }
quests[8917] = { class = "ROGUE" }
quests[8918] = { class = "SHAMAN" }
quests[8919] = { class = "WARLOCK" }
quests[8920] = { class = "WARRIOR" }
quests[8926] = { class = "DRUID" }
quests[8927] = { class = "DRUID" }
quests[8931] = { class = "HUNTER" }
quests[8932] = { class = "MAGE" }
quests[8933] = { class = "PALADIN" }
quests[8934] = { class = "PRIEST" }
quests[8935] = { class = "ROGUE" }
quests[8936] = { class = "WARLOCK" }
quests[8937] = { class = "WARRIOR" }
quests[8938] = { class = "HUNTER" }
quests[8939] = { class = "MAGE" }
quests[8940] = { class = "PRIEST" }
quests[8941] = { class = "ROGUE" }
quests[8942] = { class = "SHAMAN" }
quests[8943] = { class = "WARLOCK" }
quests[8944] = { class = "WARRIOR" }
quests[8951] = { class = "DRUID" }
quests[8952] = { class = "HUNTER" }
quests[8953] = { class = "MAGE" }
quests[8954] = { class = "PALADIN" }
quests[8955] = { class = "PRIEST" }
quests[8956] = { class = "ROGUE" }
quests[8957] = { class = "SHAMAN" }
quests[8958] = { class = "WARLOCK" }
quests[8959] = { class = "WARRIOR" }
quests[8999] = { class = "DRUID" }
quests[9000] = { class = "HUNTER" }
quests[9001] = { class = "MAGE" }
quests[9002] = { class = "PALADIN" }
quests[9003] = { class = "PRIEST" }
quests[9004] = { class = "ROGUE" }
quests[9005] = { class = "WARLOCK" }
quests[9006] = { class = "WARRIOR" }
quests[9007] = { class = "DRUID" }
quests[9008] = { class = "HUNTER" }
quests[9009] = { class = "PRIEST" }
quests[9010] = { class = "ROGUE" }
quests[9011] = { class = "SHAMAN" }
quests[9012] = { class = "WARLOCK" }
quests[9013] = { class = "WARRIOR" }
quests[9014] = { class = "MAGE" }
quests[9016] = { class = "DRUID" }
quests[9017] = { class = "HUNTER" }
quests[9018] = { class = "MAGE" }
quests[9019] = { class = "PRIEST" }
quests[9020] = { class = "ROGUE" }
quests[9021] = { class = "WARLOCK" }
quests[9022] = { class = "WARRIOR" }
quests[9034] = { class = "WARRIOR" }
quests[9036] = { class = "WARRIOR" }
quests[9037] = { class = "WARRIOR" }
quests[9038] = { class = "WARRIOR" }
quests[9039] = { class = "WARRIOR" }
quests[9040] = { class = "WARRIOR" }
quests[9041] = { class = "WARRIOR" }
quests[9042] = { class = "WARRIOR" }
quests[9043] = { class = "PALADIN" }
quests[9044] = { class = "PALADIN" }
quests[9045] = { class = "PALADIN" }
quests[9046] = { class = "PALADIN" }
quests[9047] = { class = "PALADIN" }
quests[9048] = { class = "PALADIN" }
quests[9049] = { class = "PALADIN" }
quests[9050] = { class = "PALADIN" }
quests[9051] = { class = "DRUID" }
quests[9052] = { class = "DRUID" }
quests[9053] = { class = "DRUID" }
quests[9054] = { class = "HUNTER" }
quests[9055] = { class = "HUNTER" }
quests[9056] = { class = "HUNTER" }
quests[9057] = { class = "HUNTER" }
quests[9058] = { class = "HUNTER" }
quests[9059] = { class = "HUNTER" }
quests[9060] = { class = "HUNTER" }
quests[9061] = { class = "HUNTER" }
quests[9063] = { class = "DRUID" }
quests[9068] = { class = "SHAMAN" }
quests[9069] = { class = "SHAMAN" }
quests[9070] = { class = "SHAMAN" }
quests[9071] = { class = "SHAMAN" }
quests[9072] = { class = "SHAMAN" }
quests[9073] = { class = "SHAMAN" }
quests[9074] = { class = "SHAMAN" }
quests[9075] = { class = "SHAMAN" }
quests[9077] = { class = "ROGUE" }
quests[9078] = { class = "ROGUE" }
quests[9079] = { class = "ROGUE" }
quests[9080] = { class = "ROGUE" }
quests[9081] = { class = "ROGUE" }
quests[9082] = { class = "ROGUE" }
quests[9083] = { class = "ROGUE" }
quests[9084] = { class = "ROGUE" }
quests[9086] = { class = "DRUID" }
quests[9087] = { class = "DRUID" }
quests[9088] = { class = "DRUID" }
quests[9089] = { class = "DRUID" }
quests[9090] = { class = "DRUID" }
quests[9091] = { class = "DRUID" }
quests[9092] = { class = "DRUID" }
quests[9093] = { class = "DRUID" }
quests[9095] = { class = "MAGE" }
quests[9096] = { class = "MAGE" }
quests[9097] = { class = "MAGE" }
quests[9098] = { class = "MAGE" }
quests[9099] = { class = "MAGE" }
quests[9100] = { class = "MAGE" }
quests[9101] = { class = "MAGE" }
quests[9102] = { class = "MAGE" }
quests[9103] = { class = "WARLOCK" }
quests[9104] = { class = "WARLOCK" }
quests[9105] = { class = "WARLOCK" }
quests[9106] = { class = "WARLOCK" }
quests[9107] = { class = "WARLOCK" }
quests[9108] = { class = "WARLOCK" }
quests[9109] = { class = "WARLOCK" }
quests[9110] = { class = "WARLOCK" }
quests[9111] = { class = "PRIEST" }
quests[9112] = { class = "PRIEST" }
quests[9113] = { class = "PRIEST" }
quests[9114] = { class = "PRIEST" }
quests[9115] = { class = "PRIEST" }
quests[9116] = { class = "PRIEST" }
quests[9117] = { class = "PRIEST" }
quests[9118] = { class = "PRIEST" }
quests[9257] = { class = "PRIEST" }
quests[9269] = { class = "DRUID" }
quests[9270] = { class = "MAGE" }
quests[9271] = { class = "WARLOCK" }
quests[9362] = { class = "MAGE" }
quests[9364] = { class = "MAGE", spell = "Polymorph: Pig" }
npcs["Abercrombie"] = { role = "The Hermit" }
npcs["Advisor Belgrum"] = { people = "Dwarf" }
npcs["Aelthalyste"] = { people = "Scourge", role = "Priest Trainer" }
npcs["Ahanu"] = { people = "Tauren", role = "Leather Armor Merchant" }
npcs["Alamar Grimm"] = { people = "Gnome", role = "Warlock Trainer" }
npcs["Alanndarian Nightsong"] = { people = "NightElf" }
npcs["Alchemist Pestlezugg"] = { role = "Alchemy Supplies" }
npcs["Alessandro Luca"] = { people = "Scourge", role = "Blue Moon Odds and Ends" }
npcs["Alexander Calder"] = { people = "Dwarf", role = "Warlock Trainer" }
npcs["Alexi Barov"] = { role = "House of Barov" }
npcs["Alliance Brigadier General"] = { people = "Dwarf" }
npcs["Alyissia"] = { people = "NightElf", role = "Warrior Trainer" }
npcs["Anastasia Hartwell"] = { people = "Scourge", role = "Mage Trainer" }
npcs["Ancestral Spirit"] = { people = "Tauren" }
npcs["Andorgos"] = { role = "Brood of Malygos" }
npcs["Andrew Brownell"] = { people = "Scourge" }
npcs["Andron Gant"] = { people = "Scourge" }
npcs["Angelas Moonbreeze"] = { people = "NightElf" }
npcs["Angus Stern"] = { role = "Head Chef" }
npcs["Anishar"] = { people = "NightElf", role = "Rogue Trainer" }
npcs["Antur Fallow"] = { people = "Tauren" }
npcs["Apothecary Dithers"] = { people = "Scourge" }
npcs["Apothecary Faustin"] = { people = "Scourge", role = "Royal Apothecary Society" }
npcs["Apothecary Helbrim"] = { people = "Scourge" }
npcs["Apothecary Jezel"] = { role = "Purple Lotus Collector" }
npcs["Apothecary Johaan"] = { people = "Scourge", role = "Royal Apothecary Society" }
npcs["Apothecary Lydon"] = { people = "Scourge", role = "Royal Apothecary Society" }
npcs["Apothecary Renferrel"] = { people = "Scourge", role = "Royal Apothecary Society" }
npcs["Apothecary Staffron Lerent"] = { role = "Royal Apothecary Society" }
npcs["Apothecary Zamah"] = { people = "Scourge", role = "Royal Apothecary Society" }
npcs["Apothecary Zinge"] = { people = "Scourge", role = "Royal Apothecary Society" }
npcs["Arantir"] = { role = "The Hand of Chaos" }
npcs["Arathandris Silversky"] = { role = "Emerald Circle" }
npcs["Arch Druid Fandral Staghelm"] = { people = "NightElf" }
npcs["Arch Druid Hamuul Runetotem"] = { people = "Tauren" }
npcs["Archaeologist Flagongut"] = { people = "Dwarf", role = "Explorers' League" }
npcs["Archaeologist Hollee"] = { people = "Dwarf", role = "Explorers' League" }
npcs["Archmage Angela Dosantos"] = { role = "Brotherhood of the Light" }
npcs["Archmage Ansirem Runeweaver"] = { role = "Kirin Tor" }
npcs["Arei"] = { people = "NightElf" }
npcs["Argent Guard Manados"] = { role = "The Argent Dawn" }
npcs["Argent Guard Thaelrid"] = { role = "The Argent Dawn" }
npcs["Argent Officer Garush"] = { role = "The Argent Dawn" }
npcs["Argent Officer Pureheart"] = { role = "The Argent Dawn" }
npcs["Argent Outfitter"] = { role = "The Argent Dawn" }
npcs["Argent Quartermaster"] = { role = "The Argent Dawn" }
npcs["Argent Quartermaster Hasana"] = { role = "The Argent Dawn" }
npcs["Argent Quartermaster Lightspark"] = { role = "The Argent Dawn" }
npcs["Argent Recruiter"] = { role = "The Argent Dawn" }
npcs["Argent Scout"] = { role = "The Argent Dawn" }
npcs["Argos Nightwhisper"] = { people = "NightElf" }
npcs["Arnok"] = { role = "First Aid Trainer" }
npcs["Arthur the Faithful"] = { role = "Paladin Trainer" }
npcs["Artilleryman Sheldonore"] = { people = "Dwarf" }
npcs["Ashlan Stonesmirk"] = { people = "Dwarf" }
npcs["Astarii Starseeker"] = { people = "NightElf", role = "Priest Trainer" }
npcs["Asterion"] = { people = "NightElf" }
npcs["Athridas Bearmantle"] = { people = "NightElf" }
npcs["Auld Stonespire"] = { people = "Tauren" }
npcs["Austil de Mon"] = { people = "Scourge", role = "Warrior Trainer" }
npcs["Ayanna Everstride"] = { people = "NightElf", role = "Hunter Trainer" }
npcs["Azar Stronghammer"] = { people = "Dwarf", role = "Paladin Trainer" }
npcs["Azore Aldamort"] = { role = "The Argent Dawn" }
npcs["Bailor Stonehand"] = { people = "Dwarf" }
npcs["Baine Bloodhoof"] = { people = "Tauren" }
npcs["Balir Frosthammer"] = { people = "Dwarf" }
npcs["Balthule Shadowstrike"] = { people = "NightElf" }
npcs["Baltus Fowler"] = { people = "Scourge", role = "Warrior Trainer" }
npcs["Baros Alexston"] = { role = "City Architect" }
npcs["Barrus"] = { people = "Dwarf", role = "Fishing Promoter" }
npcs["Bartleby"] = { role = "Drunk" }
npcs["Bashana Runetotem"] = { people = "Tauren" }
npcs["Batrider Pele'keiki"] = { role = "Firebloom Collector" }
npcs["Beldin Steelgrill"] = { people = "Dwarf" }
npcs["Belia Thundergranite"] = { people = "Dwarf", role = "Pet Trainer" }
npcs["Bena Winterhoof"] = { people = "Tauren", role = "Expert Alchemist" }
npcs["Beram Skychaser"] = { people = "Tauren", role = "Shaman Trainer" }
npcs["Bethor Iceshard"] = { people = "Scourge" }
npcs["Betina Bigglezink"] = { role = "The Argent Dawn" }
npcs["Bingles Blastenheimer"] = { people = "Dwarf" }
npcs["Bink"] = { people = "Gnome", role = "Mage Trainer" }
npcs["Bloodguard Rawtar"] = { role = "Lean Wolf Steak Collector" }
npcs["Bluff Runner Windstrider"] = { people = "Tauren" }
npcs["Bonnie Stoneflayer"] = { people = "Dwarf", role = "Light Leather Collector" }
npcs["Borgosh Corebender"] = { role = "Weaponsmith" }
npcs["Bounty Hunter Kolark"] = { people = "Tauren" }
npcs["Braenna Flintcrag"] = { people = "Dwarf", role = "Priest Trainer" }
npcs["Brandur Ironhammer"] = { people = "Dwarf", role = "Paladin Trainer" }
npcs["Branstock Khalder"] = { people = "Dwarf", role = "Priest Trainer" }
npcs["Braug Dimspirit"] = { people = "Tauren" }
npcs["Brave Moonhorn"] = { people = "Tauren" }
npcs["Brave Windfeather"] = { people = "Tauren" }
npcs["Brewmeister Bilger"] = { people = "Dwarf" }
npcs["Briarthorn"] = { people = "Gnome", role = "Warlock Trainer" }
npcs["Brock Stoneseeker"] = { people = "Dwarf", role = "Mining Trainer" }
npcs["Brohann Caskbelly"] = { people = "Dwarf", role = "Explorers' League" }
npcs["Bromos Grummner"] = { people = "Dwarf", role = "Paladin Trainer" }
npcs["Brother Anton"] = { role = "Scarlet Crusade Emissary" }
npcs["Brother Crowley"] = { role = "Scarlet Crusade Emissary" }
npcs["Brother Joshua"] = { role = "Priest Trainer" }
npcs["Brother Paxton"] = { role = "Librarian" }
npcs["Brother Sammuel"] = { role = "Paladin Trainer" }
npcs["Brother Wilhelm"] = { role = "Paladin Trainer" }
npcs["Brumn Winterhoof"] = { people = "Tauren", role = "Master Elemental Leatherworker" }
npcs["Bubulo Acerbus"] = { people = "Gnome", role = "Alliance Cloth Quartermaster" }
npcs["Cain Firesong"] = { people = "Scourge", role = "Mage Trainer" }
npcs["Cairne Bloodhoof"] = { people = "Tauren", role = "High Chieftain" }
npcs["Calandrath"] = { role = "Innkeeper" }
npcs["Calvin Montague"] = { people = "Scourge" }
npcs["Canaga Earthcaller"] = { people = "Troll" }
npcs["Captain Blackanvil"] = { role = "Ironforge Brigade Captain" }
npcs["Captain Danuvin"] = { role = "The People's Militia" }
npcs["Captain Rugelfuss"] = { people = "Dwarf" }
npcs["Captain Steelgut"] = { role = "Blackwater Raiders" }
npcs["Captain Stoutfist"] = { people = "Dwarf" }
npcs["Captured Mountaineer"] = { people = "Scourge" }
npcs["Captured Scarlet Zealot"] = { people = "Scourge" }
npcs["Caretaker Alen"] = { role = "The Argent Dawn" }
npcs["Carlin Redpath"] = { role = "The Argent Dawn" }
npcs["Caryssia Moonhunter"] = { people = "NightElf", role = "Tribal Leatherworking Trainer" }
npcs["Catelyn the Blade"] = { role = "Blackwater Raiders" }
npcs["Cerellean Whiteclaw"] = { people = "NightElf" }
npcs["Chemist Cuely"] = { people = "Scourge" }
npcs["Chemist Fuely"] = { people = "Scourge" }
npcs["Chief Archaeologist Greywhisker"] = { people = "Dwarf", role = "Explorers' League" }
npcs["Chief Engineer Bilgewhizzle"] = { role = "Gadgetzan Water Co." }
npcs["Chief Engineer Hinderweir VII"] = { people = "Dwarf" }
npcs["Chief Hawkwind"] = { people = "Tauren" }
npcs["Chief Sharpclaw"] = { role = "Baked Salmon Collector" }
npcs["Christoph Jeffcoat"] = { people = "Scourge", role = "Tradesman" }
npcs["Christoph Walker"] = { people = "Scourge", role = "Warrior Trainer" }
npcs["Chronos"] = { role = "He Who Never Forgets!" }
npcs["Claire Willower"] = { people = "Scourge" }
npcs["Clarice Foster"] = { people = "Scourge" }
npcs["Clavicus Knavingham"] = { role = "Alliance Cloth Quartermaster" }
npcs["Cliffwatcher Longhorn"] = { people = "Tauren" }
npcs["Coleman Farthing"] = { people = "Scourge" }
npcs["Commander Althea Ebonlocke"] = { role = "Leader of The Night Watch" }
npcs["Commander Eligor Dawnbringer"] = { role = "Brotherhood of the Light" }
npcs["Commander Gor'shak"] = { role = "Kargath Expeditionary Force" }
npcs["Commander Thomas Helleran"] = { role = "The Argent Dawn" }
npcs["Connor Rivers"] = { role = "Apprentice Chef" }
npcs["Conservator Ilthalaine"] = { people = "NightElf" }
npcs["Corithras Moonrage"] = { people = "NightElf" }
npcs["Corporal Carnes"] = { role = "Iron Bar Collector" }
npcs["Councilman Millstipe"] = { role = "Council of Darkshire" }
npcs["Count Remington Ridgewell"] = { role = "House of Nobles" }
npcs["Courier Hammerfall"] = { people = "Dwarf" }
npcs["Craftsman Wilhelm"] = { role = "Brotherhood of the Light" }
npcs["Curator Thorius"] = { people = "Dwarf" }
npcs["Dalar Dawnweaver"] = { people = "Scourge" }
npcs["Dame Twinbraid"] = { people = "Dwarf", role = "Thorium Bar Collector" }
npcs["Dannal Stern"] = { people = "Scourge", role = "Warrior Trainer" }
npcs["Darcy"] = { role = "Waitress" }
npcs["Dark Cleric Beryl"] = { people = "Scourge", role = "Priest Trainer" }
npcs["Dark Cleric Duesten"] = { people = "Scourge", role = "Priest Trainer" }
npcs["Darkcaller Yanka"] = { people = "Scourge" }
npcs["Darnassus Commendation Officer"] = { people = "NightElf" }
npcs["Darnath Bladesinger"] = { people = "NightElf", role = "Warrior Trainer" }
npcs["Darren Malvew"] = { role = "Stablehand" }
npcs["Daryl Riknussun"] = { people = "Dwarf", role = "Cooking Trainer" }
npcs["Daryl the Youngling"] = { people = "Dwarf" }
npcs["Daryn Lightwind"] = { people = "NightElf", role = "Cenarion Lore Keeper" }
npcs["David Trias"] = { people = "Scourge", role = "Rogue Trainer" }
npcs["Dawnwatcher Selgorm"] = { role = "The Argent Dawn" }
npcs["Dawnwatcher Shaedlass"] = { role = "The Argent Dawn" }
npcs["Dazalar"] = { people = "NightElf", role = "Hunter Trainer" }
npcs["Deathguard Burgess"] = { people = "Scourge" }
npcs["Deathguard Dillinger"] = { people = "Scourge" }
npcs["Deathguard Humbert"] = { people = "Scourge" }
npcs["Deathguard Linnea"] = { people = "Scourge" }
npcs["Deathguard Podrig"] = { people = "Scourge" }
npcs["Deathguard Samsa"] = { people = "Scourge" }
npcs["Deathguard Simmer"] = { people = "Scourge" }
npcs["Deathstalker Faerleia"] = { people = "Scourge" }
npcs["Deathstalker Lesh"] = { people = "Scourge" }
npcs["Deathstalker Zraedus"] = { people = "Scourge" }
npcs["Deeg"] = { role = "Blackwater Raiders" }
npcs["Deino"] = { role = "Mage Trainer" }
npcs["Demisette Cloyce"] = { role = "Warlock Trainer" }
npcs["Denalan"] = { people = "NightElf" }
npcs["Denatharion"] = { people = "NightElf", role = "Druid Trainer" }
npcs["Derotain Mudsipper"] = { role = "The Thorium Brotherhood" }
npcs["Devrak"] = { role = "Wind Rider Master" }
npcs["Dinita Stonemantle"] = { people = "Dwarf", role = "Vault Administrator" }
npcs["Dink"] = { people = "Gnome", role = "Mage Trainer" }
npcs["Dirania Silvershine"] = { people = "NightElf" }
npcs["Dirge Quikcleave"] = { role = "Butcher" }
npcs["Dispatch Commander Metz"] = { role = "The Argent Dawn" }
npcs["Dizzy One-Eye"] = { role = "Blackwater Raiders" }
npcs["Doc Mixilpixil"] = { people = "Gnome" }
npcs["Doctor Draxlegauge"] = { role = "Blackwater Raiders" }
npcs["Doctor Gregory Victor"] = { people = "Scourge", role = "Trauma Surgeon" }
npcs["Doctor Gustaf VanHowzen"] = { role = "Trauma Surgeon" }
npcs["Doctor Serratus"] = { role = "Rugged Leather Collector" }
npcs["Donyal Tovald"] = { role = "Librarian" }
npcs["Doras"] = { role = "Wind Rider Master" }
npcs["Dorion"] = { people = "NightElf", role = "Hunter Trainer" }
npcs["Dorn Plainstalker"] = { people = "Tauren" }
npcs["Dran Droffers"] = { role = "Droffers and Son Salvage" }
npcs["Drusilla La Salle"] = { role = "Warlock Trainer" }
npcs["Duke Nicholas Zverenhoff"] = { role = "The Argent Dawn" }
npcs["Dungar Longdrink"] = { role = "Gryphon Master" }
npcs["Durnan Furcutter"] = { people = "Dwarf", role = "Cloth & Leather Armor Merchant" }
npcs["Ebru"] = { role = "Disciple of Naralex" }
npcs["Einar Stonegrip"] = { people = "Dwarf" }
npcs["Einris Brightspear"] = { role = "Hunter Trainer" }
npcs["Elanaria"] = { people = "NightElf" }
npcs["Elling Trias"] = { role = "Master of Cheese" }
npcs["Elsharin"] = { role = "Mage Trainer" }
npcs["Elu"] = { people = "Tauren", role = "Wind Rider Apprentice" }
npcs["Enohar Thunderbrew"] = { people = "Dwarf" }
npcs["Enyo"] = { role = "Mage Trainer" }
npcs["Erelas Ambersky"] = { people = "NightElf" }
npcs["Eridan Bluewind"] = { role = "Emerald Circle" }
npcs["Erion Shadewhisper"] = { people = "NightElf", role = "Rogue Trainer" }
npcs["Evonice Sootsmoker"] = { role = "The Thorium Brotherhood" }
npcs["Executor Arren"] = { people = "Scourge" }
npcs["Executor Zygand"] = { people = "Scourge" }
npcs["Exzhal"] = { role = "Servitor of Rastakhan" }
npcs["Fahrad"] = { role = "Grand Master Rogue" }
npcs["Faldreas Goeth'Shael"] = { people = "NightElf" }
npcs["Falfindel Waywarder"] = { people = "NightElf" }
npcs["Falstad Wildhammer"] = { role = "High Thane" }
npcs["Fariel Starsong"] = { role = "Coin of Ancestry Collector" }
npcs["Father Cobb"] = { people = "Scourge", role = "Priest Trainer" }
npcs["Father Inigo Montoy"] = { role = "Brotherhood of the Light" }
npcs["Father Lankester"] = { people = "Scourge", role = "Priest Trainer" }
npcs["Father Lazarus"] = { people = "Scourge", role = "Priest Trainer" }
npcs["Felix Whindlebolt"] = { people = "Gnome" }
npcs["Festival Loremaster"] = { people = "Dwarf" }
npcs["Field Marshal Snowfall"] = { people = "Dwarf", role = "War Effort Commander" }
npcs["Fin Fizracket"] = { role = "Blackwater Raiders" }
npcs["First Mate Crazz"] = { role = "Blackwater Raiders" }
npcs["First Mate Nilzlix"] = { role = "Blackwater Raiders" }
npcs["Fisherman Lin'do"] = { role = "Spotted Yellowtail Collector" }
npcs["Fleet Master Seahorn"] = { role = "Blackwater Raiders" }
npcs["Flint Shadowmore"] = { role = "SI:7" }
npcs["Foggy MacKreel"] = { people = "Dwarf" }
npcs["Foreman Stonebrow"] = { people = "Dwarf", role = "Miners' League" }
npcs["Frahun Shadewhisper"] = { people = "NightElf", role = "Rogue Trainer" }
npcs["Frang"] = { role = "Warrior Trainer" }
npcs["Frostwolf Stable Master"] = { role = "Stable Master" }
npcs["Furmund"] = { people = "Tauren" }
npcs["Fylerian Nightwing"] = { people = "NightElf", role = "Druid Trainer" }
npcs["Gaerolas Talvethren"] = { people = "NightElf" }
npcs["Galamav the Marksman"] = { role = "Kargath Expeditionary Force" }
npcs["Galvan the Ancient"] = { role = "Artisan Blacksmith of the Mithril Order" }
npcs["Gann Stonespire"] = { people = "Tauren" }
npcs["Gart Mistrunner"] = { people = "Tauren", role = "Druid Trainer" }
npcs["Gelkak Gyromast"] = { people = "Dwarf" }
npcs["Gelvas Grimegate"] = { role = "Darkmoon Faire Ticket Redemption" }
npcs["General Marcus Jonathan"] = { role = "High Commander of Stormwind Defense" }
npcs["Gennia Runetotem"] = { people = "Tauren", role = "Druid Trainer" }
npcs["Gerrig Bonegrip"] = { people = "Dwarf" }
npcs["Gershala Nightwhisper"] = { people = "NightElf" }
npcs["Ghak Healtouch"] = { people = "Dwarf", role = "Journeyman Alchemist" }
npcs["Ghede"] = { people = "Tauren" }
npcs["Gilshalan Windwalker"] = { people = "NightElf" }
npcs["Ginro Hearthkindle"] = { people = "NightElf" }
npcs["Glorin Steelbrow"] = { people = "Dwarf" }
npcs["Gnoarn"] = { people = "Dwarf" }
npcs["Gnomeregan Commendation Officer"] = { people = "Gnome" }
npcs["Godrick Farsan"] = { people = "Scourge" }
npcs["Golhine the Hooded"] = { people = "NightElf", role = "Druid Trainer" }
npcs["Goli Krumn"] = { people = "Dwarf" }
npcs["Golnir Bouldertoe"] = { people = "Dwarf", role = "Mining Supplier" }
npcs["Gorbold Steelhand"] = { people = "NightElf", role = "General Trade Supplier" }
npcs["Gordo"] = { people = "Scourge" }
npcs["Gordon Wendham"] = { people = "Scourge", role = "Weapons Merchant" }
npcs["Gracina Spiritmight"] = { people = "NightElf" }
npcs["Graham Van Talen"] = { people = "Scourge", role = "Journeyman Engineer" }
npcs["Grand Mason Marblesten"] = { people = "Dwarf", role = "Royal Stonecutters Union" }
npcs["Granis Swiftaxe"] = { people = "Dwarf", role = "Warrior Trainer" }
npcs["Greatmother Hawkwind"] = { people = "Tauren" }
npcs["Gregor Greystone"] = { role = "The Argent Dawn" }
npcs["Grelin Whitebeard"] = { people = "Dwarf" }
npcs["Greshka"] = { role = "Demon Master" }
npcs["Greta Mosshoof"] = { role = "Emerald Circle" }
npcs["Gretchen Dedmar"] = { people = "Scourge" }
npcs["Grif Wildheart"] = { people = "Dwarf", role = "Hunter Trainer" }
npcs["Grimand Elmore"] = { people = "Dwarf" }
npcs["Grimbooze Thunderbrew"] = { people = "Dwarf" }
npcs["Grimnur Stonebrand"] = { people = "Dwarf", role = "Fishing Trainer" }
npcs["Grinkle"] = { role = "Fishing Promoter" }
npcs["Grish Longrunner"] = { people = "Tauren" }
npcs["Grol'dar"] = { role = "Warlock Trainer" }
npcs["Grull Hawkwind"] = { people = "Tauren" }
npcs["Grumnus Steelshaper"] = { people = "Dwarf", role = "Armor Crafter" }
npcs["Grunt Maug"] = { role = "Tin Bar Collector" }
npcs["Gryan Stoutmantle"] = { role = "The People's Militia" }
npcs["Gryth Thurden"] = { people = "Dwarf", role = "Gryphon Master" }
npcs["Guard Didier"] = { role = "Brotherhood of the Light" }
npcs["Gubber Blump"] = { people = "Dwarf" }
npcs["Gunther Arcanus"] = { people = "Scourge" }
npcs["Gwennyth Bly'Leggonde"] = { people = "NightElf" }
npcs["Hagar Lightninghoof"] = { people = "Tauren" }
npcs["Hammertoe Grez"] = { people = "Dwarf" }
npcs["Hana'zua"] = { people = "Troll" }
npcs["Hank the Hammer"] = { role = "The Mithril Order" }
npcs["Hansel Heavyhands"] = { role = "The Thorium Brotherhood" }
npcs["Harb Clawhoof"] = { people = "Tauren", role = "Kodo Mounts" }
npcs["Harbinger Balthazad"] = { people = "Scourge" }
npcs["Harlo Barnaby"] = { people = "Dwarf" }
npcs["Haromm"] = { role = "Shaman Trainer" }
npcs["Harutt Thunderhorn"] = { people = "Tauren", role = "Warrior Trainer" }
npcs["Haughty Modiste"] = { role = "Fashion Designer" }
npcs["Healer Longrunner"] = { people = "Tauren", role = "Wool Bandage Collector" }
npcs["Hegnar Rumbleshot"] = { people = "Dwarf", role = "Gunsmith" }
npcs["Helendis Riverhorn"] = { people = "NightElf" }
npcs["Heralath Fallowbrook"] = { people = "NightElf" }
npcs["Herald Moonstalker"] = { people = "NightElf" }
npcs["Herbalist Proudfeather"] = { role = "Peacebloom Collector" }
npcs["Hierophant Theodora Mulvadania"] = { role = "Kargath Expeditionary Force" }
npcs["High Executor Darthalia"] = { people = "Scourge" }
npcs["High Executor Hadrec"] = { people = "Scourge" }
npcs["High Explorer Magellas"] = { people = "Dwarf", role = "Explorers' League" }
npcs["High Priest Rohan"] = { role = "Priest Trainer" }
npcs["High Priestess Laurena"] = { role = "Priest Trainer" }
npcs["High Tinker Mekkatorque"] = { role = "King of Gnomes" }
npcs["Highlord Taelan Fordring"] = { role = "Highlord of the Scarlet Crusade" }
npcs["Historian Karnik"] = { people = "Dwarf" }
npcs["Hogral Bakkan"] = { people = "Dwarf", role = "Rogue Trainer" }
npcs["Holt Thunderhorn"] = { people = "Tauren", role = "Hunter Trainer" }
npcs["Huldar"] = { people = "Dwarf" }
npcs["Hulfdan Blackbeard"] = { people = "Dwarf", role = "Rogue Trainer" }
npcs["Huntress Swiftriver"] = { people = "NightElf", role = "Spotted Yellowtail Collector" }
npcs["Huntsman Leopold"] = { role = "The Scarlet Crusade" }
npcs["Huntsman Markhor"] = { role = "Stable Master" }
npcs["Idriana"] = { people = "NightElf", role = "Banker" }
npcs["Illiyana"] = { people = "NightElf" }
npcs["Illiyana Moonblaze"] = { role = "Silverwing Supply Officer" }
npcs["Ilsa Corbin"] = { role = "Warrior Trainer" }
npcs["Impsy"] = { role = "Niby's Minion" }
npcs["Innkeeper Allison"] = { role = "Innkeeper" }
npcs["Innkeeper Farley"] = { role = "Innkeeper" }
npcs["Innkeeper Firebrew"] = { people = "Dwarf", role = "Innkeeper" }
npcs["Innkeeper Grosk"] = { role = "Innkeeper" }
npcs["Innkeeper Gryshka"] = { role = "Innkeeper" }
npcs["Innkeeper Kauth"] = { role = "Innkeeper" }
npcs["Innkeeper Keldamyr"] = { people = "NightElf", role = "Innkeeper" }
npcs["Innkeeper Norman"] = { people = "Scourge", role = "Innkeeper" }
npcs["Innkeeper Pala"] = { people = "Tauren", role = "Innkeeper" }
npcs["Innkeeper Renee"] = { people = "Scourge", role = "Innkeeper" }
npcs["Innkeeper Saelienne"] = { people = "NightElf", role = "Innkeeper" }
npcs["Innkeeper Shyria"] = { people = "NightElf", role = "Innkeeper" }
npcs["Ironforge Commendation Officer"] = { people = "Dwarf" }
npcs["Ironus Coldsteel"] = { people = "Dwarf", role = "Special Weapon Crafter" }
npcs["Isabella"] = { people = "Scourge", role = "Mage Trainer" }
npcs["Iverron"] = { people = "NightElf" }
npcs["Ivy Leafrunner"] = { role = "Emerald Circle" }
npcs["Jahan Hawkwing"] = { role = "Leather & Mail Armor Merchant" }
npcs["Jandria"] = { people = "NightElf", role = "Priest Trainer" }
npcs["Jang"] = { role = "Fishmaster Apprentice" }
npcs["Jangdor Swiftstrider"] = { people = "Tauren", role = "Leatherworking Supplies" }
npcs["Jannok Breezesong"] = { people = "NightElf", role = "Rogue Trainer" }
npcs["Jannos Lighthoof"] = { people = "Tauren", role = "Druid Trainer" }
npcs["Jarkal Mossmeld"] = { people = "Troll" }
npcs["Jaron Stoneshaper"] = { people = "Dwarf", role = "Explorers' League" }
npcs["Jarven Thunderbrew"] = { people = "Dwarf" }
npcs["Je'neu Sancrea"] = { people = "Troll", role = "The Earthen Ring" }
npcs["Jen'shan"] = { people = "Troll", role = "Hunter Trainer" }
npcs["Jenal"] = { people = "NightElf", role = "Ditch Digger" }
npcs["Jennea Cannon"] = { role = "Mage Trainer" }
npcs["Jeremiah Payson"] = { people = "Scourge", role = "Cockroach Vendor" }
npcs["Jern Hornhelm"] = { people = "Dwarf", role = "Explorers' League" }
npcs["Jinar'Zillen"] = { people = "Troll" }
npcs["Jocaste"] = { people = "NightElf", role = "Hunter Trainer" }
npcs["Jorah Annison"] = { people = "Scourge" }
npcs["Jorik Kerridan"] = { role = "Rogue Trainer" }
npcs["Josef Gregorian"] = { people = "Scourge", role = "Artisan Tailor" }
npcs["Jubahl Corpseseeker"] = { people = "Gnome", role = "Demon Trainer" }
npcs["Juli Stormkettle"] = { people = "Gnome", role = "Mage Trainer" }
npcs["Junior Apothecary Holland"] = { people = "Scourge", role = "Royal Apothecary Society" }
npcs["Kaal Soulreaper"] = { people = "Scourge", role = "Warlock Trainer" }
npcs["Kal"] = { people = "NightElf", role = "Druid Trainer" }
npcs["Kali Remik"] = { people = "Troll" }
npcs["Kanati Greycloud"] = { people = "Tauren" }
npcs["Kandrostrasz"] = { role = "Brood of Alexstrasza" }
npcs["Kaplak"] = { role = "Rogue Trainer" }
npcs["Kardris Dreamseeker"] = { role = "Shaman Trainer" }
npcs["Karos Razok"] = { people = "Scourge", role = "Bat Handler" }
npcs["Kartosh"] = { role = "Warlock Trainer" }
npcs["Karus"] = { role = "Banker" }
npcs["Kary Thunderhorn"] = { people = "Tauren", role = "Hunter Trainer" }
npcs["Katie Hunter"] = { role = "Horse Breeder" }
npcs["Katoom the Angler"] = { role = "Fishing Trainer & Supplies" }
npcs["Kaya Flathoof"] = { people = "Tauren" }
npcs["Kaymard Copperpinch"] = { role = "Smokywood Pastures" }
npcs["Kayneth Stillwind"] = { people = "NightElf" }
npcs["Keeper Albagorm"] = { people = "NightElf" }
npcs["Keeper Bel'dugur"] = { people = "Scourge" }
npcs["Keeper Bel'varil"] = { people = "Scourge" }
npcs["Keeper Moonshade"] = { people = "NightElf", role = "Runecloth Bandage Collector" }
npcs["Keeper of the Rolls"] = { role = "The Argent Dawn" }
npcs["Kelek Skykeeper"] = { role = "Emerald Circle" }
npcs["Kelm Hargunth"] = { role = "Warsong Supply Officer" }
npcs["Kelv Sternhammer"] = { people = "Dwarf", role = "Warrior Trainer" }
npcs["Ken'jai"] = { people = "Troll", role = "Priest Trainer" }
npcs["Ken'zigla"] = { people = "Troll" }
npcs["Kerlonian Evershade"] = { people = "NightElf", role = "Druid of the Claw" }
npcs["Kerri Hicks"] = { role = "The Strongest Woman Alive!" }
npcs["Keryn Sylvius"] = { role = "Rogue Trainer" }
npcs["Khelden Bremen"] = { role = "Mage Trainer" }
npcs["Kil'hala"] = { people = "Troll", role = "Journeyman Tailor" }
npcs["Kin'weelay"] = { people = "Troll" }
npcs["King Magni Bronzebeard"] = { people = "Dwarf", role = "Lord of Ironforge" }
npcs["Kirge Sternhorn"] = { people = "Tauren" }
npcs["Klannoc Macleod"] = { role = "The Islander" }
npcs["Klockmort Spannerspan"] = { people = "Gnome" }
npcs["Kor'ghan"] = { people = "Troll" }
npcs["Korfax, Champion of the Light"] = { role = "Brotherhood of the Light" }
npcs["Korran"] = { people = "Troll" }
npcs["Krang Stonehoof"] = { people = "Tauren", role = "Warrior Trainer" }
npcs["Kreldig Ungor"] = { role = "Reclaimers Inc." }
npcs["Krinkle Goodsteel"] = { role = "Blacksmithing Supplies" }
npcs["Krom Stoutarm"] = { people = "Dwarf" }
npcs["Kruban Darkblade"] = { role = "Darkmoon Faire Barker" }
npcs["Krug Skullsplit"] = { role = "Orgrimmar Legion Captain" }
npcs["Kuray'bin"] = { people = "Troll" }
npcs["Kurgul"] = { role = "Demon Trainer" }
npcs["Kyra Windblade"] = { people = "NightElf", role = "Warrior Trainer" }
npcs["Lady Callow"] = { role = "Mageweave Bandage Collector" }
npcs["Lady Jaina Proudmoore"] = { role = "Ruler of Theramore" }
npcs["Lady Sylvanas Windrunner"] = { role = "Banshee Queen" }
npcs["Lago Blackwrench"] = { people = "Gnome" }
npcs["Laird"] = { people = "NightElf", role = "Fish Vendor" }
npcs["Lakota Windsong"] = { people = "Tauren" }
npcs["Lanka Farshot"] = { people = "Tauren", role = "Hunter Trainer" }
npcs["Lar Prowltusk"] = { people = "Troll" }
npcs["Lard"] = { role = "Innkeeper" }
npcs["Lariia"] = { people = "NightElf", role = "Priest Trainer" }
npcs["Latronicus Moonspear"] = { people = "NightElf" }
npcs["Laurna Morninglight"] = { people = "NightElf", role = "Priest Trainer" }
npcs["Layo Starstrike"] = { role = "The Cenarion Circle" }
npcs["Lelanai"] = { people = "NightElf", role = "Saber Handler" }
npcs["Leonid Barthalomew the Revered"] = { role = "The Argent Dawn" }
npcs["Lexlort"] = { role = "Kargath Expeditionary Force" }
npcs["Librarian Mae Paledust"] = { people = "Dwarf", role = "Explorers' League" }
npcs["Lieutenant Beitha"] = { role = "The Argent Dawn" }
npcs["Lieutenant Dagel"] = { role = "The Argent Dawn" }
npcs["Lieutenant Lisande"] = { role = "The Argent Dawn" }
npcs["Lieutenant Nevell"] = { role = "The Argent Dawn" }
npcs["Lieutenant Orrin"] = { role = "The Argent Dawn" }
npcs["Lieutenant Rotimer"] = { role = "Stormpike Guard Recruitment Officer" }
npcs["Lieutenant Rukag"] = { role = "The Argent Dawn" }
npcs["Liladris Moonriver"] = { people = "NightElf" }
npcs["Lilliam Sparkspindle"] = { people = "Gnome", role = "Expert Engineer" }
npcs["Liv Rizzlefix"] = { role = "Workshop Assistant" }
npcs["Llane Beshere"] = { role = "Warrior Trainer" }
npcs["Loganaar"] = { role = "Druid Trainer" }
npcs["Lokhtos Darkbargainer"] = { role = "The Thorium Brotherhood" }
npcs["Lolo the Lookout"] = { role = "Blackwater Raiders" }
npcs["Lomac Gearstrip"] = { people = "Gnome" }
npcs["Longbraid the Grim"] = { people = "Dwarf" }
npcs["Lookout Captain Lolo Longstriker"] = { role = "The Thorium Brotherhood" }
npcs["Lord Baurles K. Wishock"] = { role = "House of Nobles" }
npcs["Lord Ello Ebonlocke"] = { role = "Mayor of Darkshire" }
npcs["Lord Grayson Shadowbreaker"] = { role = "Paladin Trainer" }
npcs["Lord Jorach Ravenholdt"] = { role = "Lord of the Assassin's League" }
npcs["Lord Maxwell Tyrosus"] = { role = "The Argent Dawn" }
npcs["Lord Tirion Fordring"] = { role = "Order of the Silver Hand" }
npcs["Lord Tony Romano"] = { role = "Rogue Trainer" }
npcs["Lorekeeper Raintotem"] = { people = "Tauren" }
npcs["Loslor Rudge"] = { people = "Dwarf", role = "Engineering Supplies" }
npcs["Lotherias"] = { people = "NightElf" }
npcs["Lucius"] = { people = "Dwarf" }
npcs["Lumak"] = { role = "Fishing Trainer" }
npcs["Luther Pickman"] = { people = "Scourge", role = "Warlock Trainer" }
npcs["Lyria Du Lac"] = { role = "Warrior Trainer" }
npcs["Magatha Grimtotem"] = { people = "Tauren", role = "Elder Crone" }
npcs["Maggran Earthbinder"] = { people = "Tauren" }
npcs["Magis Sparkmantle"] = { people = "Gnome", role = "Mage Trainer" }
npcs["Magistrate Bluntnose"] = { people = "Dwarf" }
npcs["Magistrate Sevren"] = { people = "Scourge" }
npcs["Magmar Fellhew"] = { people = "Dwarf" }
npcs["Magus Wordeen Voidglare"] = { people = "Scourge" }
npcs["Mai'Lahii"] = { people = "Troll", role = "Fishing Supplies" }
npcs["Mai'ah"] = { people = "Troll", role = "Mage Trainer" }
npcs["Major Samuelson"] = { role = "Stormwind City Guard" }
npcs["Makaba Flathoof"] = { people = "Tauren" }
npcs["Malakai Cross"] = { people = "Scourge", role = "Priest Trainer" }
npcs["Malton Droffers"] = { role = "Droffers and Son Salvage" }
npcs["Malyfous Darkhammer"] = { role = "The Thorium Brotherhood" }
npcs["Mardant Strongoak"] = { people = "NightElf", role = "Druid Trainer" }
npcs["Marek Ironheart"] = { people = "Dwarf" }
npcs["Marion Call"] = { people = "Scourge", role = "Rogue Trainer" }
npcs["Marleth Barleybrew"] = { people = "Dwarf" }
npcs["Marryk Nurribit"] = { people = "Gnome", role = "Mage Trainer" }
npcs["Marshal Bluewall"] = { people = "Dwarf" }
npcs["Marta Finespindle"] = { people = "Gnome", role = "Thick Leather Collector" }
npcs["Marukai"] = { people = "Troll" }
npcs["Master Apothecary Faranell"] = { people = "Scourge", role = "Royal Apothecary Society" }
npcs["Master Gadrin"] = { people = "Troll" }
npcs["Master Mathias Shaw"] = { role = "Leader of SI:7" }
npcs["Master Mechanic Castpipe"] = { people = "Gnome" }
npcs["Master Nightsong"] = { people = "NightElf", role = "Purple Lotus Collector" }
npcs["Master Sergeant Fizzlebolt"] = { people = "Gnome", role = "War Effort Recruiter" }
npcs["Master Sergeant Maclure"] = { role = "War Effort Recruiter" }
npcs["Master Sergeant Moonshadow"] = { people = "NightElf", role = "War Effort Recruiter" }
npcs["Master Smith Burninate"] = { role = "The Thorium Brotherhood" }
npcs["Master Vornal"] = { people = "Troll" }
npcs["Mataus the Wrathcaster"] = { role = "The Scarlet Crusade" }
npcs["Mathiel"] = { people = "NightElf" }
npcs["Mathrengyl Bearwalker"] = { people = "NightElf", role = "Druid Trainer" }
npcs["Maur Raincaller"] = { people = "Tauren" }
npcs["Maurin Bonesplitter"] = { people = "Scourge" }
npcs["Maxan Anvol"] = { people = "Dwarf", role = "Priest Trainer" }
npcs["Maximillion"] = { people = "Scourge", role = "Warlock Trainer" }
npcs["Maybess Riverbreeze"] = { role = "Emerald Circle" }
npcs["Mazen Mac'Nadir"] = { role = "Academy of Arcane Arts and Sciences" }
npcs["McGavan"] = { role = "The Mithril Order" }
npcs["Meela Dawnstrider"] = { people = "Tauren", role = "Shaman Trainer" }
npcs["Melisara"] = { people = "Scourge" }
npcs["Melithar Staghelm"] = { people = "NightElf" }
npcs["Melnan Darkstone"] = { role = "Darkmoon Faire Barker" }
npcs["Mennet Carkad"] = { people = "Scourge" }
npcs["Merideth Carlson"] = { role = "Horse Breeder" }
npcs["Merrin Rockweaver"] = { people = "Dwarf", role = "Explorers' League" }
npcs["Michael Garrett"] = { people = "Scourge", role = "Bat Handler" }
npcs["Mikhail"] = { role = "Bartender" }
npcs["Miles Dexter"] = { people = "Scourge", role = "Rogue Trainer" }
npcs["Miles Welsh"] = { people = "Scourge", role = "Priest Trainer" }
npcs["Milli Featherwhistle"] = { people = "Gnome", role = "Mechanostrider Merchant" }
npcs["Milton Sheaf"] = { role = "Librarian" }
npcs["Miner Cromwell"] = { role = "Copper Bar Collector" }
npcs["Mirket"] = { role = "Warlock Trainer" }
npcs["Mist"] = { people = "NightElf" }
npcs["Mistina Steelshield"] = { people = "Dwarf", role = "Alliance Cloth Quartermaster" }
npcs["Mitsuwa"] = { people = "Troll" }
npcs["Molthor"] = { role = "Hand of Rastakhan" }
npcs["Monika Sengutz"] = { people = "Scourge" }
npcs["Monty"] = { people = "Dwarf", role = "Rat Extermination Specialist" }
npcs["Moon Priestess Amara"] = { people = "NightElf" }
npcs["Mor'rogal"] = { people = "Tauren" }
npcs["Morin Cloudstalker"] = { people = "Tauren" }
npcs["Motega Firemane"] = { people = "Tauren" }
npcs["Motley Garmason"] = { people = "Dwarf" }
npcs["Mountaineer Barleybrew"] = { people = "Dwarf" }
npcs["Mountaineer Cobbleflint"] = { people = "Dwarf" }
npcs["Mountaineer Gravelgaw"] = { people = "Dwarf" }
npcs["Mountaineer Kadrell"] = { people = "Dwarf" }
npcs["Mountaineer Pebblebitty"] = { people = "Dwarf" }
npcs["Mountaineer Rockgar"] = { people = "Dwarf" }
npcs["Mountaineer Stormpike"] = { people = "Dwarf" }
npcs["Mountaineer Thalos"] = { people = "Dwarf" }
npcs["Mountaineer Wallbang"] = { people = "Dwarf" }
npcs["Muiredon Battleforge"] = { people = "Dwarf" }
npcs["Mull Thunderhorn"] = { people = "Tauren" }
npcs["Mura Runetotem"] = { people = "Tauren" }
npcs["Muren Stormpike"] = { people = "Dwarf" }
npcs["Mydrannul"] = { people = "NightElf", role = "General Goods Vendor" }
npcs["Mystic Yayo'jin"] = { role = "Reagent Vendor" }
npcs["Nalpak"] = { role = "Disciple of Naralex" }
npcs["Nara Meideros"] = { people = "NightElf", role = "Priest Trainer" }
npcs["Nardstrum Copperpinch"] = { role = "Smokywood Pastures" }
npcs["Narm Skychaser"] = { people = "Tauren", role = "Shaman Trainer" }
npcs["Nartok"] = { role = "Warlock Trainer" }
npcs["Nataka Longhorn"] = { people = "Tauren" }
npcs["Nathanos Blightcaller"] = { role = "Champion of the Banshee Queen" }
npcs["Nazgrel"] = { role = "Advisor to Thrall" }
npcs["Nessa Shadowsong"] = { people = "NightElf", role = "Fishing Supplies" }
npcs["Nimboya"] = { people = "Troll" }
npcs["Nipsy"] = { people = "Dwarf" }
npcs["Nissa Firestone"] = { people = "Dwarf", role = "First Aid Trainer" }
npcs["Nixx Sprocketspring"] = { role = "Master Goblin Engineer" }
npcs["Nogg"] = { role = "Expert Engineer" }
npcs["Nori Pridedrift"] = { people = "Dwarf" }
npcs["Novice Elreth"] = { people = "Scourge" }
npcs["Novice Thaivand"] = { people = "Scourge" }
npcs["Nurse Stonefield"] = { role = "Silk Bandage Collector" }
npcs["Nyrill"] = { role = "Xylem's Apprentice" }
npcs["Oben Rageclaw"] = { people = "NightElf" }
npcs["Officer Gothena"] = { people = "Scourge", role = "Undercity Commendations" }
npcs["Officer Ironbeard"] = { people = "Dwarf", role = "Ironforge Commendations" }
npcs["Officer Lunalight"] = { people = "NightElf", role = "Darnassus Commendations" }
npcs["Officer Maloof"] = { role = "Stormwind Commendations" }
npcs["Officer Porterhouse"] = { people = "Gnome", role = "Gnomeregan Commendations" }
npcs["Officer Redblade"] = { role = "Orgrimmar Commendations" }
npcs["Officer Thunderstrider"] = { people = "Tauren", role = "Thunder Bluff Commendations" }
npcs["Officer Vu'Shalay"] = { people = "Troll", role = "Darkspear Commendations" }
npcs["Oglethorpe Obnoticus"] = { role = "Master Gnome Engineer" }
npcs["Ogunaro Wolfrunner"] = { role = "Kennel Master" }
npcs["Okothos Ironrager"] = { role = "Armorsmith" }
npcs["Olmin Burningbeard"] = { people = "Dwarf", role = "Hunter Trainer" }
npcs["Onin MacHammar"] = { people = "Dwarf" }
npcs["Onu"] = { role = "Ancient of Lore" }
npcs["Oralius"] = { people = "Dwarf" }
npcs["Oran Snakewrithe"] = { people = "Scourge" }
npcs["Orendil Broadleaf"] = { people = "NightElf" }
npcs["Orenthil Whisperwind"] = { people = "NightElf" }
npcs["Ormak Grimshot"] = { role = "Hunter Trainer" }
npcs["Ormer Ironbraid"] = { people = "Dwarf" }
npcs["Ormok"] = { role = "Rogue Trainer" }
npcs["Ormyr Flinteye"] = { people = "Dwarf", role = "Rogue Trainer" }
npcs["Osric Strang"] = { role = "Heavy Armor Merchant" }
npcs["Otho Moji'ko"] = { role = "Cooking Supplier" }
npcs["Overseer Oilfist"] = { role = "The Thorium Brotherhood" }
npcs["Ox"] = { people = "Tauren", role = "The Mithril Order" }
npcs["Ozzie Togglevolt"] = { people = "Gnome" }
npcs["Packmaster Stonebruiser"] = { role = "Brotherhood of the Light" }
npcs["Pao'ka Swiftmountain"] = { people = "Tauren" }
npcs["Parqual Fintallas"] = { people = "Scourge" }
npcs["Patrick Garrett"] = { people = "Scourge" }
npcs["Peter Galen"] = { role = "Master Dragonscale Leatherworker" }
npcs["Pierce Shackleton"] = { people = "Scourge", role = "Mage Trainer" }
npcs["Pilot Bellowfiz"] = { people = "Dwarf" }
npcs["Pilot Hammerfoot"] = { people = "Dwarf" }
npcs["Pilot Longbeard"] = { people = "Dwarf", role = "Ironforge Siege Brigade" }
npcs["Pilot Stonegear"] = { people = "Dwarf" }
npcs["Piznik"] = { role = "Venture Co." }
npcs["Porthannius"] = { people = "NightElf" }
npcs["Pratt McGrubben"] = { role = "Leatherworking Supplies" }
npcs["Priestess A'moora"] = { people = "NightElf" }
npcs["Priestess Alathea"] = { role = "Priest Trainer" }
npcs["Priestess Anetta"] = { role = "Priest Trainer" }
npcs["Priestess Josetta"] = { role = "Priest Trainer" }
npcs["Princess Moira Bronzebeard"] = { role = "Princess of Ironforge" }
npcs["Private Draxlegauge"] = { people = "Gnome", role = "Stranglekelp Collector" }
npcs["Private Porter"] = { role = "Medium Leather Collector" }
npcs["Professor Phizzlethorpe"] = { role = "Blackwater Raiders" }
npcs["Professor Thaddeus Paleo"] = { role = "Darkmoon Faire Cards & Exotic Goods" }
npcs["Prospector Ironband"] = { people = "Dwarf" }
npcs["Prospector Remtravel"] = { people = "Dwarf", role = "Explorers' League" }
npcs["Prospector Ryedol"] = { people = "Dwarf", role = "Explorers' League" }
npcs["Prospector Stormpike"] = { people = "Dwarf" }
npcs["Prospector Whelgar"] = { people = "Dwarf", role = "Explorers' League" }
npcs["Quartermaster Lewis"] = { role = "Quartermaster" }
npcs["Quartermaster Miranda Breechlock"] = { role = "The Argent Dawn" }
npcs["Quentin"] = { people = "NightElf" }
npcs["Quinn Yorick"] = { people = "Scourge", role = "Deathstalker" }
npcs["Quintis Jonespyre"] = { people = "NightElf" }
npcs["Raedon Duskstriker"] = { people = "NightElf", role = "Alliance Cloth Quartermaster" }
npcs["Ragnar Thunderbrew"] = { people = "Dwarf" }
npcs["Rahauro"] = { people = "Tauren", role = "Magatha's Servant" }
npcs["Raleigh Andrean"] = { people = "Scourge", role = "Ex-Chef" }
npcs["Ralston Farnsley"] = { people = "Scourge", role = "Horde Cloth Quartermaster" }
npcs["Rane Yorick"] = { people = "Scourge", role = "Deathstalker" }
npcs["Ranshalla"] = { people = "NightElf" }
npcs["Rashona Straglash"] = { role = "Horde Cloth Quartermaster" }
npcs["Rau Cliffrunner"] = { people = "Tauren" }
npcs["Ravenholdt Guard"] = { role = "Assassin's League" }
npcs["Rayne"] = { role = "Cenarion Circle" }
npcs["Razzle Sprysprocket"] = { people = "Gnome" }
npcs["Regnus Thundergranite"] = { people = "Dwarf", role = "Hunter Trainer" }
npcs["Rejold Barleybrew"] = { people = "Dwarf" }
npcs["Rellian Greenspyre"] = { people = "NightElf" }
npcs["Renzik \"The Shiv\""] = { role = "SI:7 Operative" }
npcs["Rexxar"] = { role = "Champion of the Horde" }
npcs["Rezlak"] = { role = "Tinkers' Union" }
npcs["Rhag Garmason"] = { people = "Dwarf" }
npcs["Rhinag"] = { people = "Troll" }
npcs["Richard Kerwin"] = { people = "Scourge", role = "Warlock Trainer" }
npcs["Riggle Bassbait"] = { role = "Fishmaster" }
npcs["Rimblat Earthshatter"] = { role = "The Earthen Ring" }
npcs["Rin'ji"] = { people = "Troll", role = "Witherbark Troll" }
npcs["Rin'wosho the Trader"] = { role = "Zandalar Supplies and Repair" }
npcs["Rivern Frostwind"] = { role = "Wintersaber Trainers" }
npcs["Roetten Stonehammer"] = { role = "Reclaimers Inc." }
npcs["Rohan the Assassin"] = { role = "The Scarlet Crusade" }
npcs["Royal Factor Bathrilor"] = { role = "Stormwind Census" }
npcs["Royal Historian Archesonus"] = { people = "Dwarf" }
npcs["Royal Overseer Bauhaus"] = { people = "Scourge", role = "Undercity Census" }
npcs["Rudra Amberstill"] = { people = "Dwarf" }
npcs["Rumstag Proudstrider"] = { people = "Tauren", role = "Horde Cloth Quartermaster" }
npcs["Rutherford Twing"] = { role = "Defilers Supply Officer" }
npcs["Ruul Eagletalon"] = { people = "Tauren" }
npcs["Rwag"] = { role = "Rogue Trainer" }
npcs["Sage Korolusk"] = { people = "Tauren" }
npcs["Sage Truthseeker"] = { people = "Tauren" }
npcs["Sagorne Creststrider"] = { people = "Tauren", role = "Shaman Trainer" }
npcs["Samuel Hawke"] = { role = "League of Arathor Supply Officer" }
npcs["Sandahl"] = { role = "Warlock Trainer" }
npcs["Sara Balloo"] = { people = "Dwarf" }
npcs["Sarah Sadwhistle"] = { people = "Gnome", role = "Roast Raptor Collector" }
npcs["Sarah Tanner"] = { role = "Master Elemental Leatherworker" }
npcs["Scholar Runethorn"] = { people = "NightElf" }
npcs["Scooty"] = { role = "Chief Engineer" }
npcs["Scout Galiaan"] = { role = "The People's Militia" }
npcs["Scout Riell"] = { role = "The People's Militia" }
npcs["Se'Jib"] = { role = "Master Tribal Leatherworker" }
npcs["Searn Firewarder"] = { people = "Troll" }
npcs["Security Chief Bilgewhizzle"] = { role = "Water Co. Security" }
npcs["Seer Graytongue"] = { people = "Tauren" }
npcs["Seer Ravenfeather"] = { people = "Tauren" }
npcs["Seer Wiserunner"] = { people = "Tauren" }
npcs["Senani Thunderheart"] = { people = "Tauren" }
npcs["Senator Barin Redstone"] = { people = "Dwarf" }
npcs["Senator Mehr Stonehallow"] = { people = "Dwarf" }
npcs["Senior Sergeant Grimsford"] = { people = "Scourge", role = "War Effort Recruiter" }
npcs["Senior Sergeant Kai'jin"] = { people = "Troll", role = "War Effort Recruiter" }
npcs["Senior Sergeant T'kelah"] = { role = "Mithril Bar Collector" }
npcs["Senior Sergeant Taiga"] = { people = "Tauren", role = "War Effort Recruiter" }
npcs["Senior Surveyor Fizzledowser"] = { role = "Gadgetzan Water Co." }
npcs["Senir Whitebeard"] = { people = "Dwarf" }
npcs["Sentinel Arynia Cloudsbreak"] = { people = "NightElf" }
npcs["Sentinel Elissa Starbreeze"] = { people = "NightElf" }
npcs["Sentinel Glynda Nal'Shea"] = { people = "NightElf" }
npcs["Sentinel Melyria Frostshadow"] = { people = "NightElf" }
npcs["Sentinel Selarin"] = { people = "NightElf" }
npcs["Sentinel Silversky"] = { people = "NightElf", role = "Linen Bandage Collector" }
npcs["Sentinel Thenysil"] = { people = "NightElf" }
npcs["Sentinel Tysha Moonblade"] = { people = "NightElf" }
npcs["Sentinel Velene Starstrike"] = { people = "NightElf" }
npcs["Serge Hinott"] = { people = "Scourge", role = "Expert Alchemist" }
npcs["Sergeant Major Germaine"] = { role = "Arthas' Tears Collector" }
npcs["Sergeant Stonebrow"] = { people = "Dwarf", role = "Copper Bar Collector" }
npcs["Sergeant Umala"] = { role = "Thick Leather Collector" }
npcs["Shadow Priest Allister"] = { people = "Scourge" }
npcs["Shadow Priest Sarvis"] = { people = "Scourge" }
npcs["Shadow Priestess Vandis"] = { people = "Scourge" }
npcs["Shadowmage Vivian Lagrave"] = { role = "Kargath Expeditionary Force" }
npcs["Shael'dryn"] = { people = "NightElf" }
npcs["Shakes O'Breen"] = { role = "Blackwater Raiders" }
npcs["Shanda"] = { people = "NightElf", role = "Priest Trainer" }
npcs["Shandris Feathermoon"] = { people = "NightElf", role = "General of the Sentinel Army" }
npcs["Sharlindra"] = { people = "Scourge" }
npcs["Shay Leafrunner"] = { people = "NightElf" }
npcs["Sheal Runetotem"] = { people = "Tauren", role = "Druid Trainer" }
npcs["Sheldras Moontree"] = { role = "Druid Trainer" }
npcs["Shenthul"] = { people = "Troll", role = "Rogue Trainer" }
npcs["Shikrik"] = { role = "Shaman Trainer" }
npcs["Shindrell Swiftfire"] = { people = "NightElf" }
npcs["Shoni the Shilent"] = { people = "Dwarf" }
npcs["Sian'dur"] = { role = "Hunter Trainer" }
npcs["Sian'tsu"] = { role = "Shaman Trainer" }
npcs["Sida"] = { people = "Dwarf" }
npcs["Sigrun Ironhew"] = { people = "Dwarf" }
npcs["Siln Skychaser"] = { people = "Tauren", role = "Shaman Trainer" }
npcs["Sirra Von'Indi"] = { role = "Historian of Darkshire" }
npcs["Sister Aquinne"] = { people = "NightElf", role = "Novice Priestess" }
npcs["Skinner Jamani"] = { role = "Heavy Leather Collector" }
npcs["Skorn Whitecloud"] = { people = "Tauren" }
npcs["Skuerto"] = { people = "Dwarf" }
npcs["Slicky Gastronome"] = { people = "Gnome", role = "Rainbow Fin Albacore Collector" }
npcs["Smith Argus"] = { role = "Journeyman Blacksmith" }
npcs["Smith Slagtree"] = { role = "Blacksmithing Supplies" }
npcs["Solm Hargrin"] = { people = "Dwarf", role = "Rogue Trainer" }
npcs["Sorek"] = { role = "Warrior Trainer" }
npcs["Sovik"] = { role = "Engineering Supplies" }
npcs["Spackle Thornberry"] = { people = "Gnome", role = "Demon Trainer" }
npcs["Spigot Operator Luglunket"] = { role = "Gadgetzan Water Co." }
npcs["Springspindle Fizzlegear"] = { people = "Dwarf", role = "Artisan Engineer" }
npcs["Sputtervalve"] = { role = "Tinkers' Union" }
npcs["Sten Stoutarm"] = { people = "Dwarf" }
npcs["Stomper Kreeg"] = { role = "The Drunk" }
npcs["Stoneguard Clayhoof"] = { role = "Runecloth Bandage Collector" }
npcs["Stormpike Stable Master"] = { role = "Stable Master" }
npcs["Swart"] = { role = "Shaman Trainer" }
npcs["Syral Bladeleaf"] = { people = "NightElf" }
npcs["Syurna"] = { people = "NightElf", role = "Rogue Trainer" }
npcs["Tai'jin"] = { people = "Troll", role = "Priest Trainer" }
npcs["Taiga Wisemane"] = { people = "Tauren" }
npcs["Tal"] = { people = "Tauren", role = "Wind Rider Master" }
npcs["Talen"] = { people = "NightElf" }
npcs["Talendria"] = { people = "NightElf" }
npcs["Talin Keeneye"] = { people = "Dwarf" }
npcs["Tallonkai Swiftroot"] = { people = "NightElf" }
npcs["Tallow"] = { people = "Scourge" }
npcs["Talo Thornhoof"] = { people = "Tauren" }
npcs["Talvash del Kissel"] = { people = "Gnome" }
npcs["Tammra Windfield"] = { people = "Tauren" }
npcs["Tannok Frosthammer"] = { people = "Dwarf", role = "Innkeeper Assistant" }
npcs["Tannysa"] = { role = "Herbalism Trainer" }
npcs["Tarindrella"] = { people = "NightElf" }
npcs["Taronn Redfeather"] = { role = "Emerald Circle" }
npcs["Tarrel Rockweaver"] = { people = "Dwarf" }
npcs["Tarshaw Jaggedscar"] = { role = "Warrior Trainer" }
npcs["Taskmaster Scrange"] = { role = "The Thorium Brotherhood" }
npcs["Telonis"] = { people = "NightElf", role = "Artisan Leatherworker" }
npcs["Tenaron Stormgrip"] = { people = "NightElf" }
npcs["Terenthis"] = { people = "NightElf" }
npcs["Teronis' Corpse"] = { people = "NightElf" }
npcs["Thadius Grimshade"] = { people = "Dwarf" }
npcs["Thal'trak Proudtusk"] = { role = "Kargath Expeditionary Force" }
npcs["Thalia Amberhide"] = { people = "Tauren" }
npcs["Tharek Blackstone"] = { people = "Dwarf" }
npcs["Tharnariun Treetender"] = { people = "NightElf" }
npcs["Theocritus"] = { role = "Mage of Tower Azora" }
npcs["Theodrus Frostbeard"] = { people = "Dwarf", role = "Priest Trainer" }
npcs["Theridran"] = { people = "NightElf", role = "Druid Trainer" }
npcs["Thersa Windsong"] = { people = "Tauren" }
npcs["Thistleheart"] = { people = "Dwarf", role = "Warlock Trainer" }
npcs["Thomas"] = { role = "Altar Boy" }
npcs["Thor"] = { role = "Gryphon Master" }
npcs["Thorgas Grimson"] = { people = "Dwarf", role = "Hunter Trainer" }
npcs["Thorgrum Borrelson"] = { people = "Dwarf", role = "Gryphon Master" }
npcs["Thorkaf Dragoneye"] = { role = "Master Dragonscale Leatherworker" }
npcs["Thotar"] = { role = "Hunter Trainer" }
npcs["Thrall"] = { role = "Warchief" }
npcs["Thran Khorman"] = { people = "Dwarf", role = "Warrior Trainer" }
npcs["Thunderheart"] = { role = "Kargath Expeditionary Force" }
npcs["Thundris Windweaver"] = { people = "NightElf" }
npcs["Thurston Xane"] = { people = "Scourge", role = "Mage Trainer" }
npcs["Thyn'tel Bladeweaver"] = { people = "NightElf" }
npcs["Tigor Skychaser"] = { people = "Tauren", role = "Shaman Trainer" }
npcs["Tinkerwiz"] = { role = "Journeyman Engineer" }
npcs["Tinkmaster Overspark"] = { role = "Master Gnome Engineer" }
npcs["Tiza Battleforge"] = { people = "Dwarf" }
npcs["Toldren Deepiron"] = { people = "Dwarf", role = "Priest Trainer" }
npcs["Tonga Runetotem"] = { people = "Tauren" }
npcs["Tor'gan"] = { people = "Troll" }
npcs["Torm Ragetotem"] = { people = "Tauren", role = "Warrior Trainer" }
npcs["Tormus Deepforge"] = { people = "Dwarf" }
npcs["Trenton Lighthammer"] = { role = "The Mithril Order" }
npcs["Treshala Fallowbrook"] = { people = "NightElf" }
npcs["Troyas Moonbreeze"] = { people = "NightElf" }
npcs["Tundra MacGrann"] = { people = "Dwarf" }
npcs["Turak Runetotem"] = { people = "Tauren", role = "Druid Trainer" }
npcs["Tyrande Whisperwind"] = { role = "High Priestess of Elune" }
npcs["Ula'elek"] = { people = "Troll" }
npcs["Ulfir Ironbeard"] = { role = "Hunter Trainer" }
npcs["Umpi"] = { people = "Scourge" }
npcs["Un'Thuwa"] = { people = "Troll", role = "Mage Trainer" }
npcs["Una"] = { people = "Tauren", role = "Artisan Leatherworker" }
npcs["Undertaker Mordo"] = { people = "Scourge" }
npcs["Ur'kyo"] = { role = "Priest Trainer" }
npcs["Ursula Deline"] = { role = "Warlock Trainer" }
npcs["Ursyn Ghull"] = { people = "Scourge", role = "Mage Trainer" }
npcs["Uthel'nay"] = { people = "Troll", role = "Mage Trainer" }
npcs["Valadar Starsong"] = { role = "Coin of Ancestry Collector" }
npcs["Valstag Ironjaw"] = { people = "Dwarf" }
npcs["Vargus"] = { role = "Blacksmith" }
npcs["Varimathras"] = { people = "Scourge" }
npcs["Vark Battlescar"] = { people = "Tauren" }
npcs["Vazario Linkgrease"] = { role = "Master Goblin Engineer" }
npcs["Vehena"] = { people = "Troll", role = "Horde Cloth Quartermaster" }
npcs["Vel'rin Fang"] = { people = "Troll" }
npcs["Velora Nitely"] = { people = "Scourge" }
npcs["Veren Tallstrider"] = { people = "Tauren" }
npcs["Veron Amberstill"] = { people = "Dwarf", role = "Ram Breeder" }
npcs["Vesprystus"] = { people = "NightElf", role = "Hippogryph Master" }
npcs["Vestia Moonspear"] = { people = "NightElf" }
npcs["Vethsera"] = { role = "Brood of Ysera" }
npcs["Vidra Hearthstove"] = { people = "Dwarf" }
npcs["Vinchaxa"] = { role = "Servitor of Zanza" }
npcs["Vish Kozus"] = { role = "Captain of the Guard" }
npcs["Vizzklick"] = { role = "Tailoring Supplies" }
npcs["Vorn Skyseer"] = { people = "Tauren" }
npcs["Vorrel Sengutz"] = { people = "Scourge" }
npcs["Wagner Hammerstrike"] = { people = "Dwarf" }
npcs["Warlord Gorchuk"] = { people = "Tauren", role = "War Effort Commander" }
npcs["Warlord Goretooth"] = { role = "Kargath Expeditionary Force" }
npcs["Warosh"] = { role = "The Cursed" }
npcs["Watcher Backus"] = { role = "The Night Watch" }
npcs["Watcher Dodds"] = { role = "The Night Watch" }
npcs["Watcher Ladimore"] = { role = "The Night Watch" }
npcs["Weldon Barov"] = { role = "House of Barov" }
npcs["Whiskey Slim"] = { role = "Blackwater Raiders" }
npcs["Whulwert Copperpinch"] = { role = "Smokywood Pastures" }
npcs["Wilder Thistlenettle"] = { people = "Dwarf" }
npcs["Willow"] = { role = "Twilight's Hammer" }
npcs["Winna Hazzard"] = { people = "Scourge" }
npcs["Wizlo Bearingshiner"] = { people = "Tauren" }
npcs["Wonderform Operator"] = { role = "Smokywood Pastures" }
npcs["Wu Shen"] = { role = "Warrior Trainer" }
npcs["Wulmort Jinglepocket"] = { role = "Smokywood Pastures" }
npcs["Wynd Nightchaser"] = { people = "NightElf" }
npcs["Wynne Larson"] = { role = "Robe Merchant" }
npcs["X'yera"] = { role = "Priest Trainer" }
npcs["Xanis Flameweaver"] = { people = "Tauren" }
npcs["Xiggs Fuselighter"] = { people = "Dwarf" }
npcs["Xizk Goodstitch"] = { role = "Tailoring Supplies" }
npcs["Xor'juul"] = { role = "Hunter Trainer" }
npcs["Yama Snowhoof"] = { people = "Tauren" }
npcs["Yaw Sharpmane"] = { people = "Tauren", role = "Hunter Trainer" }
npcs["Yenniku"] = { role = "Darkspear Hostage" }
npcs["Yori Crackhelm"] = { people = "Dwarf" }
npcs["Yvette Farthing"] = { people = "Scourge" }
npcs["Zaldimar Wefhellt"] = { role = "Mage Trainer" }
npcs["Zamja"] = { people = "Troll", role = "Cooking Trainer" }
npcs["Zando'zan"] = { people = "Troll" }
npcs["Zangen Stonehoof"] = { people = "Tauren" }
npcs["Zargh"] = { role = "Butcher" }
npcs["Zarlman Two-Moons"] = { people = "Tauren" }
npcs["Zarrin"] = { people = "NightElf", role = "Cook" }
npcs["Zayus"] = { role = "High Priest" }
npcs["Zengu"] = { people = "Troll" }
npcs["Zenn Foulhoof"] = { people = "NightElf" }
npcs["Zevrost"] = { role = "Warlock Trainer" }
npcs["Zggi"] = { role = "Zardeth's Minion" }
npcs["Zilzibin Drumlore"] = { people = "Troll" }
npcs["Zjolnir"] = { people = "Troll", role = "Raptor Handler" }
npcs["Zor Lonetree"] = { role = "Elder Far Seer" }
