/**
 * writing/*.md → addon/WayfarersJournal/Data_Classic.lua, Data_Forever.lua
 *
 * Each file holds the sentences of one kind of moment:
 *
 *   ---
 *   kind: close-deep
 *   ---
 *   - It came down to a breath {at}. ...
 *   - [night hc] Night had fallen over {sub} when ...
 *   - [client:forever] ...
 *
 * A sentence's [tags] are the conditions it needs (all of them): the writer
 * gives each moment its tags (night, first, hc, race:Dwarf, class:PALADIN...).
 * Plain ASCII, like the siblings' content; {slots} are checked against the
 * kind's known slots once the writer exists.
 *
 *   bun scripts/build.ts          write the data files
 *   bun scripts/build.ts --check  fail if one isn't up to date
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const WRITING = join(ROOT, "writing");
const CLIENTS = ["classic", "forever"];
const GAMES = CLIENTS.map((client) => ({ client, out: join(ROOT, `addon/WayfarersJournal/Data_${client[0].toUpperCase()}${client.slice(1)}.lua`) }));
const errors: string[] = [];
const fail = (file: string, msg: string) => errors.push(`${file}: ${msg}`);
const q = (s: string) => JSON.stringify(s);

type Sentence = { text: string; tags: string[] };
const kinds = new Map<string, Sentence[]>();
for (const f of existsSync(WRITING) ? readdirSync(WRITING).sort() : []) {
  if (!f.endsWith(".md")) continue;
  const file = join(WRITING, f);
  const src = readFileSync(file, "utf8");
  const odd = src.match(/[^\x00-\x7f]/);
  if (odd) fail(file, `non-ASCII character "${odd[0]}": use ' and plain quotes`);
  const m = src.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) { fail(file, "no front matter"); continue; }
  const kind = m[1].match(/^kind:\s*(\S+)/m)?.[1];
  if (!kind) { fail(file, "kind: missing"); continue; }
  if (kinds.has(kind)) fail(file, `kind ${kind} twice`);
  const sentences: Sentence[] = [];
  for (const line of m[2].split("\n")) {
    const s = line.match(/^- (?:\[([^\]]*)\]\s*)?(.+)$/);
    if (!s) continue;
    sentences.push({ text: s[2].trim(), tags: (s[1] ?? "").split(/\s+/).filter(Boolean) });
  }
  if (!sentences.length) fail(file, "no sentence");
  kinds.set(kind, sentences);
}
if (errors.length) {
  console.error(errors.join("\n"));
  process.exit(1);
}

function luaFor(client: string) {
  const mine = (s: Sentence) => !s.tags.some((t) => t.startsWith("client:") && t !== `client:${client}`);
  const body = [...kinds.entries()]
    .map(([kind, list]) => `    [${q(kind)}] = {\n${list.filter(mine).map((s) => `      { ${q(s.text)}${s.tags.filter((t) => !t.startsWith("client:")).length ? `, tags = { ${s.tags.filter((t) => !t.startsWith("client:")).map(q).join(", ")} }` : ""} },`).join("\n")}\n    },`)
    .join("\n");
  return `-- Generated by scripts/build.ts from writing/: edit those, not this file.
local _, ns = ...
ns.data = {
  client = ${q(client)},
  writing = {
${body}
  },
}
`;
}

let stale = false;
for (const g of GAMES) {
  const lua = luaFor(g.client);
  if (process.argv.includes("--check")) {
    const current = existsSync(g.out) ? readFileSync(g.out, "utf8") : "";
    if (current !== lua) { console.error(`✗ ${g.out} is out of date: run bun scripts/build.ts`); stale = true; }
    else console.log(`✓ ${g.out} up to date (${kinds.size} kinds)`);
  } else {
    writeFileSync(g.out, lua);
    console.log(`✓ ${g.client}: ${kinds.size} kinds → ${g.out}`);
  }
}
if (stale) process.exit(1);
