-- Generated by scripts/build.ts from writing/: edit those, not this file.
local _, ns = ...
ns.data = {
  client = "classic",
  writing = {
    ["opening"] = {
      { "Morning at {where}." },
      { "I woke at {where} to a clear sky." },
      { "Night at {where}, and a long one.", tags = { "night" } },
    },
  },
}
